export const liquidGlass = {
  id: 'liquid-glass',
  name: 'Liquid Glass',
  seed: {
    primary: '#007AFF',
    accent: '#5856D6',
    tertiary: '#30D158',
    neutral: '#8E8E93',
    success: '#30D158',
    warning: '#FF9F0A',
    error: '#FF453A',
    info: '#64D2FF',
    bg: '#f5f5f7',
    bgDark: '#1c1c1e',
  },
  personality: {
    radius: 'rounded',
    elevation: 'glass',
    motion: 'smooth',
    borders: 'thin',
    density: 'comfortable',
    gradient: 'subtle',
  },
  typography: {
    '--d-font': '-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text",system-ui,sans-serif',
    '--d-font-mono': '"SF Mono",ui-monospace,monospace',
    '--d-fw-heading': '600',
    '--d-fw-title': '500',
    '--d-ls-heading': '-0.015em',
  },
  overrides: {
    light: {
      '--d-surface-1': 'rgba(255,255,255,0.72)',
      '--d-surface-2': 'rgba(255,255,255,0.82)',
      '--d-surface-3': 'rgba(255,255,255,0.9)',
      '--d-surface-1-filter': 'blur(20px) saturate(1.9)',
      '--d-surface-2-filter': 'blur(30px) saturate(2)',
      '--d-surface-3-filter': 'blur(40px) saturate(2.2)',
      '--d-border': 'rgba(0,0,0,0.08)',
      '--d-border-strong': 'rgba(0,0,0,0.15)',
    },
    dark: {
      '--d-surface-1': 'rgba(44,44,46,0.65)',
      '--d-surface-2': 'rgba(44,44,46,0.75)',
      '--d-surface-3': 'rgba(44,44,46,0.85)',
      '--d-surface-1-filter': 'blur(20px) saturate(1.6)',
      '--d-surface-2-filter': 'blur(30px) saturate(1.8)',
      '--d-surface-3-filter': 'blur(40px) saturate(2)',
      '--d-border': 'rgba(255,255,255,0.1)',
      '--d-border-strong': 'rgba(255,255,255,0.2)',
    },
  },
  components: [
    'body{font-family:var(--d-font);background:var(--d-bg);color:var(--d-fg);line-height:var(--d-lh-normal);-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;text-rendering:optimizeLegibility}',
    '::selection{background:var(--d-selection-bg);color:var(--d-selection-fg)}',
    '.d-card{border:0.5px solid rgba(0,0,0,0.06);box-shadow:var(--d-elevation-1),inset 0 0.5px 0 rgba(255,255,255,0.5)}',
    '.d-modal-content{border:0.5px solid rgba(0,0,0,0.08);box-shadow:var(--d-elevation-3),inset 0 0.5px 0 rgba(255,255,255,0.4)}',
    '::-webkit-scrollbar{width:7px;height:7px}',
    '::-webkit-scrollbar-track{background:transparent}',
    '::-webkit-scrollbar-thumb{background:rgba(0,0,0,0.15);border-radius:var(--d-radius-full);border:2px solid transparent;background-clip:content-box}',
    '::-webkit-scrollbar-thumb:hover{background:rgba(0,0,0,0.3);background-clip:content-box}',
    '.d-select-dropdown,.d-combobox-listbox,.d-dropdown-menu,.d-cascader-panel,.d-mentions-dropdown,.d-command{backdrop-filter:blur(30px) saturate(2);-webkit-backdrop-filter:blur(30px) saturate(2)}',
  ].join(''),
};
