import { css } from '@decantr/css';
import { TopNavFooterShell } from '@/layouts/TopNavFooterShell';

export function TermsPage() {
  return (
    <TopNavFooterShell>
      <section className={css('_py16 _px4')}>
        <div className={css('_flex _col _gap8') + ' container-sm'}>
          <div className={css('_flex _col _gap2')}>
            <h1 className={css('_text3xl _fontsemi _fgtext')}>Terms of Service</h1>
            <p className={css('_textsm _fgmuted')}>Last updated: March 15, 2026</p>
          </div>

          <div className="prose">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using Carbon AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              Carbon AI provides an AI-powered development assistant that helps developers write, review, and understand code. The service includes chat-based interaction, code generation, and project analysis features.
            </p>

            <h2>3. Account Registration</h2>
            <p>
              To use certain features of our service, you must register for an account. You agree to provide accurate, current, and complete information and to keep your account credentials secure.
            </p>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to the service</li>
              <li>Interfere with or disrupt the service</li>
              <li>Upload malicious code or content</li>
              <li>Reverse engineer or decompile any part of the service</li>
            </ul>

            <h2>5. Intellectual Property</h2>
            <p>
              Code generated by Carbon AI belongs to you. You retain full ownership of any code, content, or materials you create using our service. We claim no intellectual property rights over your generated output.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
              Carbon AI is provided "as is" without warranty of any kind. We are not liable for any damages arising from your use of the service, including but not limited to bugs in generated code.
            </p>

            <h2>7. Termination</h2>
            <p>
              We may terminate or suspend your account at any time for violation of these terms. You may terminate your account at any time through your account settings.
            </p>

            <h2>8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify you of significant changes via email or through the service.
            </p>

            <h2>9. Contact</h2>
            <p>
              Questions about these terms? Contact us at <strong>legal@carbonai.dev</strong>.
            </p>
          </div>
        </div>
      </section>
    </TopNavFooterShell>
  );
}
