import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const DIM = '\x1b[2m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';

export type ExportTarget = 'shadcn' | 'tailwind' | 'css-vars';

export interface ExportOptions {
  output?: string;
}

// ── Token Mapping ──

export const SHADCN_MAP: Record<string, string> = {
  '--d-bg': '--background',
  '--d-text': '--foreground',
  '--d-surface': '--card',
  '--d-surface-raised': '--popover',
  '--d-primary': '--primary',
  '--d-secondary': '--secondary',
  '--d-accent': '--accent',
  '--d-border': '--border',
  '--d-text-muted': '--muted-foreground',
  '--d-error': '--destructive',
  '--d-radius': '--radius',
};

export const TAILWIND_COLOR_MAP: Record<string, string> = {
  '--d-primary': 'primary',
  '--d-secondary': 'secondary',
  '--d-accent': 'accent',
  '--d-bg': 'background',
  '--d-surface': 'surface',
  '--d-surface-raised': 'surface-raised',
  '--d-border': 'border',
  '--d-text': 'foreground',
  '--d-text-muted': 'muted',
  '--d-success': 'success',
  '--d-error': 'error',
  '--d-warning': 'warning',
  '--d-info': 'info',
};

// ── CSS Parsing ──

export function parseTokensCSS(css: string): Map<string, string> {
  const tokens = new Map<string, string>();
  const re = /(--d-[\w-]+)\s*:\s*([^;]+);/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(css)) !== null) {
    tokens.set(match[1], match[2].trim());
  }
  return tokens;
}

// ── Generators ──

export function generateShadcnCSS(tokens: Map<string, string>): string {
  const lines: string[] = ['/* Exported by decantr export --to shadcn */', '@layer base {', '  :root {'];

  for (const [decantrVar, shadcnVar] of Object.entries(SHADCN_MAP)) {
    const value = tokens.get(decantrVar);
    if (value) {
      lines.push(`    ${shadcnVar}: ${value};`);
    }
  }

  // Map card-foreground and popover-foreground from text
  const textValue = tokens.get('--d-text');
  if (textValue) {
    lines.push(`    --card-foreground: ${textValue};`);
    lines.push(`    --popover-foreground: ${textValue};`);
  }

  // Map muted background from surface
  const surfaceValue = tokens.get('--d-surface');
  if (surfaceValue) {
    lines.push(`    --muted: ${surfaceValue};`);
  }

  // Map accent-foreground from text
  const accentFg = tokens.get('--d-text');
  if (accentFg) {
    lines.push(`    --accent-foreground: ${accentFg};`);
  }

  // Map destructive-foreground
  lines.push(`    --destructive-foreground: #FAFAFA;`);

  lines.push('  }', '}', '');
  return lines.join('\n');
}

export function generateShadcnComponentsJSON(): string {
  const config = {
    $schema: 'https://ui.shadcn.com/schema.json',
    style: 'default',
    rsc: false,
    tsx: true,
    tailwind: {
      config: 'tailwind.config.ts',
      css: 'src/styles/shadcn-theme.css',
      baseColor: 'zinc',
    },
    aliases: {
      components: '@/components',
      utils: '@/lib/utils',
    },
  };
  return JSON.stringify(config, null, 2) + '\n';
}

export function generateTailwindConfig(tokens: Map<string, string>): string {
  const colors: Record<string, string> = {};
  for (const [decantrVar, twName] of Object.entries(TAILWIND_COLOR_MAP)) {
    const value = tokens.get(decantrVar);
    if (value) {
      colors[twName] = value;
    }
  }

  const borderRadius: Record<string, string> = {};
  for (const suffix of ['', '-sm', '-lg', '-xl', '-full']) {
    const key = `--d-radius${suffix}`;
    const value = tokens.get(key);
    if (value) {
      const name = suffix ? suffix.slice(1) : 'DEFAULT';
      borderRadius[name] = value;
    }
  }

  const boxShadow: Record<string, string> = {};
  for (const suffix of ['-sm', '', '-md', '-lg']) {
    const key = `--d-shadow${suffix}`;
    const value = tokens.get(key);
    if (value) {
      const name = suffix ? suffix.slice(1) : 'DEFAULT';
      boxShadow[name] = value;
    }
  }

  const lines: string[] = [
    '// Generated by decantr export --to tailwind',
    "import type { Config } from 'tailwindcss';",
    '',
    'export default {',
    '  theme: {',
    '    extend: {',
  ];

  // Colors
  lines.push('      colors: {');
  for (const [name, value] of Object.entries(colors)) {
    lines.push(`        '${name}': '${value}',`);
  }
  lines.push('      },');

  // Border radius
  lines.push('      borderRadius: {');
  for (const [name, value] of Object.entries(borderRadius)) {
    lines.push(`        '${name}': '${value}',`);
  }
  lines.push('      },');

  // Box shadow
  lines.push('      boxShadow: {');
  for (const [name, value] of Object.entries(boxShadow)) {
    lines.push(`        '${name}': '${value}',`);
  }
  lines.push('      },');

  lines.push('    },', '  },', '} satisfies Partial<Config>;', '');
  return lines.join('\n');
}

export function generateCSSVars(tokens: Map<string, string>): string {
  const lines: string[] = ['/* Exported by decantr export --to css-vars */', ':root {'];

  for (const [key, value] of tokens) {
    lines.push(`  ${key}: ${value};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

// ── Main Command ──

export async function cmdExport(
  target: ExportTarget,
  projectRoot: string,
  options: ExportOptions = {}
): Promise<void> {
  const essencePath = join(projectRoot, 'decantr.essence.json');
  const tokensPath = join(projectRoot, 'src', 'styles', 'tokens.css');

  if (!existsSync(essencePath)) {
    console.error(`${RED}No decantr.essence.json found. Run \`decantr init\` first.${RESET}`);
    process.exitCode = 1;
    return;
  }

  if (!existsSync(tokensPath)) {
    console.error(`${RED}No src/styles/tokens.css found. Run \`decantr refresh\` to generate tokens.${RESET}`);
    process.exitCode = 1;
    return;
  }

  const tokensCSS = readFileSync(tokensPath, 'utf-8');
  const tokens = parseTokensCSS(tokensCSS);

  if (tokens.size === 0) {
    console.error(`${RED}No --d-* tokens found in tokens.css.${RESET}`);
    process.exitCode = 1;
    return;
  }

  switch (target) {
    case 'shadcn': {
      const cssOut = options.output ?? join(projectRoot, 'src', 'styles', 'shadcn-theme.css');
      const jsonOut = join(projectRoot, 'components.json');

      ensureDir(cssOut);
      writeFileSync(cssOut, generateShadcnCSS(tokens), 'utf-8');
      writeFileSync(jsonOut, generateShadcnComponentsJSON(), 'utf-8');

      console.log(`${GREEN}Exported shadcn theme:${RESET}`);
      console.log(`  ${DIM}CSS:${RESET}  ${cssOut}`);
      console.log(`  ${DIM}JSON:${RESET} ${jsonOut}`);
      break;
    }

    case 'tailwind': {
      const out = options.output ?? join(projectRoot, 'tailwind.decantr.config.ts');

      ensureDir(out);
      writeFileSync(out, generateTailwindConfig(tokens), 'utf-8');

      console.log(`${GREEN}Exported Tailwind config:${RESET}`);
      console.log(`  ${DIM}File:${RESET} ${out}`);
      break;
    }

    case 'css-vars': {
      const out = options.output ?? join(projectRoot, 'decantr-tokens.css');

      ensureDir(out);
      writeFileSync(out, generateCSSVars(tokens), 'utf-8');

      console.log(`${GREEN}Exported CSS variables:${RESET}`);
      console.log(`  ${DIM}File:${RESET} ${out}`);
      break;
    }
  }
}

function ensureDir(filePath: string): void {
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}
