export { createReactPlugin } from './plugin.js';
export { ATOM_TO_TAILWIND, atomsToTailwind, gapClass, gridClasses, spanClass, surfaceClasses } from './tailwind.js';
export { COMPONENT_MAP, resolveShadcnComponent, collectShadcnImports } from './shadcn.js';
export type { ShadcnMapping } from './shadcn.js';
export { validateReactOutput } from './quality-rules.js';
export type { QualityViolation } from './quality-rules.js';
export { emitAuth, hasAuth } from './emit-auth.js';
export { emitTheme, isThemeToggleable } from './emit-theme.js';
export { emitHooks, HOOK_REGISTRY } from './emit-hooks.js';
export type { HookMeta } from './emit-hooks.js';
