/**
 * Map Decantr component names to shadcn/ui component imports.
 */

export interface ShadcnMapping {
  /** shadcn component name */
  component: string;
  /** Import path (e.g. "@/components/ui/button") */
  importPath: string;
  /** Named exports to import */
  imports: string[];
  /** Additional notes */
  notes?: string;
}

// AUTO: Complete shadcn/ui component map — organized by category, alphabetical within each.
// Every shadcn/ui component is listed here so the generator can resolve any IR component reference.

export const COMPONENT_MAP: Record<string, ShadcnMapping> = {
  // ── Layout ──────────────────────────────────────────────────────────────
  AspectRatio: {
    component: 'AspectRatio',
    importPath: '@/components/ui/aspect-ratio',
    imports: ['AspectRatio'],
  },
  Card: {
    component: 'Card',
    importPath: '@/components/ui/card',
    imports: ['Card', 'CardHeader', 'CardTitle', 'CardDescription', 'CardContent', 'CardFooter'],
    notes: 'Card.Header → CardHeader+CardTitle, Card.Body → CardContent',
  },
  Collapsible: {
    component: 'Collapsible',
    importPath: '@/components/ui/collapsible',
    imports: ['Collapsible', 'CollapsibleTrigger', 'CollapsibleContent'],
  },
  ScrollArea: {
    component: 'ScrollArea',
    importPath: '@/components/ui/scroll-area',
    imports: ['ScrollArea', 'ScrollBar'],
  },
  Separator: {
    component: 'Separator',
    importPath: '@/components/ui/separator',
    imports: ['Separator'],
  },
  Sidebar: {
    component: 'Sidebar',
    importPath: '@/components/ui/sidebar',
    imports: [
      'Sidebar', 'SidebarContent', 'SidebarFooter', 'SidebarHeader',
      'SidebarMenu', 'SidebarMenuItem', 'SidebarMenuButton',
      'SidebarProvider', 'SidebarTrigger',
    ],
  },
  Tabs: {
    component: 'Tabs',
    importPath: '@/components/ui/tabs',
    imports: ['Tabs', 'TabsList', 'TabsTrigger', 'TabsContent'],
  },

  // ── Form ────────────────────────────────────────────────────────────────
  Button: {
    component: 'Button',
    importPath: '@/components/ui/button',
    imports: ['Button'],
  },
  Calendar: {
    component: 'Calendar',
    importPath: '@/components/ui/calendar',
    imports: ['Calendar'],
  },
  Checkbox: {
    component: 'Checkbox',
    importPath: '@/components/ui/checkbox',
    imports: ['Checkbox'],
  },
  Input: {
    component: 'Input',
    importPath: '@/components/ui/input',
    imports: ['Input'],
  },
  Label: {
    component: 'Label',
    importPath: '@/components/ui/label',
    imports: ['Label'],
  },
  RadioGroup: {
    component: 'RadioGroup',
    importPath: '@/components/ui/radio-group',
    imports: ['RadioGroup', 'RadioGroupItem'],
  },
  Select: {
    component: 'Select',
    importPath: '@/components/ui/select',
    imports: ['Select', 'SelectTrigger', 'SelectContent', 'SelectItem', 'SelectValue', 'SelectGroup'],
  },
  Slider: {
    component: 'Slider',
    importPath: '@/components/ui/slider',
    imports: ['Slider'],
  },
  Switch: {
    component: 'Switch',
    importPath: '@/components/ui/switch',
    imports: ['Switch'],
  },
  Textarea: {
    component: 'Textarea',
    importPath: '@/components/ui/textarea',
    imports: ['Textarea'],
  },
  Toggle: {
    component: 'Toggle',
    importPath: '@/components/ui/toggle',
    imports: ['Toggle'],
  },

  // ── Data Display ────────────────────────────────────────────────────────
  Avatar: {
    component: 'Avatar',
    importPath: '@/components/ui/avatar',
    imports: ['Avatar', 'AvatarImage', 'AvatarFallback'],
  },
  Badge: {
    component: 'Badge',
    importPath: '@/components/ui/badge',
    imports: ['Badge'],
  },
  Pagination: {
    component: 'Pagination',
    importPath: '@/components/ui/pagination',
    imports: ['Pagination', 'PaginationContent', 'PaginationItem', 'PaginationPrevious', 'PaginationNext'],
  },
  Progress: {
    component: 'Progress',
    importPath: '@/components/ui/progress',
    imports: ['Progress'],
  },
  Skeleton: {
    component: 'Skeleton',
    importPath: '@/components/ui/skeleton',
    imports: ['Skeleton'],
  },
  Table: {
    component: 'Table',
    importPath: '@/components/ui/table',
    imports: ['Table', 'TableHeader', 'TableBody', 'TableRow', 'TableHead', 'TableCell', 'TableFooter', 'TableCaption'],
  },

  // ── Overlay ─────────────────────────────────────────────────────────────
  AlertDialog: {
    component: 'AlertDialog',
    importPath: '@/components/ui/alert-dialog',
    imports: [
      'AlertDialog', 'AlertDialogTrigger', 'AlertDialogContent',
      'AlertDialogHeader', 'AlertDialogFooter', 'AlertDialogTitle',
      'AlertDialogDescription', 'AlertDialogAction', 'AlertDialogCancel',
    ],
  },
  Dialog: {
    component: 'Dialog',
    importPath: '@/components/ui/dialog',
    imports: ['Dialog', 'DialogTrigger', 'DialogContent', 'DialogHeader', 'DialogFooter', 'DialogTitle', 'DialogDescription'],
  },
  Drawer: {
    component: 'Drawer',
    importPath: '@/components/ui/drawer',
    imports: ['Drawer', 'DrawerTrigger', 'DrawerContent', 'DrawerHeader', 'DrawerFooter', 'DrawerTitle', 'DrawerDescription'],
  },
  HoverCard: {
    component: 'HoverCard',
    importPath: '@/components/ui/hover-card',
    imports: ['HoverCard', 'HoverCardTrigger', 'HoverCardContent'],
  },
  Popover: {
    component: 'Popover',
    importPath: '@/components/ui/popover',
    imports: ['Popover', 'PopoverContent', 'PopoverTrigger'],
  },
  Sheet: {
    component: 'Sheet',
    importPath: '@/components/ui/sheet',
    imports: ['Sheet', 'SheetTrigger', 'SheetContent', 'SheetHeader', 'SheetFooter', 'SheetTitle', 'SheetDescription'],
  },
  Tooltip: {
    component: 'Tooltip',
    importPath: '@/components/ui/tooltip',
    imports: ['Tooltip', 'TooltipTrigger', 'TooltipContent', 'TooltipProvider'],
  },

  // ── Navigation ──────────────────────────────────────────────────────────
  Breadcrumb: {
    component: 'Breadcrumb',
    importPath: '@/components/ui/breadcrumb',
    imports: ['Breadcrumb', 'BreadcrumbList', 'BreadcrumbItem', 'BreadcrumbLink', 'BreadcrumbSeparator', 'BreadcrumbPage'],
  },
  Command: {
    component: 'Command',
    importPath: '@/components/ui/command',
    imports: ['Command', 'CommandDialog', 'CommandInput', 'CommandList', 'CommandEmpty', 'CommandGroup', 'CommandItem', 'CommandSeparator'],
    notes: 'Decantr Command palette → shadcn Command / CommandDialog',
  },
  ContextMenu: {
    component: 'ContextMenu',
    importPath: '@/components/ui/context-menu',
    imports: ['ContextMenu', 'ContextMenuTrigger', 'ContextMenuContent', 'ContextMenuItem', 'ContextMenuSeparator'],
  },
  DropdownMenu: {
    component: 'DropdownMenu',
    importPath: '@/components/ui/dropdown-menu',
    imports: ['DropdownMenu', 'DropdownMenuTrigger', 'DropdownMenuContent', 'DropdownMenuItem', 'DropdownMenuSeparator', 'DropdownMenuLabel', 'DropdownMenuGroup'],
  },
  Menubar: {
    component: 'Menubar',
    importPath: '@/components/ui/menubar',
    imports: ['Menubar', 'MenubarMenu', 'MenubarTrigger', 'MenubarContent', 'MenubarItem', 'MenubarSeparator'],
  },
  NavigationMenu: {
    component: 'NavigationMenu',
    importPath: '@/components/ui/navigation-menu',
    imports: ['NavigationMenu', 'NavigationMenuList', 'NavigationMenuItem', 'NavigationMenuLink', 'NavigationMenuTrigger', 'NavigationMenuContent'],
  },

  // ── Feedback ────────────────────────────────────────────────────────────
  Accordion: {
    component: 'Accordion',
    importPath: '@/components/ui/accordion',
    imports: ['Accordion', 'AccordionItem', 'AccordionTrigger', 'AccordionContent'],
  },
  Alert: {
    component: 'Alert',
    importPath: '@/components/ui/alert',
    imports: ['Alert', 'AlertTitle', 'AlertDescription'],
  },
  Toast: {
    component: 'Toast',
    importPath: '@/components/ui/toast',
    imports: ['Toast', 'ToastAction'],
    notes: 'Also requires Toaster from @/components/ui/toaster and useToast hook',
  },

  // ── Aliases ─────────────────────────────────────────────────────────────
  // AUTO: Decantr abstract names that map to shadcn equivalents
  Modal: {
    component: 'Dialog',
    importPath: '@/components/ui/dialog',
    imports: ['Dialog', 'DialogTrigger', 'DialogContent', 'DialogHeader', 'DialogFooter', 'DialogTitle', 'DialogDescription'],
    notes: 'Modal → Dialog (alias)',
  },
  Dropdown: {
    component: 'DropdownMenu',
    importPath: '@/components/ui/dropdown-menu',
    imports: ['DropdownMenu', 'DropdownMenuTrigger', 'DropdownMenuContent', 'DropdownMenuItem', 'DropdownMenuSeparator', 'DropdownMenuLabel', 'DropdownMenuGroup'],
    notes: 'Dropdown → DropdownMenu (alias)',
  },
  Chip: {
    component: 'Badge',
    importPath: '@/components/ui/badge',
    imports: ['Badge'],
    notes: 'Chip → Badge (alias)',
  },
};

// AUTO: Pattern-level shadcn templates for patterns that need specific React layouts
// beyond the generic Card-based template in buildPatternComponent
export interface PatternShadcnTemplate {
  /** Additional shadcn component imports needed */
  imports: Map<string, string[]>;
  /** Function that generates the JSX body for the pattern */
  body: (gapClass: string) => string;
}

export const PATTERN_TEMPLATE_MAP: Record<string, PatternShadcnTemplate> = {
  // AUTO: data-table pattern template for React + shadcn/ui emission
  'data-table': {
    imports: new Map([
      ['@/components/ui/table', ['Table', 'TableHeader', 'TableBody', 'TableRow', 'TableHead', 'TableCell']],
      ['@/components/ui/checkbox', ['Checkbox']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/input', ['Input']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/dropdown-menu', ['DropdownMenu', 'DropdownMenuContent', 'DropdownMenuItem', 'DropdownMenuTrigger']],
    ]),
    body: (gap: string) => [
      `    <div className="flex flex-col ${gap} w-full overflow-auto">`,
      `      <div className="flex items-center justify-between ${gap}">`,
      `        <Input placeholder="Search..." className="max-w-sm" />`,
      `        <div className="flex gap-2">`,
      `          <DropdownMenu>`,
      `            <DropdownMenuTrigger asChild>`,
      `              <Button variant="outline" size="sm">Columns</Button>`,
      `            </DropdownMenuTrigger>`,
      `            <DropdownMenuContent align="end">`,
      `              {["Name", "Status", "Email", "Amount"].map((col) => (`,
      `                <DropdownMenuItem key={col}>{col}</DropdownMenuItem>`,
      `              ))}`,
      `            </DropdownMenuContent>`,
      `          </DropdownMenu>`,
      `          <Button variant="outline" size="sm">Export</Button>`,
      `        </div>`,
      `      </div>`,
      `      <div className="rounded-md border">`,
      `        <Table>`,
      `          <TableHeader>`,
      `            <TableRow>`,
      `              <TableHead className="w-12"><Checkbox /></TableHead>`,
      `              <TableHead>Name</TableHead>`,
      `              <TableHead>Status</TableHead>`,
      `              <TableHead>Email</TableHead>`,
      `              <TableHead className="text-right">Amount</TableHead>`,
      `            </TableRow>`,
      `          </TableHeader>`,
      `          <TableBody>`,
      `            {[`,
      `              { name: "Alice Johnson", status: "active", email: "alice@example.com", amount: "$1,200" },`,
      `              { name: "Bob Smith", status: "inactive", email: "bob@example.com", amount: "$890" },`,
      `              { name: "Carol White", status: "active", email: "carol@example.com", amount: "$2,100" },`,
      `            ].map((row) => (`,
      `              <TableRow key={row.email}>`,
      `                <TableCell><Checkbox /></TableCell>`,
      `                <TableCell className="font-medium">{row.name}</TableCell>`,
      `                <TableCell><Badge variant={row.status === "active" ? "default" : "secondary"}>{row.status}</Badge></TableCell>`,
      `                <TableCell>{row.email}</TableCell>`,
      `                <TableCell className="text-right">{row.amount}</TableCell>`,
      `              </TableRow>`,
      `            ))}`,
      `          </TableBody>`,
      `        </Table>`,
      `      </div>`,
      `      <div className="flex items-center justify-between py-2">`,
      `        <p className="text-sm text-muted-foreground">3 row(s)</p>`,
      `        <div className="flex gap-2">`,
      `          <Button variant="outline" size="sm" disabled>Previous</Button>`,
      `          <Button variant="outline" size="sm">Next</Button>`,
      `        </div>`,
      `      </div>`,
      `    </div>`,
    ].join('\n'),
  },
  // AUTO: filter-bar pattern template for React + shadcn/ui emission
  'filter-bar': {
    imports: new Map([
      ['@/components/ui/input', ['Input']],
      ['@/components/ui/select', ['Select', 'SelectTrigger', 'SelectContent', 'SelectItem', 'SelectValue']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/popover', ['Popover', 'PopoverContent', 'PopoverTrigger']],
    ]),
    body: (gap: string) => [
      `    <div className="flex flex-row items-center ${gap} w-full py-2">`,
      `      <Input placeholder="Search..." className="max-w-sm flex-1" />`,
      `      <Select>`,
      `        <SelectTrigger className="w-[160px]">`,
      `          <SelectValue placeholder="Category" />`,
      `        </SelectTrigger>`,
      `        <SelectContent>`,
      `          {["All Categories", "Active", "Archived"].map((opt) => (`,
      `            <SelectItem key={opt} value={opt.toLowerCase().replace(/ /g, "-")}>{opt}</SelectItem>`,
      `          ))}`,
      `        </SelectContent>`,
      `      </Select>`,
      `      <Select>`,
      `        <SelectTrigger className="w-[140px]">`,
      `          <SelectValue placeholder="Status" />`,
      `        </SelectTrigger>`,
      `        <SelectContent>`,
      `          {["All", "Published", "Draft"].map((opt) => (`,
      `            <SelectItem key={opt} value={opt.toLowerCase()}>{opt}</SelectItem>`,
      `          ))}`,
      `        </SelectContent>`,
      `      </Select>`,
      `      <div className="flex gap-2 ml-auto">`,
      `        <Button variant="outline" size="sm">Clear</Button>`,
      `        <Button size="sm">Apply</Button>`,
      `      </div>`,
      `    </div>`,
    ].join('\n'),
  },
  // AUTO: card-grid pattern templates for React + shadcn/ui emission
  'card-grid': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardHeader', 'CardContent', 'CardFooter', 'CardTitle']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/aspect-ratio', ['AspectRatio']],
    ]),
    body: (gap: string) => [
      `    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 ${gap}">`,
      `      {[`,
      `        { name: "Wireless Headphones", price: "$79.99", rating: 4.5, reviews: 128, image: "/images/headphones.jpg" },`,
      `        { name: "Mechanical Keyboard", price: "$149.99", rating: 4.8, reviews: 256, image: "/images/keyboard.jpg" },`,
      `        { name: "USB-C Hub", price: "$49.99", rating: 4.2, reviews: 89, image: "/images/hub.jpg" },`,
      `        { name: "Webcam HD", price: "$69.99", rating: 4.6, reviews: 312, image: "/images/webcam.jpg" },`,
      `      ].map((product) => (`,
      `        <Card key={product.name} className="flex flex-col overflow-hidden">`,
      `          <AspectRatio ratio={4 / 3}>`,
      `            <img src={product.image} alt={product.name} className="w-full h-full object-cover" />`,
      `          </AspectRatio>`,
      `          <CardContent className="flex flex-col gap-2 p-4">`,
      `            <p className="text-sm font-medium">{product.name}</p>`,
      `            <p className="text-xl font-bold">{product.price}</p>`,
      `            <div className="flex items-center gap-1">`,
      `              <Badge variant="secondary">{product.reviews} reviews</Badge>`,
      `            </div>`,
      `          </CardContent>`,
      `          <CardFooter className="p-4 pt-0">`,
      `            <Button size="sm" className="w-full">Add to Cart</Button>`,
      `          </CardFooter>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
  'card-grid:content': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent', 'CardHeader', 'CardTitle']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/avatar', ['Avatar', 'AvatarImage', 'AvatarFallback']],
    ]),
    body: (gap: string) => [
      `    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 ${gap}">`,
      `      {[`,
      `        { title: "Getting Started with Decantr", excerpt: "Learn how to build your first app.", category: "Tutorial", author: "Jane Doe", date: "2025-03-15", image: "/images/post1.jpg" },`,
      `        { title: "Advanced Signal Patterns", excerpt: "Deep dive into reactive signal composition.", category: "Guide", author: "John Smith", date: "2025-03-12", image: "/images/post2.jpg" },`,
      `        { title: "Registry-Driven UI", excerpt: "How the content registry powers generation.", category: "Architecture", author: "Alex Chen", date: "2025-03-10", image: "/images/post3.jpg" },`,
      `      ].map((post) => (`,
      `        <Card key={post.title} className="flex flex-col overflow-hidden">`,
      `          <CardHeader className="p-0">`,
      `            <div className="aspect-video overflow-hidden">`,
      `              <img src={post.image} alt={post.title} className="w-full h-full object-cover" />`,
      `            </div>`,
      `          </CardHeader>`,
      `          <CardContent className="flex flex-col gap-3 p-4">`,
      `            <Badge variant="outline" className="w-fit">{post.category}</Badge>`,
      `            <CardTitle className="text-lg">{post.title}</CardTitle>`,
      `            <p className="text-sm text-muted-foreground line-clamp-2">{post.excerpt}</p>`,
      `            <div className="flex items-center gap-2 text-sm text-muted-foreground">`,
      `              <Avatar className="h-6 w-6">`,
      `                <AvatarFallback>{post.author[0]}</AvatarFallback>`,
      `              </Avatar>`,
      `              <span>{post.author}</span>`,
      `              <span>&middot;</span>`,
      `              <time>{post.date}</time>`,
      `            </div>`,
      `          </CardContent>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
  'card-grid:collection': {
    imports: new Map([
      ['@/components/ui/card', ['Card']],
      ['@/components/ui/badge', ['Badge']],
    ]),
    body: (gap: string) => [
      `    <div className="grid grid-cols-2 lg:grid-cols-3 ${gap}">`,
      `      {[`,
      `        { name: "Electronics", count: 234, image: "/images/electronics.jpg" },`,
      `        { name: "Clothing", count: 567, image: "/images/clothing.jpg" },`,
      `        { name: "Home & Garden", count: 189, image: "/images/home.jpg" },`,
      `        { name: "Sports", count: 312, image: "/images/sports.jpg" },`,
      `        { name: "Books", count: 445, image: "/images/books.jpg" },`,
      `        { name: "Toys", count: 178, image: "/images/toys.jpg" },`,
      `      ].map((col) => (`,
      `        <Card key={col.name} className="relative aspect-[3/2] overflow-hidden cursor-pointer group">`,
      `          <img src={col.image} alt={col.name} className="absolute inset-0 w-full h-full object-cover transition group-hover:scale-105" />`,
      `          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black/70" />`,
      `          <div className="absolute bottom-0 left-0 right-0 p-4 flex justify-between items-center">`,
      `            <h3 className="text-lg font-semibold text-white">{col.name}</h3>`,
      `            <Badge variant="secondary">{col.count} items</Badge>`,
      `          </div>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
  'card-grid:icon': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent']],
    ]),
    body: (gap: string) => [
      `    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 ${gap}">`,
      `      {[`,
      `        { title: "Fast Build", description: "Lightning-fast compilation and HMR" },`,
      `        { title: "Type Safe", description: "Full TypeScript support out of the box" },`,
      `        { title: "Responsive", description: "Mobile-first responsive design system" },`,
      `        { title: "Accessible", description: "WCAG 2.1 AA compliant components" },`,
      `        { title: "Themeable", description: "Dark mode and custom theme support" },`,
      `        { title: "Extensible", description: "Plugin architecture for custom needs" },`,
      `        { title: "Tested", description: "Comprehensive test coverage built in" },`,
      `        { title: "Documented", description: "Detailed docs with live examples" },`,
      `      ].map((feature) => (`,
      `        <Card key={feature.title}>`,
      `          <CardContent className="flex flex-col items-center text-center gap-2 p-4">`,
      `            <div className="w-10 h-10 flex items-center justify-center rounded-full bg-muted" />`,
      `            <h4 className="text-sm font-medium">{feature.title}</h4>`,
      `            <p className="text-xs text-muted-foreground">{feature.description}</p>`,
      `          </CardContent>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
  // AUTO: chart-grid pattern templates for React + shadcn/ui emission
  'chart-grid': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent', 'CardHeader', 'CardTitle']],
    ]),
    body: (gap: string) => [
      `    {/* AUTO: Replace with Recharts/Chart.js component */}`,
      `    {/* import { LineChart, Line, BarChart, Bar, PieChart, Pie, AreaChart, Area, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer } from "recharts"; */}`,
      `    <div className="grid grid-cols-1 lg:grid-cols-2 ${gap}">`,
      `      {[`,
      `        { title: "Revenue Over Time", type: "line", legends: ["Revenue", "Expenses"] },`,
      `        { title: "Users by Region", type: "bar", legends: ["NA", "EU", "APAC"] },`,
      `        { title: "Traffic Sources", type: "pie", legends: ["Organic", "Paid", "Referral"] },`,
      `        { title: "Engagement Trend", type: "area", legends: ["Sessions", "Bounce Rate"] },`,
      `      ].map((chart) => (`,
      `        <Card key={chart.title}>`,
      `          <CardHeader>`,
      `            <CardTitle className="text-sm font-medium">{chart.title}</CardTitle>`,
      `          </CardHeader>`,
      `          <CardContent>`,
      `            {/* AUTO: Replace with Recharts/Chart.js component */}`,
      `            <div className="min-h-[200px] rounded-md bg-muted/10 flex items-center justify-center" data-chart-type={chart.type}>`,
      `              <span className="text-sm text-muted-foreground">[{chart.type} chart placeholder]</span>`,
      `            </div>`,
      `            <div className="flex gap-2 mt-2">`,
      `              {chart.legends.map((legend) => (`,
      `                <div key={legend} className="flex items-center gap-1 text-xs text-muted-foreground">`,
      `                  <div className="w-2 h-2 rounded-full bg-primary" />`,
      `                  <span>{legend}</span>`,
      `                </div>`,
      `              ))}`,
      `            </div>`,
      `          </CardContent>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
  'chart-grid:wide': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent', 'CardHeader', 'CardTitle']],
    ]),
    body: (gap: string) => [
      `    {/* AUTO: Replace with Recharts/Chart.js component */}`,
      `    <div className="flex flex-row ${gap} overflow-auto">`,
      `      {[`,
      `        { title: "Revenue Over Time", type: "line" },`,
      `        { title: "Users by Region", type: "bar" },`,
      `        { title: "Traffic Sources", type: "pie" },`,
      `      ].map((chart) => (`,
      `        <Card key={chart.title} className="min-w-[300px] shrink-0">`,
      `          <CardHeader>`,
      `            <CardTitle className="text-sm font-medium">{chart.title}</CardTitle>`,
      `          </CardHeader>`,
      `          <CardContent>`,
      `            <div className="min-h-[200px] rounded-md bg-muted/10 flex items-center justify-center" data-chart-type={chart.type}>`,
      `              <span className="text-sm text-muted-foreground">[{chart.type} chart placeholder]</span>`,
      `            </div>`,
      `          </CardContent>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
  'chart-grid:mixed': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent', 'CardHeader', 'CardTitle']],
    ]),
    body: (gap: string) => [
      `    {/* AUTO: Replace with Recharts/Chart.js component */}`,
      `    <div className="grid grid-cols-1 lg:grid-cols-2 ${gap}">`,
      `      <Card className="lg:col-span-2">`,
      `        <CardHeader>`,
      `          <CardTitle className="text-sm font-medium">Revenue Overview</CardTitle>`,
      `        </CardHeader>`,
      `        <CardContent>`,
      `          <div className="min-h-[300px] rounded-md bg-muted/10 flex items-center justify-center" data-chart-type="area">`,
      `            <span className="text-sm text-muted-foreground">[area chart placeholder]</span>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <Card>`,
      `        <CardHeader>`,
      `          <CardTitle className="text-sm font-medium">Users by Source</CardTitle>`,
      `        </CardHeader>`,
      `        <CardContent>`,
      `          <div className="min-h-[200px] rounded-md bg-muted/10 flex items-center justify-center" data-chart-type="pie">`,
      `            <span className="text-sm text-muted-foreground">[pie chart placeholder]</span>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <Card>`,
      `        <CardHeader>`,
      `          <CardTitle className="text-sm font-medium">Conversion Rate</CardTitle>`,
      `        </CardHeader>`,
      `        <CardContent>`,
      `          <div className="min-h-[200px] rounded-md bg-muted/10 flex items-center justify-center" data-chart-type="bar">`,
      `            <span className="text-sm text-muted-foreground">[bar chart placeholder]</span>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `    </div>`,
    ].join('\n'),
  },
  // AUTO: form-sections pattern templates for React + shadcn/ui emission
  'form-sections': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardHeader', 'CardTitle', 'CardContent']],
      ['@/components/ui/input', ['Input']],
      ['@/components/ui/label', ['Label']],
      ['@/components/ui/textarea', ['Textarea']],
      ['@/components/ui/select', ['Select', 'SelectTrigger', 'SelectContent', 'SelectItem', 'SelectValue']],
      ['@/components/ui/switch', ['Switch']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/separator', ['Separator']],
    ]),
    body: (gap: string) => [
      `    <form className="flex flex-col ${gap} p-4" onSubmit={(e) => e.preventDefault()}>`,
      `      <Card>`,
      `        <CardContent className="grid grid-cols-1 lg:grid-cols-2 gap-4 p-6">`,
      `          <div className="flex flex-col gap-1">`,
      `            <h3 className="text-lg font-semibold">Profile</h3>`,
      `            <p className="text-sm text-muted-foreground">Your personal information</p>`,
      `          </div>`,
      `          <div className="flex flex-col gap-4">`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="name">Display Name</Label>`,
      `              <Input id="name" placeholder="Enter your name" />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="bio">Bio</Label>`,
      `              <Textarea id="bio" placeholder="Tell us about yourself" rows={3} />`,
      `            </div>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <Separator />`,
      `      <Card>`,
      `        <CardContent className="grid grid-cols-1 lg:grid-cols-2 gap-4 p-6">`,
      `          <div className="flex flex-col gap-1">`,
      `            <h3 className="text-lg font-semibold">Notifications</h3>`,
      `            <p className="text-sm text-muted-foreground">Manage notification preferences</p>`,
      `          </div>`,
      `          <div className="flex flex-col gap-4">`,
      `            <div className="flex items-center justify-between">`,
      `              <Label>Email Notifications</Label>`,
      `              <Switch />`,
      `            </div>`,
      `            <div className="flex items-center justify-between">`,
      `              <Label>Push Notifications</Label>`,
      `              <Switch />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label>Frequency</Label>`,
      `              <Select>`,
      `                <SelectTrigger className="w-full">`,
      `                  <SelectValue placeholder="Select frequency" />`,
      `                </SelectTrigger>`,
      `                <SelectContent>`,
      `                  {["Immediately", "Daily Digest", "Weekly"].map((opt) => (`,
      `                    <SelectItem key={opt} value={opt.toLowerCase().replace(/ /g, "-")}>{opt}</SelectItem>`,
      `                  ))}`,
      `                </SelectContent>`,
      `              </Select>`,
      `            </div>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <div className="flex gap-3 justify-end">`,
      `        <Button variant="outline" type="button">Cancel</Button>`,
      `        <Button type="submit">Save Changes</Button>`,
      `      </div>`,
      `    </form>`,
    ].join('\n'),
  },
  'form-sections:creation': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent']],
      ['@/components/ui/input', ['Input']],
      ['@/components/ui/label', ['Label']],
      ['@/components/ui/textarea', ['Textarea']],
      ['@/components/ui/select', ['Select', 'SelectTrigger', 'SelectContent', 'SelectItem', 'SelectValue']],
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <form className="flex flex-col ${gap} p-4 max-w-[640px] mx-auto" onSubmit={(e) => e.preventDefault()}>`,
      `      <div className="flex gap-2 items-center">`,
      `        <span className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-sm font-bold">1</span>`,
      `        <div className="flex-1 h-px bg-muted" />`,
      `        <span className="w-8 h-8 rounded-full bg-muted text-muted-foreground flex items-center justify-center text-sm">2</span>`,
      `        <div className="flex-1 h-px bg-muted" />`,
      `        <span className="w-8 h-8 rounded-full bg-muted text-muted-foreground flex items-center justify-center text-sm">3</span>`,
      `      </div>`,
      `      <Card>`,
      `        <CardContent className="flex flex-col gap-4 p-6">`,
      `          <h3 className="text-lg font-semibold">Basic Information</h3>`,
      `          <p className="text-sm text-muted-foreground">Step 1 of 3</p>`,
      `          <div className="flex flex-col gap-4">`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="project">Project Name</Label>`,
      `              <Input id="project" placeholder="My Project" />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="desc">Description</Label>`,
      `              <Textarea id="desc" placeholder="Describe your project" rows={3} />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label>Category</Label>`,
      `              <Select>`,
      `                <SelectTrigger className="w-full">`,
      `                  <SelectValue placeholder="Select category" />`,
      `                </SelectTrigger>`,
      `                <SelectContent>`,
      `                  {["Web App", "Mobile App", "API Service", "Library"].map((opt) => (`,
      `                    <SelectItem key={opt} value={opt.toLowerCase().replace(/ /g, "-")}>{opt}</SelectItem>`,
      `                  ))}`,
      `                </SelectContent>`,
      `              </Select>`,
      `            </div>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <div className="flex justify-between">`,
      `        <Button variant="outline" type="button">Cancel</Button>`,
      `        <div className="flex gap-3">`,
      `          <Button variant="outline" type="button" disabled>Previous</Button>`,
      `          <Button type="submit">Next</Button>`,
      `        </div>`,
      `      </div>`,
      `    </form>`,
    ].join('\n'),
  },
  'form-sections:structured': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent']],
      ['@/components/ui/input', ['Input']],
      ['@/components/ui/label', ['Label']],
      ['@/components/ui/checkbox', ['Checkbox']],
      ['@/components/ui/radio-group', ['RadioGroup', 'RadioGroupItem']],
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <form className="flex flex-col ${gap} p-4" onSubmit={(e) => e.preventDefault()}>`,
      `      <Card>`,
      `        <CardContent className="flex flex-col gap-4 p-6">`,
      `          <h4 className="text-base font-medium">Contact Details</h4>`,
      `          <div className="grid grid-cols-2 gap-4">`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="firstName">First Name</Label>`,
      `              <Input id="firstName" placeholder="First name" required />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="lastName">Last Name</Label>`,
      `              <Input id="lastName" placeholder="Last name" required />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="email">Email</Label>`,
      `              <Input id="email" type="email" placeholder="email@example.com" />`,
      `            </div>`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label htmlFor="phone">Phone</Label>`,
      `              <Input id="phone" type="tel" placeholder="+1 (555) 000-0000" />`,
      `            </div>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <Card>`,
      `        <CardContent className="flex flex-col gap-4 p-6">`,
      `          <h4 className="text-base font-medium">Preferences</h4>`,
      `          <div className="flex flex-col gap-4">`,
      `            <div className="flex flex-col gap-2">`,
      `              <Label>Contact Method</Label>`,
      `              <RadioGroup defaultValue="email">`,
      `                {["Email", "Phone", "SMS"].map((opt) => (`,
      `                  <div key={opt} className="flex items-center gap-2">`,
      `                    <RadioGroupItem value={opt.toLowerCase()} id={opt.toLowerCase()} />`,
      `                    <Label htmlFor={opt.toLowerCase()}>{opt}</Label>`,
      `                  </div>`,
      `                ))}`,
      `              </RadioGroup>`,
      `            </div>`,
      `            <div className="flex items-center gap-2">`,
      `              <Checkbox id="newsletter" />`,
      `              <Label htmlFor="newsletter">Subscribe to newsletter</Label>`,
      `            </div>`,
      `            <div className="flex items-center gap-2">`,
      `              <Checkbox id="terms" />`,
      `              <Label htmlFor="terms">Agree to terms and conditions</Label>`,
      `            </div>`,
      `          </div>`,
      `        </CardContent>`,
      `      </Card>`,
      `      <div className="flex gap-3 justify-end">`,
      `        <Button variant="ghost" type="button">Reset</Button>`,
      `        <Button variant="outline" type="button">Cancel</Button>`,
      `        <Button type="submit">Save</Button>`,
      `      </div>`,
      `    </form>`,
    ].join('\n'),
  },
  // AUTO: activity-feed pattern template for React + shadcn/ui emission
  'activity-feed': {
    imports: new Map([
      ['@/components/ui/avatar', ['Avatar', 'AvatarImage', 'AvatarFallback']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/separator', ['Separator']],
      ['@/components/ui/scroll-area', ['ScrollArea']],
    ]),
    body: (gap: string) => [
      `    <ScrollArea className="h-[480px] w-full">`,
      `      <div className="flex flex-col ${gap}">`,
      `        <h4 className="text-sm font-medium text-muted-foreground py-2">Today</h4>`,
      `        {[`,
      `          { user: "Alice Johnson", initials: "AJ", action: "created a new project", type: "create", time: "2 hours ago" },`,
      `          { user: "Bob Smith", initials: "BS", action: "commented on issue #42", type: "comment", time: "4 hours ago" },`,
      `        ].map((item) => (`,
      `          <div key={item.action} className="flex items-start gap-3 py-2">`,
      `            <Avatar className="h-8 w-8">`,
      `              <AvatarFallback>{item.initials}</AvatarFallback>`,
      `            </Avatar>`,
      `            <div className="flex flex-col gap-1 flex-1">`,
      `              <p className="text-sm">`,
      `                <span className="font-medium">{item.user}</span>`,
      `                {" "}{item.action}`,
      `              </p>`,
      `              <time className="text-xs text-muted-foreground">{item.time}</time>`,
      `            </div>`,
      `            <Badge variant="outline">{item.type}</Badge>`,
      `          </div>`,
      `        ))}`,
      `        <Separator />`,
      `        <h4 className="text-sm font-medium text-muted-foreground py-2">Yesterday</h4>`,
      `        {[`,
      `          { user: "Carol White", initials: "CW", action: "deployed v2.1.0 to production", type: "deploy", time: "1 day ago" },`,
      `        ].map((item) => (`,
      `          <div key={item.action} className="flex items-start gap-3 py-2">`,
      `            <Avatar className="h-8 w-8">`,
      `              <AvatarFallback>{item.initials}</AvatarFallback>`,
      `            </Avatar>`,
      `            <div className="flex flex-col gap-1 flex-1">`,
      `              <p className="text-sm">`,
      `                <span className="font-medium">{item.user}</span>`,
      `                {" "}{item.action}`,
      `              </p>`,
      `              <time className="text-xs text-muted-foreground">{item.time}</time>`,
      `            </div>`,
      `            <Badge variant="outline">{item.type}</Badge>`,
      `          </div>`,
      `        ))}`,
      `        <div className="flex justify-center pt-4">`,
      `          <Button variant="outline" size="sm">Load more</Button>`,
      `        </div>`,
      `      </div>`,
      `    </ScrollArea>`,
    ].join('\n'),
  },
  // AUTO: detail-header pattern templates for React + shadcn/ui emission
  'detail-header': {
    imports: new Map([
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/breadcrumb', ['Breadcrumb', 'BreadcrumbList', 'BreadcrumbItem', 'BreadcrumbLink', 'BreadcrumbSeparator']],
      ['@/components/ui/separator', ['Separator']],
      ['@/components/ui/dropdown-menu', ['DropdownMenu', 'DropdownMenuContent', 'DropdownMenuItem', 'DropdownMenuTrigger']],
    ]),
    body: (gap: string) => [
      `    <div className="flex flex-col ${gap} pb-4 border-b">`,
      `      <Breadcrumb>`,
      `        <BreadcrumbList>`,
      `          <BreadcrumbItem>`,
      `            <BreadcrumbLink href="/">Home</BreadcrumbLink>`,
      `          </BreadcrumbItem>`,
      `          <BreadcrumbSeparator />`,
      `          <BreadcrumbItem>`,
      `            <BreadcrumbLink href="/items">Items</BreadcrumbLink>`,
      `          </BreadcrumbItem>`,
      `          <BreadcrumbSeparator />`,
      `          <BreadcrumbItem>`,
      `            <BreadcrumbLink>Detail</BreadcrumbLink>`,
      `          </BreadcrumbItem>`,
      `        </BreadcrumbList>`,
      `      </Breadcrumb>`,
      `      <div className="flex items-center justify-between">`,
      `        <div className="flex flex-col gap-1">`,
      `          <div className="flex items-center gap-3">`,
      `            <h1 className="text-2xl font-bold tracking-tight">Item Title</h1>`,
      `            <Badge>Active</Badge>`,
      `          </div>`,
      `          <p className="text-sm text-muted-foreground">Item description goes here</p>`,
      `        </div>`,
      `        <div className="flex gap-2">`,
      `          <Button variant="outline" size="sm">Share</Button>`,
      `          <Button variant="outline" size="sm">Edit</Button>`,
      `          <DropdownMenu>`,
      `            <DropdownMenuTrigger asChild>`,
      `              <Button variant="outline" size="sm">More</Button>`,
      `            </DropdownMenuTrigger>`,
      `            <DropdownMenuContent align="end">`,
      `              <DropdownMenuItem>Duplicate</DropdownMenuItem>`,
      `              <DropdownMenuItem className="text-destructive">Delete</DropdownMenuItem>`,
      `            </DropdownMenuContent>`,
      `          </DropdownMenu>`,
      `        </div>`,
      `      </div>`,
      `    </div>`,
    ].join('\n'),
  },
  'detail-header:profile': {
    imports: new Map([
      ['@/components/ui/avatar', ['Avatar', 'AvatarImage', 'AvatarFallback']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/separator', ['Separator']],
    ]),
    body: (gap: string) => [
      `    <div className="flex items-start ${gap}">`,
      `      <Avatar className="h-24 w-24">`,
      `        <AvatarImage src="/images/avatar.jpg" alt="User" />`,
      `        <AvatarFallback>UN</AvatarFallback>`,
      `      </Avatar>`,
      `      <div className="flex flex-col gap-2 flex-1">`,
      `        <div className="flex items-center gap-3">`,
      `          <h1 className="text-2xl font-bold tracking-tight">User Name</h1>`,
      `          <Badge variant="secondary">Member</Badge>`,
      `        </div>`,
      `        <p className="text-sm text-muted-foreground">Software Engineer</p>`,
      `        <p className="text-sm text-muted-foreground">No bio provided.</p>`,
      `        <div className="flex gap-6 mt-2">`,
      `          {[`,
      `            { label: "Followers", value: "1,234" },`,
      `            { label: "Following", value: "567" },`,
      `            { label: "Posts", value: "89" },`,
      `          ].map((stat) => (`,
      `            <div key={stat.label} className="flex flex-col items-center">`,
      `              <span className="text-lg font-bold">{stat.value}</span>`,
      `              <span className="text-xs text-muted-foreground">{stat.label}</span>`,
      `            </div>`,
      `          ))}`,
      `        </div>`,
      `        <Separator className="my-2" />`,
      `        <div className="flex gap-2">`,
      `          <Button size="sm">Follow</Button>`,
      `          <Button variant="outline" size="sm">Message</Button>`,
      `        </div>`,
      `      </div>`,
      `    </div>`,
    ].join('\n'),
  },
  // AUTO: cta-section pattern templates for React + shadcn/ui emission
  'cta-section': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <section className="flex flex-col items-center text-center py-12 px-4 ${gap}">`,
      `      <h2 className="text-3xl font-bold tracking-tight">Ready to Get Started?</h2>`,
      `      <p className="text-muted-foreground max-w-[640px]">Join thousands of developers building better applications faster with our platform.</p>`,
      `      <div className="flex gap-3">`,
      `        <Button size="lg">Start Free Trial</Button>`,
      `        <Button variant="outline" size="lg">Learn More</Button>`,
      `      </div>`,
      `    </section>`,
    ].join('\n'),
  },
  'cta-section:split': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <section className="grid grid-cols-1 lg:grid-cols-2 ${gap} items-center py-8">`,
      `      <div className="flex flex-col gap-4">`,
      `        <h2 className="text-3xl font-bold tracking-tight">Take Your Project to the Next Level</h2>`,
      `        <p className="text-muted-foreground">Our platform provides everything you need to build, deploy, and scale your applications with confidence.</p>`,
      `        <div className="flex gap-3">`,
      `          <Button size="lg">Get Started</Button>`,
      `          <Button variant="ghost" size="lg">See Examples</Button>`,
      `        </div>`,
      `      </div>`,
      `      <img src="/images/cta-illustration.svg" alt="Platform illustration" className="w-full rounded-lg" />`,
      `    </section>`,
    ].join('\n'),
  },
  'cta-section:banner': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <div className="flex items-center justify-between py-4 px-6 rounded-lg bg-primary/10">`,
      `      <p className="font-medium">Ready to upgrade? Get 20% off annual plans today.</p>`,
      `      <Button size="sm">Upgrade Now</Button>`,
      `    </div>`,
    ].join('\n'),
  },
  // AUTO: hero pattern templates for all presets
  'hero': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <section className="flex flex-col items-center text-center ${gap} py-16 px-6">`,
      `      <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Build Faster, Ship Smarter</h1>`,
      `      <p className="text-muted-foreground max-w-[640px]">The AI-first framework that turns your ideas into production-ready applications in minutes, not months.</p>`,
      `      <div className="flex gap-3">`,
      `        <Button size="lg">Get Started</Button>`,
      `        <Button variant="outline" size="lg">View Source</Button>`,
      `      </div>`,
      `    </section>`,
    ].join('\n'),
  },
  'hero:image-overlay': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/badge', ['Badge']],
    ]),
    body: (gap: string) => [
      `    <div className="relative w-full h-[400px] overflow-hidden rounded-lg">`,
      `      <img src="/images/hero-bg.jpg" alt="Hero background" className="absolute inset-0 w-full h-full object-cover" />`,
      `      <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />`,
      `      <div className="absolute top-0 left-0 right-0 flex justify-between p-4">`,
      `        <Button variant="ghost" size="sm">Back</Button>`,
      `        <Button variant="ghost" size="sm">Edit</Button>`,
      `      </div>`,
      `      <div className="absolute bottom-0 left-0 right-0 p-6 flex flex-col ${gap}">`,
      `        <div className="flex gap-2">`,
      `          <Badge variant="outline">Featured</Badge>`,
      `        </div>`,
      `        <h1 className="text-3xl font-bold text-white">Hero Title</h1>`,
      `        <p className="text-muted-foreground text-white/80">Supporting description for the hero section.</p>`,
      `      </div>`,
      `    </div>`,
    ].join('\n'),
  },
  'hero:image-overlay-compact': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/badge', ['Badge']],
      ['@/components/ui/avatar', ['Avatar', 'AvatarImage', 'AvatarFallback']],
    ]),
    body: (gap: string) => [
      `    <div className="relative w-full h-[300px] overflow-hidden rounded-lg">`,
      `      <img src="/images/cover.jpg" alt="Cover" className="absolute inset-0 w-full h-full object-cover" />`,
      `      <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />`,
      `      <div className="absolute top-0 right-0 p-4 flex gap-2">`,
      `        <Button variant="ghost" size="sm">Edit</Button>`,
      `        <Button variant="ghost" size="sm">Delete</Button>`,
      `      </div>`,
      `      <div className="absolute bottom-0 left-0 right-0 p-6 flex flex-col ${gap}">`,
      `        <h1 className="text-3xl font-bold text-white">Collection Title</h1>`,
      `        <div className="flex items-center gap-3">`,
      `          <Badge variant="outline">12 items</Badge>`,
      `          <div className="flex items-center gap-2">`,
      `            <Avatar className="h-6 w-6">`,
      `              <AvatarImage src="/images/avatar.jpg" />`,
      `              <AvatarFallback>U</AvatarFallback>`,
      `            </Avatar>`,
      `            <span className="text-sm text-white/80">Author Name</span>`,
      `          </div>`,
      `        </div>`,
      `      </div>`,
      `    </div>`,
    ].join('\n'),
  },
  'hero:split': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <section className="min-h-[100vh] relative flex items-center justify-center px-6 py-24">`,
      `      <div className="grid grid-cols-1 lg:grid-cols-2 ${gap} max-w-[1100px] w-full items-center">`,
      `        <div className="flex items-center justify-center">`,
      `          <img src="/images/logo.svg" alt="Logo" className="w-[280px]" />`,
      `        </div>`,
      `        <div className="flex flex-col gap-6 text-center lg:text-left">`,
      `          <h1 className="text-4xl font-bold tracking-tight">Your headline here</h1>`,
      `          <p className="text-muted-foreground max-w-[540px]">Supporting description text for the hero section.</p>`,
      `          <div className="flex gap-3 justify-center lg:justify-start">`,
      `            <Button size="lg">Get Started</Button>`,
      `            <Button variant="outline" size="lg">View Source</Button>`,
      `          </div>`,
      `        </div>`,
      `      </div>`,
      `    </section>`,
    ].join('\n'),
  },
  'hero:empty-state': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <div className="flex flex-col items-center text-center ${gap} py-12 px-6">`,
      `      <div className="w-16 h-16 flex items-center justify-center rounded-full bg-muted/10">`,
      `        <span className="text-2xl text-muted-foreground">📦</span>`,
      `      </div>`,
      `      <h3 className="text-lg font-semibold">No items yet</h3>`,
      `      <p className="text-muted-foreground max-w-[480px]">Get started by creating your first item or importing existing data.</p>`,
      `      <Button>Create First Item</Button>`,
      `    </div>`,
    ].join('\n'),
  },
  'hero:brand': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
      ['@/components/ui/badge', ['Badge']],
    ]),
    body: (gap: string) => [
      `    <section className="flex flex-col items-center text-center ${gap} py-24 px-6 min-h-[100vh] justify-center relative">`,
      `      <Badge variant="outline">Now in Beta</Badge>`,
      `      <h1 className="text-5xl font-bold tracking-tight bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">Build stunning apps in minutes</h1>`,
      `      <p className="text-lg text-muted-foreground max-w-[640px]">The AI-first web framework that transforms your ideas into production-ready applications.</p>`,
      `      <div className="flex gap-3">`,
      `        <Button size="lg">Get Started</Button>`,
      `        <Button variant="outline" size="lg">View Source</Button>`,
      `      </div>`,
      `    </section>`,
    ].join('\n'),
  },
  'hero:vision': {
    imports: new Map([
      ['@/components/ui/button', ['Button']],
    ]),
    body: (gap: string) => [
      `    <section className="flex flex-col items-center text-center ${gap} py-24 px-6 min-h-[100vh] justify-center relative">`,
      `      <h1 className="text-5xl font-bold tracking-tight bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">Frameworks were built for humans. Decantr is built for AI.</h1>`,
      `      <p className="text-lg text-muted-foreground max-w-[640px] leading-relaxed">The AI-native web framework. Registry-driven generation, signal reactivity, and 100+ components — all designed for LLMs to generate, read, and maintain.</p>`,
      `      <div className="flex gap-3">`,
      `        <Button size="lg">npx decantr init</Button>`,
      `        <Button variant="outline" size="lg">View Showcase</Button>`,
      `      </div>`,
      `    </section>`,
    ].join('\n'),
  },
  'kpi-grid': {
    imports: new Map([
      ['@/components/ui/card', ['Card', 'CardContent', 'CardHeader', 'CardTitle']],
      ['@/components/ui/badge', ['Badge']],
    ]),
    body: (gap: string) => [
      `    <div className="grid grid-cols-2 lg:grid-cols-4 ${gap} p-4">`,
      `      {[`,
      `        { label: "Total Revenue", value: "$45,231", change: "+20.1%", trend: "up" },`,
      `        { label: "Subscriptions", value: "2,350", change: "+180", trend: "up" },`,
      `        { label: "Active Now", value: "573", change: "+19", trend: "up" },`,
      `        { label: "Bounce Rate", value: "24.5%", change: "-4.3%", trend: "down" },`,
      `      ].map((kpi) => (`,
      `        <Card key={kpi.label}>`,
      `          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">`,
      `            <CardTitle className="text-sm font-medium">{kpi.label}</CardTitle>`,
      `          </CardHeader>`,
      `          <CardContent>`,
      `            <p className="text-2xl font-bold">{kpi.value}</p>`,
      `            <Badge variant={kpi.trend === "up" ? "default" : "secondary"}>`,
      `              {kpi.change}`,
      `            </Badge>`,
      `          </CardContent>`,
      `        </Card>`,
      `      ))}`,
      `    </div>`,
    ].join('\n'),
  },
};

/** Resolve the pattern-specific shadcn template if one exists */
export function resolvePatternTemplate(patternId: string): PatternShadcnTemplate | null {
  return PATTERN_TEMPLATE_MAP[patternId] || null;
}

/** Resolve the shadcn import for a Decantr component name */
export function resolveShadcnComponent(decantrComponent: string): ShadcnMapping | null {
  return COMPONENT_MAP[decantrComponent] || null;
}

/** Collect all shadcn imports needed for a set of Decantr component names */
export function collectShadcnImports(components: string[]): Map<string, string[]> {
  const imports = new Map<string, string[]>();
  for (const comp of components) {
    const mapping = COMPONENT_MAP[comp];
    if (mapping) {
      const existing = imports.get(mapping.importPath) || [];
      imports.set(mapping.importPath, [...new Set([...existing, ...mapping.imports])]);
    }
  }
  return imports;
}
