// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/blocks' {
  /**
   * Hero content block.
   */
  export function Hero(props?: Record<string, any>): HTMLElement;

  /**
   * Features content block.
   */
  export function Features(props?: Record<string, any>): HTMLElement;

  /**
   * Pricing content block.
   */
  export function Pricing(props?: Record<string, any>): HTMLElement;

  /**
   * Testimonials content block.
   */
  export function Testimonials(props?: Record<string, any>): HTMLElement;

  /**
   * CTA content block.
   */
  export function CTA(props?: Record<string, any>): HTMLElement;

  /**
   * Footer content block.
   */
  export function Footer(props?: Record<string, any>): HTMLElement;

  /**
   * ProfileHero content block.
   */
  export function ProfileHero(props?: Record<string, any>): HTMLElement;

  /**
   * ExpertiseGrid content block.
   */
  export function ExpertiseGrid(props?: Record<string, any>): HTMLElement;

  /**
   * StatsRow content block.
   */
  export function StatsRow(props?: Record<string, any>): HTMLElement;

  /**
   * IdentityGrid content block.
   */
  export function IdentityGrid(props?: Record<string, any>): HTMLElement;

  /**
   * SkillCategories content block.
   */
  export function SkillCategories(props?: Record<string, any>): HTMLElement;

  /**
   * CertificationRow content block.
   */
  export function CertificationRow(props?: Record<string, any>): HTMLElement;

  /**
   * Timeline content block.
   */
  export function Timeline(props?: Record<string, any>): HTMLElement;

  /**
   * ProjectGrid content block.
   */
  export function ProjectGrid(props?: Record<string, any>): HTMLElement;

  /**
   * TechGrid content block.
   */
  export function TechGrid(props?: Record<string, any>): HTMLElement;

  /**
   * HobbyGrid content block.
   */
  export function HobbyGrid(props?: Record<string, any>): HTMLElement;

  /**
   * PhotoGallery content block.
   */
  export function PhotoGallery(props?: Record<string, any>): HTMLElement;

  /**
   * ContactSplit content block.
   */
  export function ContactSplit(props?: Record<string, any>): HTMLElement;

  /**
   * SocialSidebar content block.
   */
  export function SocialSidebar(props?: Record<string, any>): HTMLElement;

}
