// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/chart' {
  interface ChartSpec {
    /** Chart type. Default: 'line'. */
    type?: 'line' | 'bar' | 'area' | 'pie';
    /** Data array or reactive signal getter. */
    data?: any[] | (() => any[]);
    /** X-axis field name. Default: 'x'. */
    x?: string;
    /** Y-axis field name(s). Default: 'y'. */
    y?: string | string[];
    /** Chart title. */
    title?: string;
    /** Show tooltip. Default: true. */
    tooltip?: boolean | ((info: { label: string; value: string; element: Element }) => Node);
    /** Show legend. Default: true. */
    legend?: boolean;
    /** Show grid lines. Default: true. */
    grid?: boolean;
    /** Stack series. Default: false. */
    stacked?: boolean;
    /** Animate transitions. Default: true. */
    animate?: boolean;
    /** Render mode. Default: 'auto'. */
    renderer?: 'auto' | 'svg' | 'canvas';
    /** Chart height CSS value. Default: '300px'. */
    height?: string;
    /** Donut mode for pie charts. Default: true. */
    donut?: boolean;
    /** Show accessible data table fallback. Default: true. */
    tableAlt?: boolean;
    /** CSS class for the container. */
    class?: string;
    /** Accessible label. */
    'aria-label'?: string;
    [key: string]: any;
  }

  /**
   * Validate and fill defaults for a chart spec.
   */
  export function chartSpec(overrides?: Partial<ChartSpec>): ChartSpec;

  /**
   * Create a chart DOM element from a declarative spec.
   */
  export function Chart(spec: ChartSpec): HTMLElement;

  interface SparklineSpec {
    /** Data array or reactive signal getter. */
    data: number[] | (() => number[]);
    /** Height in pixels. Default: '32'. */
    height?: string;
    /** Width in pixels. Default: '120'. */
    width?: string;
    /** CSS class. */
    class?: string;
    /** Accessible label. */
    'aria-label'?: string;
    [key: string]: any;
  }

  /**
   * Create an inline sparkline element.
   */
  export function Sparkline(spec: SparklineSpec): HTMLElement;

  /**
   * Get the CSS color for a chart series index.
   */
  export function chartColor(index: number): string;

  /**
   * Number of colors in the chart palette.
   */
  export const PALETTE_SIZE: number;
}
