// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/components' {
  // ── Component Props Base ──
  interface BaseProps {
    class?: string;
    style?: string | Record<string, string>;
    id?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
    [key: string]: any;
  }

  /**
   * Button component.
   */
  export function Button(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Spinner component.
   */
  export function Spinner(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Input component.
   */
  export function Input(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Textarea component.
   */
  export function Textarea(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Checkbox component.
   */
  export function Checkbox(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Switch component.
   */
  export function Switch(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Select component.
   */
  export function Select(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Card component.
   */
  export function Card(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Badge component.
   */
  export function Badge(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Modal component.
   */
  export function Modal(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Tabs component.
   */
  export function Tabs(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Accordion component.
   */
  export function Accordion(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Separator component.
   */
  export function Separator(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Breadcrumb component.
   */
  export function Breadcrumb(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Table component.
   */
  export function Table(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Avatar component.
   */
  export function Avatar(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Progress component.
   */
  export function Progress(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Skeleton component.
   */
  export function Skeleton(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Tooltip component.
   */
  export function Tooltip(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Alert component.
   */
  export function Alert(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Chip component.
   */
  export function Chip(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dropdown component.
   */
  export function Dropdown(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Drawer component.
   */
  export function Drawer(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Pagination component.
   */
  export function Pagination(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * RadioGroup component.
   */
  export function RadioGroup(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Popover component.
   */
  export function Popover(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Combobox component.
   */
  export function Combobox(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Slider component.
   */
  export function Slider(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Toggle component.
   */
  export function Toggle(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * ToggleGroup component.
   */
  export function ToggleGroup(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Title component.
   */
  export function Title(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Text component.
   */
  export function Text(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Paragraph component.
   */
  export function Paragraph(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Link component.
   */
  export function Link(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Blockquote component.
   */
  export function Blockquote(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Kbd component.
   */
  export function Kbd(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Space component.
   */
  export function Space(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * AspectRatio component.
   */
  export function AspectRatio(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Resizable component.
   */
  export function Resizable(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * ScrollArea component.
   */
  export function ScrollArea(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Collapsible component.
   */
  export function Collapsible(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Splitter component.
   */
  export function Splitter(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Menu component.
   */
  export function Menu(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Steps component.
   */
  export function Steps(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Segmented component.
   */
  export function Segmented(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Affix component.
   */
  export function Affix(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * ContextMenu component.
   */
  export function ContextMenu(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * NavigationMenu component.
   */
  export function NavigationMenu(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * BackTop component.
   */
  export function BackTop(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * InputGroup component.
   */
  export function InputGroup(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * CompactGroup component.
   */
  export function CompactGroup(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * InputNumber component.
   */
  export function InputNumber(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * InputOTP component.
   */
  export function InputOTP(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Rate component.
   */
  export function Rate(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * ColorPicker component.
   */
  export function ColorPicker(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * DatePicker component.
   */
  export function DatePicker(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * TimePicker component.
   */
  export function TimePicker(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Upload component.
   */
  export function Upload(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Transfer component.
   */
  export function Transfer(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Cascader component.
   */
  export function Cascader(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Mentions component.
   */
  export function Mentions(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Label component.
   */
  export function Label(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Form component.
   */
  export function Form(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Field component.
   */
  export function Field(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * DateRangePicker component.
   */
  export function DateRangePicker(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * TimeRangePicker component.
   */
  export function TimeRangePicker(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * RangeSlider component.
   */
  export function RangeSlider(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * TreeSelect component.
   */
  export function TreeSelect(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * DataTable component.
   */
  export function DataTable(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * AvatarGroup component.
   */
  export function AvatarGroup(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Tag component.
   */
  export function Tag(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * List component.
   */
  export function List(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Tree component.
   */
  export function Tree(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Descriptions component.
   */
  export function Descriptions(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Statistic component.
   */
  export function Statistic(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Calendar component.
   */
  export function Calendar(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Carousel component.
   */
  export function Carousel(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Empty component.
   */
  export function Empty(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Image component.
   */
  export function Image(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Timeline component.
   */
  export function Timeline(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * HoverCard component.
   */
  export function HoverCard(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * AlertDialog component.
   */
  export function AlertDialog(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Sheet component.
   */
  export function Sheet(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Result component.
   */
  export function Result(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Popconfirm component.
   */
  export function Popconfirm(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Command component.
   */
  export function Command(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * FloatButton component.
   */
  export function FloatButton(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Tour component.
   */
  export function Tour(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Watermark component.
   */
  export function Watermark(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * VisuallyHidden component.
   */
  export function VisuallyHidden(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Button variant class generator.
   */
  export function buttonVariants(props?: Record<string, any>): string;

  /**
   * Create an icon element by name.
   */
  export function icon(name: string, props?: { size?: number | string; class?: string; [key: string]: any }): SVGElement;

  /**
   * Register a custom icon.
   */
  export function registerIcon(name: string, pathData: string): void;

  /**
   * Register multiple icons at once.
   */
  export function registerIcons(iconMap: Record<string, string>): void;

  /**
   * Show a toast notification. Returns a dismiss function.
   */
  export function toast(props: {
    title?: string;
    description?: string;
    variant?: 'default' | 'success' | 'error' | 'warning' | 'info';
    duration?: number;
    action?: { label: string; onClick: () => void };
    [key: string]: any;
  }): () => void;

  /**
   * Clear all active toasts.
   */
  export function resetToasts(): void;

  /**
   * Show a notification. Returns a dismiss function.
   */
  export function notification(props: {
    title?: string;
    description?: string;
    variant?: string;
    duration?: number;
    placement?: string;
    [key: string]: any;
  }): () => void;

  /**
   * Clear all active notifications.
   */
  export function resetNotifications(): void;

  /**
   * Show a message. Returns a dismiss function.
   */
  export function message(props: {
    content?: string;
    type?: 'info' | 'success' | 'warning' | 'error' | 'loading';
    duration?: number;
    [key: string]: any;
  }): () => void;

  /**
   * Clear all active messages.
   */
  export function resetMessages(): void;

  /**
   * Create a reactive form field binding helper.
   */
  export function createFormField(form: any, fieldName: string): Record<string, any>;
}
