// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/core' {
  /**
   * Create a DOM element via hyperscript.
   */
  export function h(tag: string, props?: Record<string, any> | null, ...children: any[]): HTMLElement;

  /**
   * Create a reactive text node from a getter function.
   */
  export function text(getter: () => string | number): Text;

  /**
   * Conditional rendering — renders trueBranch or falseBranch based on predicate.
   */
  export function cond(
    condition: () => boolean,
    thenFn: () => Node,
    elseFn?: () => Node
  ): HTMLElement;

  /**
   * Keyed list rendering with efficient reconciliation.
   */
  export function list(
    itemsGetter: () => any[],
    keyFn: (item: any, index: number) => string | number,
    renderFn: (item: any, index: number) => Node
  ): HTMLElement;

  /**
   * Mount a component to a DOM element.
   */
  export function mount(root: HTMLElement, component: () => Node): void;

  /**
   * Unmount a previously mounted component tree.
   */
  export function unmount(root: HTMLElement): void;

  /**
   * Register a callback to run after mount.
   */
  export function onMount(fn: () => void | (() => void)): void;

  /**
   * Register a callback to run on teardown.
   */
  export function onDestroy(fn: () => void): void;

  /**
   * Error catching component. Wraps children and catches render/effect errors.
   */
  export function ErrorBoundary(
    props: { fallback: (error: Error, retry: () => void) => Node },
    ...children: Node[]
  ): HTMLElement;

  /**
   * Render children into a different DOM target (e.g., document.body).
   */
  export function Portal(
    props?: { target?: string | HTMLElement },
    ...children: Node[]
  ): Comment;

  /**
   * Async boundary. Shows fallback while createQuery() calls in children are loading.
   */
  export function Suspense(
    props: { fallback: () => Node },
    ...children: Node[]
  ): HTMLElement;

  /**
   * Enter/exit animation wrapper for conditional content.
   */
  export function Transition(
    props: { enter?: string; exit?: string; duration?: number },
    child: () => Node | null
  ): HTMLElement;

  /**
   * Extract ref from props and pass it as second argument to a component.
   */
  export function forwardRef<P extends Record<string, any>>(
    component: (props: P, ref: ((el: HTMLElement) => void) | undefined, ...children: Node[]) => Node
  ): (props: P & { ref?: (el: HTMLElement) => void }, ...children: Node[]) => Node;
}
