// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/css' {
  /**
   * Compose atomic CSS class names. Injects styles on first use.
   */
  export function css(...classes: string[]): string;

  /**
   * Define a custom atomic CSS class.
   */
  export function define(name: string, declaration: string): void;

  /**
   * Get all generated CSS as a string.
   */
  export function extractCSS(): string;

  /**
   * Clear all injected styles.
   */
  export function reset(): void;

  /**
   * Sanitize a string for safe use in HTML attributes.
   */
  export function sanitize(str: string): string;

  // ── Style API (visual personality) ──

  /**
   * Set the active visual style.
   */
  export function setStyle(id: string): void;

  /**
   * Get the active style ID.
   */
  export function getStyle(): string;

  /**
   * Get list of registered styles.
   */
  export function getStyleList(): Array<{ id: string; name: string }>;

  interface StyleDefinition {
    id: string;
    name: string;
    seed: Record<string, string>;
    personality: Record<string, string>;
    typography?: Record<string, string>;
    overrides?: { light?: Record<string, string>; dark?: Record<string, string> };
    components?: string;
  }

  /**
   * Register a custom style.
   */
  export function registerStyle(style: StyleDefinition): void;

  // ── Mode API (light/dark) ──

  /**
   * Set the color mode.
   */
  export function setMode(mode: 'light' | 'dark' | 'auto'): void;

  /**
   * Get the current mode setting.
   */
  export function getMode(): 'light' | 'dark' | 'auto';

  /**
   * Get the resolved mode (always 'light' or 'dark', never 'auto').
   */
  export function getResolvedMode(): 'light' | 'dark';

  /**
   * Register callback for resolved mode changes. Returns unsubscribe function.
   */
  export function onModeChange(fn: (mode: 'light' | 'dark') => void): () => void;

  // ── Legacy / backward compat ──

  /**
   * Combines setStyle + setMode. Accepts legacy theme IDs.
   */
  export function setTheme(id: string, mode?: string): void;

  /**
   * Get the current theme object (backward compat).
   */
  export function getTheme(): Record<string, any>;

  /**
   * Get theme metadata.
   */
  export function getThemeMeta(): Record<string, any>;

  /**
   * Get list of available themes.
   */
  export function getThemeList(): Array<Record<string, any>>;

  /**
   * Register a theme (backward compat wrapper for registerStyle).
   */
  export function registerTheme(theme: Record<string, any>): void;

  /**
   * Get complete CSS for the active style's theme layer.
   */
  export function getActiveCSS(): string;

  /**
   * Reset to defaults (clean + light).
   */
  export function resetStyles(): void;

  /**
   * Enable/disable JS animations globally.
   */
  export function setAnimations(enabled: boolean): void;

  /**
   * Get a signal getter for the current animations-enabled state.
   */
  export function getAnimations(): () => boolean;

  /** Responsive breakpoint widths. */
  export const BREAKPOINTS: Record<string, number>;

  /** Container query widths. */
  export const CQ_WIDTHS: number[];
}
