// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/data' {
  // ─── Query ────────────────────────────────────────────────

  interface QueryOptions<T> {
    staleTime?: number;
    cacheTime?: number;
    retry?: number;
    refetchInterval?: number;
    refetchOnWindowFocus?: boolean;
    enabled?: () => boolean;
    select?: (data: any) => T;
    initialData?: T;
    placeholderData?: T;
  }

  interface QueryResult<T> {
    data: () => T | undefined;
    status: () => 'idle' | 'loading' | 'success' | 'error';
    error: () => Error | null;
    isLoading: () => boolean;
    isStale: () => boolean;
    isFetching: () => boolean;
    refetch: () => Promise<void>;
    setData: (value: T) => void;
  }

  export function createQuery<T>(
    key: string | (() => string),
    fetcher: (context: { key: string; signal: AbortSignal }) => Promise<T>,
    options?: QueryOptions<T>
  ): QueryResult<T>;

  interface InfiniteQueryOptions<T> extends QueryOptions<T> {
    getNextPageParam: (lastPage: T, allPages: T[]) => any | undefined;
  }

  interface InfiniteQueryResult<T> {
    pages: () => T[];
    allItems: () => any[];
    hasNextPage: () => boolean;
    fetchNextPage: () => Promise<void>;
    isFetchingNextPage: () => boolean;
    refetch: () => Promise<void>;
  }

  export function createInfiniteQuery<T>(
    key: string | (() => string),
    fetcher: (context: { key: string; pageParam: any; signal: AbortSignal }) => Promise<T>,
    options?: InfiniteQueryOptions<T>
  ): InfiniteQueryResult<T>;

  interface MutationOptions<TData, TVariables, TContext> {
    onMutate?: (variables: TVariables) => TContext | Promise<TContext>;
    onSuccess?: (data: TData, variables: TVariables, context: TContext) => void;
    onError?: (error: Error, variables: TVariables, context: TContext) => void;
    onSettled?: (data: TData | undefined, error: Error | null, variables: TVariables, context: TContext) => void;
  }

  interface MutationResult<TData, TVariables> {
    mutate: (variables: TVariables) => void;
    mutateAsync: (variables: TVariables) => Promise<TData>;
    isLoading: () => boolean;
    error: () => Error | null;
    data: () => TData | undefined;
    reset: () => void;
  }

  export function createMutation<TData = any, TVariables = any, TContext = any>(
    mutationFn: (variables: TVariables) => Promise<TData>,
    options?: MutationOptions<TData, TVariables, TContext>
  ): MutationResult<TData, TVariables>;

  interface QueryClient {
    invalidate: (keyPrefix: string) => void;
    prefetch: <T>(key: string, fetcher: (context: { key: string; signal: AbortSignal }) => Promise<T>) => Promise<void>;
    setCache: (key: string, data: any) => void;
    getCache: (key: string) => any | undefined;
    clear: () => void;
  }

  export const queryClient: QueryClient;

  // ─── Entity ───────────────────────────────────────────────

  interface EntityStore<T> {
    addMany: (entities: T[]) => void;
    upsert: (entity: T) => void;
    update: (id: any, partial: Partial<T>) => void;
    remove: (id: any) => void;
    clear: () => void;
    get: (id: any) => () => T | undefined;
    all: () => T[];
    count: () => number;
    filter: (predicate: (entity: T) => boolean) => () => T[];
    sorted: (comparator: (a: T, b: T) => number) => () => T[];
    paginated: (opts: { page: number; size: number }) => () => T[];
  }

  export function createEntityStore<T>(options: { getId: (entity: T) => any }): EntityStore<T>;

  // ─── URL State ────────────────────────────────────────────

  interface Parser<T> {
    parse: (value: string) => T;
    serialize: (value: T) => string;
  }

  interface URLSignalOptions<T> {
    defaultValue?: T;
    push?: boolean;
  }

  export function createURLSignal<T>(
    key: string,
    parser: Parser<T>,
    options?: URLSignalOptions<T>
  ): [() => T, (value: T) => void];

  export function createURLStore<T extends Record<string, any>>(
    schema: { [K in keyof T]: { parser: Parser<T[K]>; defaultValue: T[K] } }
  ): { [K in keyof T as `${string & K}`]: () => T[K] } & { [K in keyof T as `set${Capitalize<string & K>}`]: (value: T[K]) => void } & { values: () => T; reset: () => void };

  export const parsers: {
    string: Parser<string>;
    integer: Parser<number>;
    float: Parser<number>;
    boolean: Parser<boolean>;
    json: Parser<any>;
    date: Parser<Date>;
    enum: <T extends string>(values: T[]) => Parser<T>;
  };

  // ─── Realtime ─────────────────────────────────────────────

  interface WebSocketOptions {
    reconnectDelay?: number;
    maxRetries?: number;
    buffer?: boolean;
    parse?: (data: any) => any;
    protocols?: string[];
  }

  interface WebSocketResult {
    lastMessage: () => any;
    messages: () => any[];
    status: () => 'connecting' | 'open' | 'closed' | 'reconnecting';
    send: (data: any) => void;
    close: () => void;
    reconnect: () => void;
    on: (handler: (message: any) => void) => () => void;
  }

  export function createWebSocket(url: string, options?: WebSocketOptions): WebSocketResult;

  interface EventSourceOptions {
    events?: string[];
    withCredentials?: boolean;
  }

  interface EventSourceResult {
    lastEvent: () => { type: string; data: any } | null;
    status: () => 'connecting' | 'open' | 'closed';
    close: () => void;
    on: (eventType: string, handler: (data: any) => void) => () => void;
  }

  export function createEventSource(url: string, options?: EventSourceOptions): EventSourceResult;

  // ─── Persistence ──────────────────────────────────────────

  interface PersistedOptions {
    storage?: 'local' | 'session';
    serialize?: (value: any) => string;
    deserialize?: (value: string) => any;
  }

  export function createPersisted<T>(
    key: string,
    init: T,
    options?: PersistedOptions
  ): [() => T, (value: T | ((prev: T) => T)) => void];

  interface IndexedDBStore {
    get: <T>(key: string) => Promise<T | undefined>;
    set: (key: string, value: any) => Promise<void>;
    delete: (key: string) => Promise<void>;
    getAll: <T>() => Promise<T[]>;
    clear: () => Promise<void>;
  }

  export function createIndexedDB(dbName: string, storeName: string): IndexedDBStore;

  export function createCrossTab<T>(
    channel: string,
    signal: [() => T, (value: T) => void]
  ): () => void;

  interface OfflineQueueOptions {
    process: (item: any) => Promise<void>;
    persist?: boolean;
    key?: string;
    retryDelay?: number;
  }

  interface OfflineQueue {
    add: (item: any) => void;
    pending: () => any[];
    isOnline: () => boolean;
    flush: () => Promise<void>;
  }

  export function createOfflineQueue(options: OfflineQueueOptions): OfflineQueue;

  // ─── Worker ───────────────────────────────────────────────

  interface WorkerSignalResult {
    result: () => any;
    busy: () => boolean;
    error: () => Error | null;
    send: (data: any) => void;
    terminate: () => void;
  }

  export function createWorkerSignal(worker: Worker): WorkerSignalResult;

  interface WorkerQueryResult<T> {
    data: () => T | undefined;
    loading: () => boolean;
    error: () => Error | null;
    refetch: () => void;
  }

  export function createWorkerQuery<T>(
    worker: Worker,
    input: (() => any) | any
  ): WorkerQueryResult<T>;
}
