// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/form' {
  // ── Validator Types ──

  type SyncValidator = (value: any, allValues?: Record<string, any>) => string | null;
  type AsyncValidator = (value: any, allValues?: Record<string, any>) => Promise<string | null>;

  interface Validators {
    /** Value must be truthy (non-empty). */
    required(msg?: string): SyncValidator;
    /** String length must be >= n. */
    minLength(n: number, msg?: string): SyncValidator;
    /** String length must be <= n. */
    maxLength(n: number, msg?: string): SyncValidator;
    /** Numeric value must be >= n. */
    min(n: number, msg?: string): SyncValidator;
    /** Numeric value must be <= n. */
    max(n: number, msg?: string): SyncValidator;
    /** Value must match regex pattern. */
    pattern(regex: RegExp, msg?: string): SyncValidator;
    /** Must be a valid email address. */
    email(msg?: string): SyncValidator;
    /** Value must equal another field's current value. */
    match(fieldName: string, msg?: string): SyncValidator;
    /** Custom synchronous validator. */
    custom(fn: (value: any, allValues: Record<string, any>) => true | string, msg?: string): SyncValidator;
    /** Async validator (auto-debounced 300ms). */
    async(fn: (value: any, allValues: Record<string, any>) => Promise<true | string>, msg?: string): AsyncValidator;
  }

  export const validators: Validators;

  // ── Field Instance ──

  interface FieldInstance {
    readonly name: string;
    /** Signal getter for current value. */
    value: () => any;
    /** First error message or null. */
    error: () => string | null;
    /** All error messages. */
    errors: () => string[];
    /** Whether field has been blurred. */
    touched: () => boolean;
    /** Whether value differs from initial. */
    dirty: () => boolean;
    /** Whether field has no errors. */
    valid: () => boolean;
    /** Set a new value. */
    setValue: (value: any) => void;
    /** Mark as touched. */
    setTouched: () => void;
    /** Set an error manually. */
    setError: (msg: string) => void;
    /** Reset to initial value. */
    reset: (value?: any) => void;
    /** Run all validators. Returns true if valid. */
    validate: () => Promise<boolean>;
    /** Get binding props for Decantr form components. */
    bind: () => { value: () => any; onchange: (v: any) => void; onblur: () => void; error: () => string | null };
  }

  // ── Field Array Instance ──

  interface FieldArrayInstance {
    /** Signal getter for array of items. */
    items: () => any[];
    /** Reactive item count. */
    length: () => number;
    /** Append a value to the end. */
    append: (value: any) => void;
    /** Prepend a value to the beginning. */
    prepend: (value: any) => void;
    /** Remove item at index. */
    remove: (index: number) => void;
    /** Move item from one index to another. */
    move: (from: number, to: number) => void;
    /** Swap two items by index. */
    swap: (a: number, b: number) => void;
    /** Replace item at index. */
    replace: (index: number, value: any) => void;
  }

  // ── Form Instance ──

  interface FieldConfig {
    /** Initial value. */
    value?: any;
    /** Array of validator functions. */
    validators?: Array<SyncValidator | AsyncValidator>;
    /** Transform function applied on setValue. */
    transform?: (raw: any) => any;
  }

  interface FormConfig {
    /** Field definitions. */
    fields: Record<string, FieldConfig>;
    /** Submit handler. */
    onSubmit?: (values: Record<string, any>, form: FormInstance) => void | Promise<void>;
    /** Cross-field validation returning `{ fieldName: string[] }`. */
    validate?: (values: Record<string, any>) => Record<string, string[]> | void;
    /** When to trigger validation. Default: 'onBlur'. */
    validateOn?: 'onChange' | 'onBlur' | 'onSubmit';
  }

  interface FormInstance {
    /** Get or create a field by name. */
    field: (name: string) => FieldInstance;
    /** Proxy for field access via dot notation (form.fields.email). */
    fields: Record<string, FieldInstance>;
    /** Signal getter for all current values. */
    values: () => Record<string, any>;
    /** Signal getter for all errors `{ fieldName: string[] }`. */
    errors: () => Record<string, string[]>;
    /** Signal getter for overall form validity. */
    isValid: () => boolean;
    /** Signal getter for whether any field is dirty. */
    isDirty: () => boolean;
    /** Signal getter for submitting state. */
    isSubmitting: () => boolean;
    /** Signal getter for submitted state. */
    isSubmitted: () => boolean;
    /** Signal getter for submit count. */
    submitCount: () => number;
    /** Submit the form. */
    submit: () => Promise<void>;
    /** Reset all fields. */
    reset: (values?: Record<string, any>) => void;
    /** Set multiple field values at once. */
    setValues: (partial: Record<string, any>) => void;
    /** Set errors on multiple fields. */
    setErrors: (errors: Record<string, string | string[]>) => void;
    /** Run all validators. Returns true if valid. */
    validate: () => Promise<boolean>;
    /** Get or create a field array. */
    fieldArray: (name: string) => FieldArrayInstance;
    /** Watch a specific field for value changes. Returns unsubscribe. */
    watch: (fieldName: string, callback: (value: any, prevValue: any) => void) => () => void;
    /** Watch all fields for any change. Returns unsubscribe. */
    watchAll: (callback: (values: Record<string, any>) => void) => () => void;
  }

  /**
   * Create a reactive form instance.
   */
  export function createForm(config: FormConfig): FormInstance;

  interface UseFormFieldResult {
    value: () => any;
    setValue: (value: any) => void;
    error: () => string | null;
    errors: () => string[];
    touched: () => boolean;
    dirty: () => boolean;
    valid: () => boolean;
    onBlur: () => void;
    bind: () => { value: () => any; onchange: (v: any) => void; onblur: () => void; error: () => string | null };
  }

  /**
   * Hook for binding a form field to a custom component.
   */
  export function useFormField(form: FormInstance, fieldName: string): UseFormFieldResult;
}
