// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/i18n' {
  /**
   * Configuration for creating an i18n instance.
   */
  export interface I18nConfig {
    /** Initial active locale (e.g. 'en', 'fr', 'ar'). */
    locale: string;
    /** Messages keyed by locale. Each locale maps keys to strings or nested objects. */
    messages: Record<string, Record<string, any>>;
    /** Fallback locale used when a key is missing in the active locale. */
    fallbackLocale?: string;
  }

  /**
   * An i18n instance returned by createI18n().
   */
  export interface I18nInstance {
    /**
     * Translate a key with optional interpolation and pluralization.
     *
     * - Dot notation: `t('nav.home')` resolves nested objects.
     * - Interpolation: `t('hello', { name: 'World' })` replaces `{name}`.
     * - Pluralization: `t('items', { count: 3 })` appends `_one`/`_other` suffix
     *   via `Intl.PluralRules`.
     * - Fallback chain: current locale -> fallback locale -> raw key.
     */
    t: (key: string, params?: Record<string, any>) => string;

    /** Signal getter for the current locale. */
    locale: () => string;

    /** Set the active locale. Reactively updates all `t()` consumers. */
    setLocale: (locale: string) => void;

    /** Set the document direction attribute ('ltr' or 'rtl'). */
    setDirection: (dir: 'ltr' | 'rtl') => void;

    /** Merge additional messages into a locale at runtime. */
    addMessages: (locale: string, messages: Record<string, any>) => void;
  }

  /**
   * Create a reactive i18n instance.
   *
   * The returned `t()` function is reactive — it reads the internal locale
   * signal, so any `createEffect` or `createMemo` that calls `t()` will
   * re-run when the locale changes via `setLocale()`.
   */
  export function createI18n(config: I18nConfig): I18nInstance;
}
