// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/icons' {
  /**
   * Get SVG inner content for an icon by name.
   */
  export function getIconPath(name: string): string | null;

  /**
   * Register a custom icon (or override an existing one).
   */
  export function registerIcon(name: string, pathData: string): void;

  /**
   * Register multiple icons at once.
   */
  export function registerIcons(iconMap: Record<string, string>): void;

  /**
   * Check if an icon is available.
   */
  export function hasIcon(name: string): boolean;

  /**
   * Get all currently available icon names.
   */
  export function getIconNames(): string[];
}
