// Auto-generated by tools/dts-gen.js — do not edit manually
// Master declaration file — re-exports all Decantr modules.

/// <reference path="./core.d.ts" />
/// <reference path="./state.d.ts" />
/// <reference path="./router.d.ts" />
/// <reference path="./css.d.ts" />
/// <reference path="./tags.d.ts" />
/// <reference path="./components.d.ts" />
/// <reference path="./form.d.ts" />
/// <reference path="./icons.d.ts" />
/// <reference path="./chart.d.ts" />
/// <reference path="./blocks.d.ts" />
/// <reference path="./kit-dashboard.d.ts" />
/// <reference path="./kit-auth.d.ts" />
/// <reference path="./kit-content.d.ts" />
/// <reference path="./test.d.ts" />
