// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/kit/auth' {
  /**
   * Auth kit: LoginForm component.
   */
  export function LoginForm(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Auth kit: RegisterForm component.
   */
  export function RegisterForm(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Auth kit: ForgotPasswordForm component.
   */
  export function ForgotPasswordForm(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Auth kit: AuthLayout component.
   */
  export function AuthLayout(props?: Record<string, any>, ...children: any[]): HTMLElement;

}
