// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/kit/dashboard' {
  /**
   * Dashboard kit: Sidebar component.
   * Props accept signal getters or static values.
   */
  export function Sidebar(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dashboard kit: DashboardHeader component.
   * Props accept signal getters or static values.
   */
  export function DashboardHeader(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dashboard kit: StatsGrid component.
   * Props accept signal getters or static values.
   */
  export function StatsGrid(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dashboard kit: KPICard component.
   * Props accept signal getters or static values.
   */
  export function KPICard(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dashboard kit: ActivityFeed component.
   * Props accept signal getters or static values.
   */
  export function ActivityFeed(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dashboard kit: DataTable component.
   * Props accept signal getters or static values.
   */
  export function DataTable(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Dashboard kit: ChartPlaceholder component.
   * Props accept signal getters or static values.
   */
  export function ChartPlaceholder(props?: Record<string, any>, ...children: any[]): HTMLElement;

}
