// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/kit/content' {
  /**
   * Content kit: ArticleLayout component.
   */
  export function ArticleLayout(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Content kit: AuthorCard component.
   */
  export function AuthorCard(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Content kit: TableOfContents component.
   */
  export function TableOfContents(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Content kit: PostList component.
   */
  export function PostList(props?: Record<string, any>, ...children: any[]): HTMLElement;

  /**
   * Content kit: CategoryNav component.
   */
  export function CategoryNav(props?: Record<string, any>, ...children: any[]): HTMLElement;

}
