// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/router' {
  interface RouteConfig {
    /** Route path pattern (e.g., '/users/:id'). */
    path: string;
    /** Component function to render. */
    component?: (params?: Record<string, string>) => Node;
    /** Nested child routes. */
    children?: RouteConfig[];
    /** Optional named route. */
    name?: string;
  }

  interface RouterConfig {
    /** Routing strategy. Default: 'hash'. */
    mode?: 'hash' | 'history';
    /** Route definitions. */
    routes: RouteConfig[];
    /** Enable View Transitions API for route changes. */
    transitions?: boolean;
    /** Scroll behavior on navigation. Default: 'top'. */
    scrollBehavior?: 'top' | 'restore' | false;
    /** Navigation guard — return false to cancel, string to redirect. */
    beforeEach?: (to: RouteMatch, from: RouteMatch) => void | false | string;
    /** Post-navigation hook. */
    afterEach?: (to: RouteMatch, from: RouteMatch) => void;
  }

  interface RouteMatch {
    path: string;
    params: Record<string, string>;
    query: Record<string, string>;
    component: Function | null;
    components: Function[];
    matched: boolean;
    name?: string;
  }

  interface Router {
    /** Programmatic navigation. */
    navigate: (to: string | { name: string; params?: Record<string, string> }, opts?: { replace?: boolean }) => void;
    /** Create a route outlet element that renders the matched component. */
    outlet: (depth?: number) => HTMLElement;
    /** Signal getter for the current route match. */
    current: () => RouteMatch;
    /** Signal getter for the current path string. */
    path: () => string;
    /** Destroy the router and remove event listeners. */
    destroy: () => void;
  }

  /**
   * Create a router instance.
   */
  export function createRouter(config: RouterConfig): Router;

  /**
   * Navigate programmatically. Delegates to the active router.
   */
  export function navigate(
    to: string | { name: string; params?: Record<string, string> },
    opts?: { replace?: boolean }
  ): void;

  /**
   * Create a router-aware anchor element with active link detection.
   */
  export function link(
    props: { href: string; activeClass?: string; exact?: boolean; class?: string; [key: string]: any },
    ...children: any[]
  ): HTMLAnchorElement;

  /**
   * Get the current route signal from the active router.
   */
  export function useRoute(): () => RouteMatch;

  /**
   * Reactive search params. Returns [getter, setter] tuple.
   */
  export function useSearchParams(): [() => URLSearchParams, (params: Record<string, string> | URLSearchParams) => void];
}
