// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/ssr' {
  /**
   * Render a component to an HTML string for server-side rendering.
   * The component is executed in an SSR context where signals are
   * evaluated once without reactive tracking, and DOM APIs are not used.
   * Each element includes a `data-d-id` attribute for hydration.
   */
  export function renderToString(component: () => any): string;

  /**
   * Render a component to a ReadableStream of HTML chunks.
   * Same SSR semantics as renderToString but yields chunks incrementally.
   * Uses the Web Streams API (Node.js 18+).
   */
  export function renderToStream(component: () => any): ReadableStream<string>;

  /**
   * Hydrate an existing DOM tree produced by renderToString/renderToStream.
   * Walks the existing DOM and attaches event listeners, signal subscriptions,
   * and reactive effects without recreating DOM nodes.
   */
  export function hydrate(root: HTMLElement, component: () => any): void;

  /**
   * Install the reactive runtime for hydration.
   * Must be called once on the client before calling hydrate().
   */
  export function installHydrationRuntime(
    stateMod: { createEffect: (fn: () => any) => () => void },
    lifecycleMod: {
      pushScope: () => void;
      popScope: () => (() => void)[];
      drainMountQueue: () => (() => void)[];
      runDestroyFns: (fns: (() => void)[]) => void;
    }
  ): void;

  /**
   * Check if currently executing in SSR mode.
   */
  export function isSSR(): boolean;

  /**
   * Get the SSR-safe h() function (returns null outside SSR).
   */
  export function getSSRH(): ((tag: string, props?: Record<string, any> | null, ...children: any[]) => any) | null;

  /**
   * Get the SSR-safe text() function (returns null outside SSR).
   */
  export function getSSRText(): ((getter: () => any) => any) | null;

  /**
   * Get the SSR-safe cond() function (returns null outside SSR).
   */
  export function getSSRCond(): ((condition: () => boolean, thenFn: () => any, elseFn?: () => any) => any) | null;

  /**
   * Get the SSR-safe list() function (returns null outside SSR).
   */
  export function getSSRList(): ((items: () => any[], keyFn: (item: any, i: number) => any, renderFn: (item: any, i: number) => any) => any) | null;

  /**
   * Get the SSR-safe css() function (returns null outside SSR).
   */
  export function getSSRCss(): ((...classes: string[]) => string) | null;

  /**
   * Create an SSR-compatible component that works in both server and client contexts.
   */
  export function ssrComponent(
    factory: (
      h: (tag: string, props?: Record<string, any> | null, ...children: any[]) => any,
      text: (getter: () => any) => any,
      cond: (condition: () => boolean, thenFn: () => any, elseFn?: () => any) => any,
      list: (items: () => any[], keyFn: (item: any, i: number) => any, renderFn: (item: any, i: number) => any) => any,
      css: (...classes: string[]) => string
    ) => (...args: any[]) => any
  ): (...args: any[]) => any;

  /** SSR h() — creates VNodes instead of DOM elements */
  export function ssrH(tag: string, props?: Record<string, any> | null, ...children: any[]): any;

  /** SSR text() — evaluates getter once, returns TextVNode */
  export function ssrText(getter: () => any): any;

  /** SSR cond() — evaluates predicate once, returns active branch */
  export function ssrCond(condition: () => boolean, thenFn: () => any, elseFn?: () => any): any;

  /** SSR list() — evaluates items once, maps through renderFn */
  export function ssrList(items: () => any[], keyFn: (item: any, i: number) => any, renderFn: (item: any, i: number) => any): any;

  /** SSR css() — resolves atom classes without DOM injection */
  export function ssrCss(...classes: string[]): string;

  /** SSR onMount — no-op during SSR */
  export function ssrOnMount(fn: () => void): void;

  /** SSR onDestroy — no-op during SSR */
  export function ssrOnDestroy(fn: () => void): void;
}
