// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/state' {
  /**
   * Create a reactive signal primitive.
   * Returns a [getter, setter] tuple.
   */
  export function createSignal<T>(initialValue: T): [() => T, (value: T | ((prev: T) => T)) => void];

  /**
   * Create a reactive effect that auto-tracks signal dependencies.
   * Returns a dispose function.
   */
  export function createEffect(fn: () => void | (() => void)): () => void;

  /**
   * Create a cached derived computation.
   */
  export function createMemo<T>(fn: () => T): () => T;

  /**
   * Create a reactive proxy store with per-property tracking.
   */
  export function createStore<T extends object>(initialValue: T): T;

  /**
   * Batch multiple signal updates into one effect flush.
   */
  export function batch(fn: () => void): void;

  /**
   * Execute a function without subscribing to signal reads.
   */
  export function untrack<T>(fn: () => T): T;

  /**
   * Read a signal getter without subscribing. Alias for untrack().
   */
  export function peek<T>(getter: () => T): T;

  /**
   * Persistent signal backed by localStorage.
   */
  export function useLocalStorage<T>(key: string, initialValue: T): [() => T, (value: T | ((prev: T) => T)) => void];

  interface Resource<T> {
    /** Signal getter for the resolved data. */
    data: () => T | undefined;
    /** Signal getter for loading state. */
    loading: () => boolean;
    /** Signal getter for error state. */
    error: () => Error | null;
    /** Re-run the fetcher. */
    refetch: () => Promise<void>;
    /** Manually set the data value. */
    mutate: (value: T) => void;
  }

  /**
   * Create an async resource backed by a fetcher function.
   */
  export function createResource<T>(
    fetcher: () => Promise<T>,
    options?: { initialValue?: T; lazy?: boolean }
  ): Resource<T>;

  interface Context<T> {
    /** Provide a value. Returns a cleanup function to restore previous value. */
    Provider: (value: T) => () => void;
    /** Consume the current context value. */
    consume: () => T;
  }

  /**
   * Create a context for dependency injection.
   */
  export function createContext<T>(defaultValue?: T): Context<T>;

  /**
   * Create a selector — returns a function that produces a boolean signal
   * for whether a given key matches the source signal's value.
   */
  export function createSelector<T>(source: () => T): (key: T) => boolean;

  /**
   * Create a deferred/lazy memo that only computes on first read.
   */
  export function createDeferred<T>(fn: () => T): () => T;

  interface History<T> {
    canUndo: () => boolean;
    canRedo: () => boolean;
    undo: () => void;
    redo: () => void;
    clear: () => void;
  }

  /**
   * Create an undo/redo history tracker for a signal.
   */
  export function createHistory<T>(
    signal: [() => T, (value: T) => void],
    options?: { maxLength?: number }
  ): History<T>;
}
