// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/tags' {
  type TagFunction = (propsOrChild?: Record<string, any> | string | number | Node | (() => any), ...children: any[]) => HTMLElement;

  interface TagMap {
    [tag: string]: TagFunction;
    div: TagFunction;
    span: TagFunction;
    p: TagFunction;
    a: TagFunction;
    button: TagFunction;
    input: TagFunction;
    textarea: TagFunction;
    select: TagFunction;
    option: TagFunction;
    form: TagFunction;
    label: TagFunction;
    img: TagFunction;
    h1: TagFunction;
    h2: TagFunction;
    h3: TagFunction;
    h4: TagFunction;
    h5: TagFunction;
    h6: TagFunction;
    ul: TagFunction;
    ol: TagFunction;
    li: TagFunction;
    table: TagFunction;
    thead: TagFunction;
    tbody: TagFunction;
    tr: TagFunction;
    th: TagFunction;
    td: TagFunction;
    nav: TagFunction;
    header: TagFunction;
    footer: TagFunction;
    main: TagFunction;
    section: TagFunction;
    article: TagFunction;
    aside: TagFunction;
    details: TagFunction;
    summary: TagFunction;
    dialog: TagFunction;
    pre: TagFunction;
    code: TagFunction;
    em: TagFunction;
    strong: TagFunction;
    small: TagFunction;
    sub: TagFunction;
    sup: TagFunction;
    br: TagFunction;
    hr: TagFunction;
    svg: TagFunction;
    path: TagFunction;
  }

  /**
   * Proxy-based tag functions. Destructure what you need:
   * `const { div, p, h2, button } = tags;`
   */
  export const tags: TagMap;
}
