// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/tannins/auth' {
  export interface AuthConfig {
    /** POST endpoint for login. Default: '/api/auth/login'. */
    loginEndpoint?: string;
    /** POST endpoint for token refresh. Default: '/api/auth/refresh'. */
    refreshEndpoint?: string;
    /** POST endpoint for logout. Default: '/api/auth/logout'. */
    logoutEndpoint?: string;
    /** Storage key for the persisted token. Default: 'decantr_auth_token'. */
    tokenKey?: string;
    /** Which storage to use for token persistence. Default: 'localStorage'. */
    storage?: 'localStorage' | 'sessionStorage';
    /** Called whenever the isAuthenticated state changes. */
    onAuthChange?: (isAuthenticated: boolean) => void;
  }

  export interface AuthInstance {
    /** Signal getter for the current user object (null when not logged in). */
    user: () => any;
    /** Signal getter for the current auth token (null when not authenticated). */
    token: () => string | null;
    /** Derived signal — true when token is non-null. */
    isAuthenticated: () => boolean;
    /** Signal getter — true during login/logout/refresh operations. */
    isLoading: () => boolean;
    /** Signal getter for the last auth error (null when no error). */
    error: () => any;
    /** POST credentials to loginEndpoint. Sets token + user on success. */
    login: (credentials: Record<string, any>) => Promise<any>;
    /** Clear local auth state. Optionally POSTs to logoutEndpoint. */
    logout: () => Promise<void>;
    /** POST to refreshEndpoint to obtain a new token. */
    refresh: () => Promise<void>;
    /** Manually set the user object. */
    setUser: (user: any) => void;
    /** Manually set the auth token (or null to clear). */
    setToken: (token: string | null) => void;
    /** Remove fetch middleware and clean up reactive effects. */
    destroy: () => void;
  }

  /**
   * Create an auth instance with reactive signals, token persistence,
   * login/logout/refresh flows, and automatic fetch middleware.
   */
  export function createAuth(config?: AuthConfig): AuthInstance;

  export interface RequireAuthOptions {
    /** Path to redirect unauthenticated users to. Default: '/login'. */
    loginPath?: string;
    /** Query parameter name for the redirect URL. Default: 'redirect'. */
    redirectParam?: string;
    /** Custom authentication check function. */
    isAuthenticated?: () => boolean;
  }

  /**
   * Install a route guard that redirects unauthenticated users to a login page.
   * Returns a cleanup function to remove the guard.
   */
  export function requireAuth(router: any, options?: RequireAuthOptions): () => void;
}
