// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/test' {
  import type { TestContext } from 'node:test';

  export function describe(name: string, fn: () => void): void;
  export function it(name: string, fn: (t?: TestContext) => void | Promise<void>): void;
  export function test(name: string, fn: (t?: TestContext) => void | Promise<void>): void;
  export function before(fn: () => void | Promise<void>): void;
  export function after(fn: () => void | Promise<void>): void;
  export function beforeEach(fn: () => void | Promise<void>): void;
  export function afterEach(fn: () => void | Promise<void>): void;
  export function mock(target: any): any;

  export const assert: typeof import('node:assert/strict');

  interface DOMEnvironment {
    document: Document;
    cleanup: () => void;
  }

  /**
   * Create an isolated DOM environment for testing.
   */
  export function createDOM(): DOMEnvironment;

  interface RenderResult {
    container: Element;
    getByText: (text: string) => Element | null;
    getByClass: (cls: string) => Element | null;
    getById: (id: string) => Element | null;
    cleanup: () => void;
  }

  /**
   * Render a component for testing.
   */
  export function render(component: () => Node): RenderResult;

  /**
   * Dispatch a DOM event on an element.
   */
  export function fire(el: Element, event: string, detail?: Record<string, any>): void;

  /**
   * Flush pending reactive effects.
   */
  export function flush(): Promise<void>;
}
