export type {
  IRNodeType,
  IRLayer,
  IRSpatial,
  IRHookType,
  IRWiringSignal,
  IRWiring,
  IRPatternMeta,
  IRVisualEffect,
  IRCardWrapping,
  IRNavItem,
  IRShellConfig,
  IRThemeDecoration,
  IRTheme,
  IRRoute,
  IRNode,
  IRAppNode,
  IRShellNode,
  IRPageNode,
  IRPatternNode,
  IRBreakpointEntry,
  IRGridNode,
  IRStoreNode,
} from './types.js';
export type {
  ExecutionPackType,
  ExecutionPackTarget,
  ExecutionPackScope,
  ExecutionPackExample,
  ExecutionPackAntiPattern,
  ExecutionPackSuccessCheck,
  ExecutionPackTokenBudget,
  ExecutionPackBase,
  PackManifestEntry,
  PackManifestSectionEntry,
  PackManifestPageEntry,
  PackManifestMutationEntry,
  ExecutionPackManifest,
  ScaffoldPackRoute,
  ScaffoldPackData,
  ScaffoldExecutionPack,
  ScaffoldPackBuilderOptions,
  SectionPackInput,
  SectionPackRoute,
  SectionPackData,
  SectionExecutionPack,
  SectionPackBuilderOptions,
  PagePackInput,
  PagePackPattern,
  PagePackData,
  PageExecutionPack,
  PagePackBuilderOptions,
  MutationPackKind,
  MutationPackData,
  MutationExecutionPack,
  MutationPackBuilderOptions,
  ReviewPackKind,
  ReviewPackData,
  ReviewExecutionPack,
  ReviewPackBuilderOptions,
  ExecutionPackBundle,
  CompileExecutionPackBundleOptions,
} from './packs.js';

export type { PipelineOptions, PipelineResult } from './pipeline.js';
export { runPipeline } from './pipeline.js';
export { buildPageIR } from './ir.js';
export { resolveEssence, resolveVisualEffects } from './resolve.js';
export type { ResolvedPage, ResolvedEssence } from './resolve.js';
export { walkIR, findNodes, countPatterns, validateIR } from './ir-helpers.js';
export { pascalCase } from './utils.js';
export {
  EXECUTION_PACK_SCHEMA_URLS,
  PACK_MANIFEST_SCHEMA_URL,
  EXECUTION_PACK_BUNDLE_SCHEMA_URL,
  buildScaffoldPack,
  buildSectionPack,
  buildPagePack,
  buildMutationPack,
  buildReviewPack,
  resolvePackAdapter,
  listPackSections,
  listPackPages,
  compileExecutionPackBundle,
  renderExecutionPackMarkdown,
} from './packs.js';
