import { generateDecoratorRule } from './scaffold.js';

/**
 * Generate CSS for the 6 universal visual treatment categories,
 * plus theme treatment overrides and theme decorators.
 *
 * Layer 1: Base treatments (the 6 categories)
 * Layer 2: Theme treatment overrides (merged into base rules)
 * Layer 3: Theme decorators (appended after treatments)
 */
export function generateTreatmentCSS(
  spatialTokens: Record<string, string>,
  treatmentOverrides?: Record<string, Record<string, string>>,
  themeDecorators?: Record<string, string>,
  themeName?: string,
): string {
  const lines: string[] = [];

  lines.push('/* Generated by @decantr/cli — Visual Treatment System */');
  lines.push('');

  // ── Layer 1 + 2: Base Treatments (with optional overrides merged) ──

  lines.push('/* ── Layer 1: Base Treatments ── */');
  lines.push('');

  // Helper: merge overrides into a property map, then emit rule
  function emitRule(selector: string, props: [string, string][]): void {
    const treatmentName = selector.replace(/^\./, '').replace(/[:[\s].+$/, '');
    const overrides = treatmentOverrides?.[treatmentName];
    const merged = new Map<string, string>();
    for (const [prop, val] of props) {
      merged.set(prop, val);
    }
    if (overrides && selector === `.${treatmentName}`) {
      for (const [prop, val] of Object.entries(overrides)) {
        merged.set(prop, val);
      }
    }
    const body = Array.from(merged.entries())
      .map(([p, v]) => `  ${p}: ${v};`)
      .join('\n');
    lines.push(`${selector} {`);
    lines.push(body);
    lines.push('}');
    lines.push('');
  }

  // ── 1. Interactive Surface — .d-interactive ──

  emitRule('.d-interactive', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['gap', '0.5em'],
    ['padding', 'var(--d-interactive-py) var(--d-interactive-px)'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius)'],
    ['background', 'transparent'],
    ['color', 'var(--d-text)'],
    ['font', 'inherit'],
    ['cursor', 'pointer'],
    ['text-decoration', 'none'],
    ['transition', 'background 0.15s ease, border-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease, opacity 0.15s ease'],
  ]);

  emitRule('.d-interactive:hover', [
    ['border-color', 'var(--d-primary-hover)'],
    ['background', 'var(--d-surface)'],
  ]);

  emitRule('.d-interactive:focus-visible', [
    ['outline', '2px solid var(--d-primary)'],
    ['outline-offset', '2px'],
  ]);

  emitRule('.d-interactive:disabled', [
    ['opacity', '0.5'],
    ['cursor', 'not-allowed'],
    ['pointer-events', 'none'],
  ]);

  emitRule('.d-interactive[data-variant="primary"]', [
    ['background', 'var(--d-primary)'],
    ['color', '#fff'],
    ['border-color', 'var(--d-primary)'],
  ]);

  emitRule('.d-interactive[data-variant="primary"]:hover', [
    ['background', 'var(--d-primary-hover)'],
    ['border-color', 'var(--d-primary-hover)'],
  ]);

  emitRule('.d-interactive[data-variant="ghost"]', [
    ['border-color', 'transparent'],
    ['background', 'transparent'],
  ]);

  emitRule('.d-interactive[data-variant="ghost"]:hover', [
    ['background', 'var(--d-surface)'],
  ]);

  emitRule('.d-interactive[data-variant="danger"]', [
    ['background', 'var(--d-error)'],
    ['color', '#fff'],
    ['border-color', 'var(--d-error)'],
  ]);

  // ── 2. Container Surface — .d-surface ──

  emitRule('.d-surface', [
    ['background', 'var(--d-surface)'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius)'],
    ['box-shadow', 'var(--d-shadow)'],
    ['padding', 'var(--d-surface-p)'],
  ]);

  emitRule('.d-surface[data-elevation="raised"]', [
    ['background', 'var(--d-surface-raised)'],
    ['box-shadow', 'var(--d-shadow-md)'],
  ]);

  emitRule('.d-surface[data-elevation="overlay"]', [
    ['background', 'var(--d-surface-raised)'],
    ['box-shadow', 'var(--d-shadow-lg)'],
    ['z-index', '50'],
  ]);

  emitRule('.d-surface[data-interactive]:hover', [
    ['border-color', 'var(--d-primary-hover, var(--d-border))'],
    ['box-shadow', 'var(--d-shadow-md)'],
    ['transition', 'border-color 0.15s ease, box-shadow 0.15s ease'],
  ]);

  // ── 3. Data Display — .d-data, .d-data-header, .d-data-row, .d-data-cell ──

  emitRule('.d-data', [
    ['width', '100%'],
    ['border-collapse', 'collapse'],
    ['text-align', 'left'],
    ['font-size', '0.875rem'],
  ]);

  emitRule('.d-data-header', [
    ['padding', 'var(--d-data-py) var(--d-content-gap)'],
    ['font-weight', '500'],
    ['color', 'var(--d-text-muted)'],
    ['border-bottom', '1px solid var(--d-border)'],
    ['font-size', '0.75rem'],
    ['text-transform', 'uppercase'],
    ['letter-spacing', '0.05em'],
  ]);

  emitRule('.d-data-row', [
    ['border-bottom', '1px solid var(--d-border)'],
    ['transition', 'background 0.1s ease'],
  ]);

  emitRule('.d-data-row:hover', [
    ['background', 'var(--d-surface)'],
  ]);

  emitRule('.d-data-cell', [
    ['padding', 'var(--d-data-py) var(--d-content-gap)'],
    ['vertical-align', 'middle'],
  ]);

  // ── 4. Form Control — .d-control ──

  emitRule('.d-control', [
    ['background', 'var(--d-surface)'],
    ['color', 'var(--d-text)'],
    ['padding', 'var(--d-control-py) 0.75rem'],
    ['border-radius', 'var(--d-radius)'],
    ['border', '1px solid var(--d-border)'],
    ['width', '100%'],
    ['outline', 'none'],
    ['font', 'inherit'],
    ['transition', 'border-color 0.15s ease, box-shadow 0.15s ease'],
  ]);

  emitRule('.d-control:focus', [
    ['border-color', 'var(--d-primary)'],
    ['box-shadow', '0 0 0 3px color-mix(in srgb, var(--d-primary) 25%, transparent)'],
  ]);

  emitRule('.d-control::placeholder', [
    ['color', 'var(--d-text-muted)'],
  ]);

  emitRule('.d-control:disabled', [
    ['opacity', '0.5'],
    ['cursor', 'not-allowed'],
  ]);

  emitRule('.d-control[aria-invalid]', [
    ['border-color', 'var(--d-error)'],
    ['box-shadow', '0 0 0 3px color-mix(in srgb, var(--d-error) 15%, transparent)'],
  ]);

  // ── 5. Section Rhythm — .d-section ──

  emitRule('.d-section', [
    ['padding', 'var(--d-section-py) 0'],
  ]);

  lines.push('.d-section + .d-section {');
  lines.push('  border-top: 1px solid var(--d-border);');
  lines.push('}');
  lines.push('');

  // ── 6. Inline Annotation — .d-annotation ──

  emitRule('.d-annotation', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['gap', '0.25em'],
    ['font-size', '0.75rem'],
    ['font-weight', '500'],
    ['padding', '0.125rem 0.5rem'],
    ['border-radius', 'var(--d-radius-full)'],
    ['background', 'var(--d-surface)'],
    ['color', 'var(--d-text-muted)'],
    ['white-space', 'nowrap'],
  ]);

  emitRule('.d-annotation[data-status="success"]', [
    ['background', 'color-mix(in srgb, var(--d-success) 15%, transparent)'],
    ['color', 'var(--d-success)'],
  ]);

  emitRule('.d-annotation[data-status="error"]', [
    ['background', 'color-mix(in srgb, var(--d-error) 15%, transparent)'],
    ['color', 'var(--d-error)'],
  ]);

  emitRule('.d-annotation[data-status="warning"]', [
    ['background', 'color-mix(in srgb, var(--d-warning) 15%, transparent)'],
    ['color', 'var(--d-warning)'],
  ]);

  emitRule('.d-annotation[data-status="info"]', [
    ['background', 'color-mix(in srgb, var(--d-info) 15%, transparent)'],
    ['color', 'var(--d-info)'],
  ]);

  // ── Layer 3: Theme Decorators ──

  if (themeDecorators && Object.keys(themeDecorators).length > 0) {
    const label = themeName ? ` (${themeName})` : '';
    lines.push(`/* ── Layer 3: Theme Decorators${label} ── */`);
    lines.push('');

    for (const [name, description] of Object.entries(themeDecorators)) {
      const rule = generateDecoratorRule(name, description);
      lines.push(rule);
      lines.push('');
    }
  }

  // ── Keyframes ──

  lines.push('/* ── Keyframes ── */');
  lines.push('');
  lines.push('@keyframes decantr-fade-in {');
  lines.push('  from { opacity: 0; transform: translateY(4px); }');
  lines.push('  to { opacity: 1; transform: translateY(0); }');
  lines.push('}');
  lines.push('');
  lines.push('@keyframes decantr-pulse {');
  lines.push('  0%, 100% { opacity: 1; }');
  lines.push('  50% { opacity: 0.5; }');
  lines.push('}');

  return lines.join('\n');
}
