/**
 * Generate CSS for the 6 universal visual treatment categories,
 * plus theme treatment overrides.
 *
 * Layer 1: Base treatments (the 6 categories)
 * Layer 2: Theme treatment overrides (merged into base rules)
 * Layer 3: Decorator stub (AI generates decorator CSS from structured definitions)
 */
export function generateTreatmentCSS(
  spatialTokens: Record<string, string>,
  treatmentOverrides?: Record<string, Record<string, string>>,
  themeDecorators?: Record<string, string>,
  themeName?: string,
  themeDecoratorDefinitions?: Record<
    string,
    {
      description?: string;
      intent?: string;
      suggested_properties?: Record<string, string>;
      /**
       * Optional state-variant CSS emitted as pseudo-class rules on the same
       * selector. Each is a flat property map; keys are CSS declarations, not
       * nested selectors. Missing fields fall back to current behavior (base
       * properties only). Introduced for P0-1 so decorator prose that
       * promises hover / focus / active styling (e.g. "carbon-card gains a
       * neon cyan shadow on hover") can be delivered by the content pipeline
       * instead of every scaffolded app reaching for inline styles.
       */
      hover_properties?: Record<string, string>;
      focus_properties?: Record<string, string>;
      active_properties?: Record<string, string>;
      pairs_with?: string[];
      usage?: string[];
    }
  >,
): string {
  const lines: string[] = [];
  const decoratorAnimationNames = new Set<string>();

  lines.push('/* Generated by @decantr/cli — Visual Treatment System */');
  lines.push('');

  // ── Layer 1 + 2: Base Treatments (with optional overrides merged) ──

  lines.push('@layer treatments {');
  lines.push('');
  lines.push('/* ── Layer 1: Base Treatments ── */');
  lines.push('');

  // Properties that are theme-specific effects and should not merge into the base rule.
  // These are emitted in a separate theme-scoped block instead.
  const THEME_ONLY_PROPS = new Set(['backdrop-filter', '-webkit-backdrop-filter']);

  // Collect theme-scoped overrides to emit after base rules
  const themeOverrideRules: string[] = [];

  // Helper: merge overrides into a property map, then emit rule.
  // Theme-specific properties (e.g. backdrop-filter) are separated and
  // emitted later in a theme-scoped block so they don't leak into the base.
  function emitRule(selector: string, props: [string, string][]): void {
    const treatmentName = selector.replace(/^\./, '').replace(/[:[\s].+$/, '');
    const overrides = treatmentOverrides?.[treatmentName];
    const merged = new Map<string, string>();
    for (const [prop, val] of props) {
      merged.set(prop, val);
    }
    if (overrides && selector === `.${treatmentName}`) {
      const themeProps: [string, string][] = [];
      for (const [prop, val] of Object.entries(overrides)) {
        if (THEME_ONLY_PROPS.has(prop)) {
          themeProps.push([prop, val]);
        } else {
          merged.set(prop, val);
        }
      }
      // Emit theme-only properties in a separate scoped rule
      if (themeProps.length > 0 && themeName) {
        const themeSelector = `[data-theme="${themeName}"] ${selector}`;
        const themeBody = themeProps.map(([p, v]) => `  ${p}: ${v};`).join('\n');
        themeOverrideRules.push(`${themeSelector} {\n${themeBody}\n}`);
      }
    }
    const body = Array.from(merged.entries())
      .map(([p, v]) => `  ${p}: ${v};`)
      .join('\n');
    lines.push(`${selector} {`);
    lines.push(body);
    lines.push('}');
    lines.push('');
  }

  // ── 1. Interactive Surface — .d-interactive ──

  emitRule('.d-interactive', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['gap', '0.5em'],
    [
      'padding',
      'calc(var(--d-interactive-py) * var(--d-density-scale, 1)) var(--d-interactive-px)',
    ],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius)'],
    ['background', 'transparent'],
    ['color', 'var(--d-text)'],
    ['font', 'inherit'],
    ['cursor', 'pointer'],
    ['text-decoration', 'none'],
    [
      'transition',
      'background 0.15s ease, border-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease, opacity 0.15s ease',
    ],
  ]);

  emitRule('.d-interactive:hover', [
    ['border-color', 'var(--d-primary-hover)'],
    ['background', 'var(--d-surface)'],
  ]);

  emitRule('.d-interactive:focus-visible', [
    ['outline', '2px solid var(--d-primary)'],
    ['outline-offset', '2px'],
  ]);

  emitRule('.d-interactive:disabled', [
    ['opacity', '0.5'],
    ['cursor', 'not-allowed'],
    ['pointer-events', 'none'],
  ]);

  emitRule('.d-interactive[data-variant="primary"]', [
    ['background', 'var(--d-primary)'],
    ['color', '#fff'],
    ['border-color', 'var(--d-primary)'],
  ]);

  emitRule('.d-interactive[data-variant="primary"]:hover', [
    ['background', 'var(--d-primary-hover)'],
    ['border-color', 'var(--d-primary-hover)'],
  ]);

  emitRule('.d-interactive[data-variant="ghost"]', [
    ['border-color', 'transparent'],
    ['background', 'transparent'],
  ]);

  emitRule('.d-interactive[data-variant="ghost"]:hover', [['background', 'var(--d-surface)']]);

  emitRule('.d-interactive[data-variant="danger"]', [
    ['background', 'var(--d-error)'],
    ['color', '#fff'],
    ['border-color', 'var(--d-error)'],
  ]);

  // Size variants. Default (no data-size) is "md". Use "sm" for compact chrome
  // (52px-tall headers, 32px nav items) and "lg" for prominent primary CTAs.
  // Eliminates inline padding/font-size workarounds for non-default sizes.
  emitRule('.d-interactive[data-size="sm"]', [
    [
      'padding',
      'calc(var(--d-interactive-py) * 0.5 * var(--d-density-scale, 1)) calc(var(--d-interactive-px) * 0.75)',
    ],
    ['font-size', '0.875rem'],
    ['gap', '0.375em'],
  ]);

  emitRule('.d-interactive[data-size="md"]', [
    // Explicit md — same as default. Lets authors opt in without inheriting
    // contextual sizing from an ancestor that may have set data-size.
    [
      'padding',
      'calc(var(--d-interactive-py) * var(--d-density-scale, 1)) var(--d-interactive-px)',
    ],
    ['font-size', '1rem'],
    ['gap', '0.5em'],
  ]);

  emitRule('.d-interactive[data-size="lg"]', [
    [
      'padding',
      'calc(var(--d-interactive-py) * 1.5 * var(--d-density-scale, 1)) calc(var(--d-interactive-px) * 1.25)',
    ],
    ['font-size', '1.125rem'],
    ['gap', '0.625em'],
  ]);

  // ── 2. Container Surface — .d-surface ──

  emitRule('.d-surface', [
    ['background', 'var(--d-surface)'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius)'],
    ['box-shadow', 'var(--d-shadow)'],
    ['padding', 'calc(var(--d-surface-p) * var(--d-density-scale, 1))'],
  ]);

  emitRule('.d-surface[data-elevation="raised"]', [
    ['background', 'var(--d-surface-raised)'],
    ['box-shadow', 'var(--d-shadow-md)'],
  ]);

  emitRule('.d-surface[data-elevation="overlay"]', [
    ['background', 'var(--d-surface-raised)'],
    ['box-shadow', 'var(--d-shadow-lg)'],
    ['z-index', '50'],
  ]);

  emitRule('.d-surface[data-interactive]', [['cursor', 'pointer']]);

  emitRule('.d-surface[data-interactive]:hover', [
    ['border-color', 'var(--d-primary-hover, var(--d-border))'],
    ['box-shadow', 'var(--d-shadow-md)'],
    ['transition', 'border-color 0.15s ease, box-shadow 0.15s ease'],
  ]);

  // ── 3. Data Display — .d-data, .d-data-header, .d-data-row, .d-data-cell ──

  emitRule('.d-data', [
    ['width', '100%'],
    ['border-collapse', 'collapse'],
    ['text-align', 'left'],
    ['font-size', '0.875rem'],
  ]);

  emitRule('.d-data-header', [
    ['padding', 'calc(var(--d-data-py) * var(--d-density-scale, 1)) var(--d-content-gap)'],
    ['font-weight', '500'],
    ['color', 'var(--d-text-muted)'],
    ['border-bottom', '1px solid var(--d-border)'],
    ['font-size', '0.75rem'],
    ['text-transform', 'uppercase'],
    ['letter-spacing', '0.05em'],
  ]);

  emitRule('.d-data-row', [
    ['border-bottom', '1px solid var(--d-border)'],
    ['transition', 'background 0.1s ease'],
  ]);

  emitRule('.d-data-row:hover', [['background', 'var(--d-surface)']]);

  emitRule('.d-data-cell', [
    ['padding', 'calc(var(--d-data-py) * var(--d-density-scale, 1)) var(--d-content-gap)'],
    ['vertical-align', 'middle'],
  ]);

  // ── 4. Form Control — .d-control ──

  emitRule('.d-control', [
    ['background', 'var(--d-surface)'],
    ['color', 'var(--d-text)'],
    ['padding', 'calc(var(--d-control-py) * var(--d-density-scale, 1)) 0.75rem'],
    ['border-radius', 'var(--d-radius)'],
    ['border', '1px solid var(--d-border)'],
    ['width', '100%'],
    ['outline', 'none'],
    ['font', 'inherit'],
    ['transition', 'border-color 0.15s ease, box-shadow 0.15s ease'],
  ]);

  emitRule('.d-control:focus', [
    ['border-color', 'var(--d-primary)'],
    ['box-shadow', '0 0 0 3px color-mix(in srgb, var(--d-primary) 25%, transparent)'],
  ]);

  emitRule('.d-control::placeholder', [['color', 'var(--d-text-muted)']]);

  emitRule('.d-control:disabled', [
    ['opacity', '0.5'],
    ['cursor', 'not-allowed'],
  ]);

  emitRule('.d-control[aria-invalid]', [
    ['border-color', 'var(--d-error)'],
    ['box-shadow', '0 0 0 3px color-mix(in srgb, var(--d-error) 15%, transparent)'],
  ]);

  // ── 5. Section Rhythm — .d-section ──

  // ── Section Rhythm ──
  emitRule('.d-section', [
    ['--d-density-scale', '1'],
    ['padding', 'calc(var(--d-section-py) * var(--d-density-scale)) 0'],
  ]);

  // Density variants — broadcast scale to descendants
  lines.push('.d-section[data-density="compact"] {');
  lines.push('  --d-density-scale: 0.65;');
  lines.push('}');
  lines.push('');

  lines.push('.d-section[data-density="spacious"] {');
  lines.push('  --d-density-scale: 1.4;');
  lines.push('}');
  lines.push('');

  // Adjacent section separator — density-aware gap
  lines.push('.d-section + .d-section {');
  lines.push('  border-top: 1px solid transparent;');
  lines.push(
    '  border-image: linear-gradient(to right, transparent, var(--d-border), transparent) 1;',
  );
  lines.push('  margin-top: calc(var(--d-section-gap) * var(--d-density-scale, 1));');
  lines.push('}');
  lines.push('');

  // ── 6. Inline Annotation — .d-annotation ──

  emitRule('.d-annotation', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['gap', '0.25em'],
    ['font-size', '0.75rem'],
    ['font-weight', '500'],
    ['padding', '0.125rem 0.5rem'],
    ['border-radius', 'var(--d-radius-full)'],
    ['background', 'color-mix(in srgb, var(--d-surface-raised) 88%, transparent)'],
    ['border', '1px solid color-mix(in srgb, var(--d-border) 72%, transparent)'],
    ['color', 'var(--d-text-muted)'],
    ['white-space', 'nowrap'],
  ]);

  emitRule('.d-annotation[data-status="success"]', [
    ['background', 'color-mix(in srgb, var(--d-success) 15%, transparent)'],
    ['color', 'var(--d-success)'],
  ]);

  emitRule('.d-annotation[data-status="error"]', [
    ['background', 'color-mix(in srgb, var(--d-error) 15%, transparent)'],
    ['color', 'var(--d-error)'],
  ]);

  emitRule('.d-annotation[data-status="warning"]', [
    ['background', 'color-mix(in srgb, var(--d-warning) 15%, transparent)'],
    ['color', 'var(--d-warning)'],
  ]);

  emitRule('.d-annotation[data-status="info"]', [
    ['background', 'color-mix(in srgb, var(--d-info) 15%, transparent)'],
    ['color', 'var(--d-info)'],
  ]);

  // ── 7. Label Utility — .d-label ──

  // ── Label ──
  emitRule('.d-label', [
    ['font-size', '0.7rem'],
    ['font-weight', '600'],
    ['text-transform', 'uppercase'],
    ['letter-spacing', '0.08em'],
    ['color', 'var(--d-text-muted)'],
    ['font-family', 'var(--d-font-mono, ui-monospace, monospace)'],
    ['display', 'block'],
    ['margin-bottom', 'calc(var(--d-label-mb) * var(--d-density-scale, 1))'],
  ]);

  // Anchored section header variant — accent border
  emitRule('.d-label[data-anchor]', [
    ['padding-left', 'var(--d-label-px)'],
    ['border-left', '2px solid var(--d-accent)'],
  ]);

  // ── 8. Text Link — .d-link ──
  // Chromeless inline anchor. Covers breadcrumbs, footer links, inline
  // body-copy links, and "learn more" affordances. The v4 ecommerce
  // harness forced 5+ hand-rolled `.nav-link` / `.nav-link-active`
  // classes because there was no link treatment.

  emitRule('.d-link', [
    ['color', 'var(--d-text)'],
    ['text-decoration', 'none'],
    ['border-bottom', '1px solid transparent'],
    ['transition', 'color 0.15s ease, border-color 0.15s ease'],
    ['cursor', 'pointer'],
  ]);

  emitRule('.d-link:hover', [
    ['color', 'var(--d-primary)'],
    ['border-bottom-color', 'var(--d-primary)'],
  ]);

  emitRule('.d-link:focus-visible', [
    ['outline', '2px solid var(--d-primary)'],
    ['outline-offset', '2px'],
    ['border-radius', '2px'],
  ]);

  emitRule('.d-link[data-variant="subtle"]', [['color', 'var(--d-text-muted)']]);

  emitRule('.d-link[data-variant="subtle"]:hover', [
    ['color', 'var(--d-text)'],
    ['border-bottom-color', 'var(--d-text)'],
  ]);

  emitRule('.d-link[data-variant="strong"]', [
    ['color', 'var(--d-primary)'],
    ['font-weight', '500'],
  ]);

  emitRule('.d-link[data-variant="strong"]:hover', [
    ['color', 'var(--d-primary-hover)'],
    ['border-bottom-color', 'var(--d-primary-hover)'],
  ]);

  // Active state for nav-link-style usage (e.g., sidebar/topnav when
  // current route matches). Pair with aria-current="page" for a11y.
  emitRule('.d-link[aria-current="page"], .d-link[data-active="true"]', [
    ['color', 'var(--d-primary)'],
    ['font-weight', '500'],
  ]);

  // ── 9. Icon Button — .d-icon-btn ──
  // Chromeless square button for icon-only actions (header actions,
  // card overflow menus, close X, etc.). Avoids the hand-rolled
  // `.icon-btn` / `.header-btn` classes the ecommerce harness produced.

  emitRule('.d-icon-btn', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['justify-content', 'center'],
    ['width', '2rem'],
    ['height', '2rem'],
    ['border', 'none'],
    ['background', 'transparent'],
    ['color', 'var(--d-text-muted)'],
    ['border-radius', 'var(--d-radius-sm)'],
    ['cursor', 'pointer'],
    ['transition', 'background 0.15s ease, color 0.15s ease'],
  ]);

  emitRule('.d-icon-btn:hover', [
    ['background', 'color-mix(in srgb, var(--d-text) 8%, transparent)'],
    ['color', 'var(--d-text)'],
  ]);

  emitRule('.d-icon-btn:focus-visible', [
    ['outline', '2px solid var(--d-primary)'],
    ['outline-offset', '2px'],
  ]);

  emitRule('.d-icon-btn:disabled', [
    ['opacity', '0.5'],
    ['cursor', 'not-allowed'],
    ['pointer-events', 'none'],
  ]);

  emitRule('.d-icon-btn[data-size="sm"]', [
    ['width', '1.5rem'],
    ['height', '1.5rem'],
  ]);

  emitRule('.d-icon-btn[data-size="lg"]', [
    ['width', '2.5rem'],
    ['height', '2.5rem'],
  ]);

  emitRule('.d-icon-btn[data-variant="primary"]', [
    ['background', 'var(--d-primary)'],
    ['color', '#fff'],
  ]);

  emitRule('.d-icon-btn[data-variant="primary"]:hover', [['background', 'var(--d-primary-hover)']]);

  // ── 10. Sidebar Nav Link — .d-nav-link ──
  // Muted-by-default nav-link row. `[data-active]` or `aria-current="page"`
  // switches to the "current route" pill style with primary accent.
  // Replaces hand-rolled `.sidebar-link` / `.nav-link-active` classes.

  emitRule('.d-nav-link', [
    ['display', 'flex'],
    ['align-items', 'center'],
    ['gap', '0.5rem'],
    ['padding', '0.5rem 0.75rem'],
    ['border-radius', 'var(--d-radius-sm)'],
    ['color', 'var(--d-text-muted)'],
    ['text-decoration', 'none'],
    ['font-size', '0.875rem'],
    ['cursor', 'pointer'],
    ['transition', 'background 0.15s ease, color 0.15s ease'],
    ['border-left', '2px solid transparent'],
  ]);

  emitRule('.d-nav-link:hover', [
    ['color', 'var(--d-text)'],
    ['background', 'color-mix(in srgb, var(--d-text) 6%, transparent)'],
  ]);

  emitRule('.d-nav-link:focus-visible', [
    ['outline', '2px solid var(--d-primary)'],
    ['outline-offset', '2px'],
  ]);

  // Active state — matches whichever attribute the framework produces.
  emitRule('.d-nav-link[aria-current="page"], .d-nav-link[data-active="true"]', [
    ['color', 'var(--d-primary)'],
    ['background', 'color-mix(in srgb, var(--d-primary) 10%, transparent)'],
    ['border-left-color', 'var(--d-primary)'],
    ['font-weight', '500'],
  ]);

  // ── 11. Stepper Chip — .d-step-chip ──
  // Circular badge for wizard/checkout steppers. Handles the three
  // canonical states (pending / active / done).

  emitRule('.d-step-chip', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['justify-content', 'center'],
    ['width', '2rem'],
    ['height', '2rem'],
    ['border-radius', '50%'],
    ['border', '1.5px solid var(--d-border)'],
    ['background', 'transparent'],
    ['color', 'var(--d-text-muted)'],
    ['font-size', '0.875rem'],
    ['font-weight', '600'],
    ['font-variant-numeric', 'tabular-nums'],
    ['transition', 'background 0.15s ease, border-color 0.15s ease, color 0.15s ease'],
  ]);

  emitRule('.d-step-chip[data-step-state="active"]', [
    ['background', 'var(--d-primary)'],
    ['border-color', 'var(--d-primary)'],
    ['color', '#fff'],
  ]);

  emitRule('.d-step-chip[data-step-state="done"]', [
    ['background', 'color-mix(in srgb, var(--d-success) 15%, transparent)'],
    ['border-color', 'var(--d-success)'],
    ['color', 'var(--d-success)'],
  ]);

  // ── 12a. Agent Node + Ports — .d-agent-node ──
  // Card for spatial/graph canvases where nodes render as positioned
  // cards with connection ports. Eliminates the 15-inline-style cluster
  // the v4 harness reported in AgentSwarmCanvas. Pair with absolute
  // positioning on the parent canvas; this treatment only handles the
  // card's internal layout + port anchors.

  emitRule('.d-agent-node', [
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['gap', '0.5rem'],
    ['position', 'relative'],
    ['min-width', '200px'],
    ['max-width', '260px'],
    ['padding', '0.75rem'],
    ['background', 'var(--d-surface)'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius)'],
    ['cursor', 'pointer'],
    ['transition', 'border-color 0.15s ease, box-shadow 0.15s ease, transform 0.15s ease'],
  ]);

  emitRule('.d-agent-node:hover', [
    ['border-color', 'var(--d-primary)'],
    ['transform', 'translateY(-1px)'],
  ]);

  emitRule('.d-agent-node[data-status="error"]', [
    ['box-shadow', '0 0 12px color-mix(in srgb, var(--d-error) 25%, transparent)'],
    ['border-color', 'color-mix(in srgb, var(--d-error) 60%, transparent)'],
  ]);

  emitRule('.d-agent-node[data-status="active"]', [['border-color', 'var(--d-primary)']]);

  // Connection ports — positioned absolutely on the node edges so SVG
  // connection paths can anchor to predictable coordinates instead of
  // guessing center offsets. Pair with canvas that reads getBoundingClientRect
  // on these elements.
  emitRule('.d-port', [
    ['position', 'absolute'],
    ['width', '8px'],
    ['height', '8px'],
    ['border-radius', '50%'],
    ['background', 'var(--d-border)'],
    ['top', '50%'],
    ['transform', 'translateY(-50%)'],
    ['transition', 'background 0.15s ease'],
  ]);

  emitRule('.d-port[data-side="left"]', [['left', '-4px']]);

  emitRule('.d-port[data-side="right"]', [['right', '-4px']]);

  emitRule('.d-port[data-side="top"]', [
    ['top', '-4px'],
    ['left', '50%'],
    ['transform', 'translateX(-50%)'],
  ]);

  emitRule('.d-port[data-side="bottom"]', [
    ['bottom', '-4px'],
    ['top', 'auto'],
    ['left', '50%'],
    ['transform', 'translateX(-50%)'],
  ]);

  emitRule('.d-port[data-active="true"]', [['background', 'var(--d-primary)']]);

  // ── 12b. CTA Banner — .d-cta-banner ──
  // Prominent full-width CTA with gradient wash + dark pill action.
  // Replaces the inline-hex cluster the v4 harness reported in CtaBanner
  // (the pack contract was asking for `_bgdark` / `_fgwhite` atoms that
  // don't exist — now there's a semantic treatment for it).

  emitRule('.d-cta-banner', [
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['align-items', 'center'],
    ['justify-content', 'center'],
    ['gap', '1rem'],
    ['padding', '3rem 1.5rem'],
    ['border-radius', 'var(--d-radius-lg)'],
    ['text-align', 'center'],
    ['position', 'relative'],
    ['overflow', 'hidden'],
    // Default gradient uses theme tokens — themes can override the stops
    // via CSS variables --d-cta-gradient if desired.
    [
      'background',
      'var(--d-cta-gradient, linear-gradient(135deg, color-mix(in srgb, var(--d-primary) 85%, transparent), color-mix(in srgb, var(--d-accent) 80%, transparent)))',
    ],
    ['color', 'var(--d-cta-text, #ffffff)'],
  ]);

  emitRule('.d-cta-banner[data-size="compact"]', [
    ['padding', '1.5rem 1rem'],
    ['gap', '0.5rem'],
  ]);

  emitRule('.d-cta-banner[data-size="hero"]', [
    ['padding', '5rem 2rem'],
    ['gap', '1.5rem'],
  ]);

  // Dark pill CTA inside a banner — the v4 harness explicitly called out
  // this shape. Using a d-interactive with data-variant="dark" parallels
  // the existing primary/ghost/danger variants.
  emitRule('.d-interactive[data-variant="dark"]', [
    ['background', 'var(--d-cta-pill-bg, #18181b)'],
    ['color', 'var(--d-cta-pill-text, #ffffff)'],
    ['border-color', 'transparent'],
    ['border-radius', 'var(--d-radius-full)'],
  ]);

  emitRule('.d-interactive[data-variant="dark"]:hover', [
    ['background', 'var(--d-cta-pill-bg-hover, #27272a)'],
  ]);

  // ── 12. Divider Utilities ──
  // Single-side border rules. Use these as plain class additions on
  // containers instead of hand-rolling `.divider-top` / `.divider-bottom`.

  emitRule('.d-divider-top', [['border-top', '1px solid var(--d-border)']]);

  emitRule('.d-divider-bottom', [['border-bottom', '1px solid var(--d-border)']]);

  emitRule('.d-divider-left', [['border-left', '1px solid var(--d-border)']]);

  emitRule('.d-divider-right', [['border-right', '1px solid var(--d-border)']]);

  // Horizontal standalone divider element (<hr class="d-divider">).
  emitRule('.d-divider', [
    ['border', '0'],
    ['border-top', '1px solid var(--d-border)'],
    ['margin', '0'],
    ['width', '100%'],
    ['height', '0'],
  ]);

  // ── 13. Shell Structural Treatments — .d-shell-* ──
  // The v5 harness reported that cold scaffolds hand-rolled 310 lines /
  // 56 CSS classes of shell structural layout because Decantr didn't
  // ship shell treatments. These treatments cover the three shells
  // declared across most blueprints: sidebar-main, centered,
  // top-nav-footer. Compose with atoms for per-region overrides.

  // Root shell container — full viewport height + overflow containment.
  emitRule('.d-shell', [
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['min-height', '100vh'],
    ['background', 'var(--d-bg)'],
    ['color', 'var(--d-text)'],
  ]);

  // Sidebar-main variant — sidebar + main body side by side.
  emitRule('.d-shell[data-layout="sidebar-main"]', [
    ['flex-direction', 'row'],
    ['height', '100vh'],
    ['overflow', 'hidden'],
  ]);

  // Centered variant — single card centered in the viewport.
  emitRule('.d-shell[data-layout="centered"]', [
    ['align-items', 'center'],
    ['justify-content', 'center'],
    ['padding', '1rem'],
  ]);

  // Sidebar region — 240px persistent nav column.
  emitRule('.d-shell-sidebar', [
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['width', '240px'],
    ['flex-shrink', '0'],
    ['border-right', '1px solid var(--d-border)'],
    ['background', 'var(--d-surface)'],
    ['overflow-y', 'auto'],
    ['transition', 'width 0.2s ease, transform 0.2s ease'],
  ]);

  // Collapsed rail variant — 64px icon-only.
  emitRule('.d-shell-sidebar[data-collapsed="true"]', [['width', '64px']]);

  // Below md: sidebar becomes an off-canvas drawer controlled by
  // `data-mobile-open="true|false"`. Hidden by default (translate off-screen).
  lines.push('@media (max-width: 767.98px) {');
  lines.push('  .d-shell-sidebar {');
  lines.push('    position: fixed;');
  lines.push('    top: 0;');
  lines.push('    left: 0;');
  lines.push('    bottom: 0;');
  lines.push('    z-index: 50;');
  lines.push('    transform: translateX(-100%);');
  lines.push('  }');
  lines.push('  .d-shell-sidebar[data-mobile-open="true"] {');
  lines.push('    transform: translateX(0);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Main content area (to the right of sidebar, or spanning full width
  // in top-nav-* shells). Takes remaining space, scroll container itself.
  emitRule('.d-shell-main', [
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['flex', '1'],
    ['min-width', '0'],
    ['overflow', 'hidden'],
  ]);

  // Header — 52px sticky top bar. Used inside d-shell-main (sidebar-main)
  // or at the top of d-shell (top-nav-*). Horizontal layout, flex aligned.
  emitRule('.d-shell-header', [
    ['display', 'flex'],
    ['align-items', 'center'],
    ['justify-content', 'space-between'],
    ['gap', '1rem'],
    ['height', '52px'],
    ['flex-shrink', '0'],
    ['padding', '0 clamp(1rem, 2vw, 1.5rem)'],
    ['border-bottom', '1px solid var(--d-border)'],
    ['background', 'var(--d-bg)'],
    ['position', 'sticky'],
    ['top', '0'],
    ['z-index', '10'],
  ]);

  // Body — scrollable main region inside d-shell-main.
  emitRule('.d-shell-body', [
    ['flex', '1'],
    ['overflow-y', 'auto'],
    ['padding', '1rem'],
  ]);

  // Body size variants.
  emitRule('.d-shell-body[data-padding="compact"]', [['padding', '0.75rem']]);

  emitRule('.d-shell-body[data-padding="spacious"]', [['padding', '1.5rem']]);

  emitRule('.d-shell-body[data-padding="none"]', [['padding', '0']]);

  // Footer — narrow band below body.
  emitRule('.d-shell-footer', [
    ['padding', '1rem clamp(1rem, 2vw, 1.5rem)'],
    ['border-top', '1px solid var(--d-border)'],
    ['background', 'var(--d-surface)'],
    ['flex-shrink', '0'],
  ]);

  // Centered card — the content parent inside d-shell[data-layout="centered"].
  emitRule('.d-shell-centered-card', [
    ['width', '100%'],
    ['max-width', '28rem'],
  ]);

  // ── 14. Modal + Palette Chrome — .d-modal, .d-palette, .d-kbd ──
  // The v5 harness reported that command_palette is a mandatory feature
  // in every scaffold-pack but Decantr shipped no modal/palette treatments.
  // Cold scaffolds hand-rolled the same overlay chrome repeatedly. These
  // treatments cover the universal modal + palette shape.

  // Modal root — fixed overlay covering viewport.
  emitRule('.d-modal', [
    ['position', 'fixed'],
    ['inset', '0'],
    ['z-index', '100'],
    ['display', 'flex'],
    ['align-items', 'center'],
    ['justify-content', 'center'],
    ['padding', '1rem'],
  ]);

  emitRule('.d-modal[data-align="top"]', [
    ['align-items', 'flex-start'],
    ['padding-top', '15vh'],
  ]);

  // Backdrop — absolute scrim that covers everything.
  emitRule('.d-modal-backdrop', [
    ['position', 'absolute'],
    ['inset', '0'],
    ['background', 'color-mix(in srgb, var(--d-bg) 70%, transparent)'],
    ['backdrop-filter', 'blur(8px)'],
    ['-webkit-backdrop-filter', 'blur(8px)'],
  ]);

  // Panel — the actual dialog content.
  emitRule('.d-modal-panel', [
    ['position', 'relative'],
    ['z-index', '1'],
    ['width', '100%'],
    ['max-width', '32rem'],
    ['background', 'var(--d-surface-raised)'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius-lg)'],
    ['box-shadow', 'var(--d-shadow-lg)'],
    ['max-height', '85vh'],
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['overflow', 'hidden'],
  ]);

  emitRule('.d-modal-panel[data-size="sm"]', [['max-width', '24rem']]);

  emitRule('.d-modal-panel[data-size="lg"]', [['max-width', '48rem']]);

  // Command palette — specialized modal variant with fixed 640px width
  // and specific search + list internal rhythm.
  emitRule('.d-palette', [
    ['width', '100%'],
    ['max-width', '40rem'],
    ['background', 'var(--d-surface-raised)'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius-lg)'],
    ['box-shadow', 'var(--d-shadow-lg)'],
    ['display', 'flex'],
    ['flex-direction', 'column'],
    ['overflow', 'hidden'],
    ['max-height', '60vh'],
  ]);

  // Search input at the top of the palette.
  emitRule('.d-palette-input', [
    ['padding', '1rem 1.25rem'],
    ['border', '0'],
    ['border-bottom', '1px solid var(--d-border)'],
    ['background', 'transparent'],
    ['color', 'var(--d-text)'],
    ['font-size', '1rem'],
    ['outline', '0'],
    ['width', '100%'],
  ]);

  // Scrollable list of commands.
  emitRule('.d-palette-list', [
    ['flex', '1'],
    ['overflow-y', 'auto'],
    ['padding', '0.5rem'],
  ]);

  // Individual command row.
  emitRule('.d-palette-row', [
    ['display', 'flex'],
    ['align-items', 'center'],
    ['gap', '0.75rem'],
    ['padding', '0.5rem 0.75rem'],
    ['border-radius', 'var(--d-radius-sm)'],
    ['cursor', 'pointer'],
    ['color', 'var(--d-text)'],
    ['font-size', '0.875rem'],
    ['transition', 'background 0.1s ease'],
  ]);

  emitRule('.d-palette-row:hover, .d-palette-row[data-active="true"]', [
    ['background', 'color-mix(in srgb, var(--d-primary) 10%, transparent)'],
  ]);

  // Section label inside a palette (e.g., "Navigation", "Settings").
  emitRule('.d-palette-section', [
    ['padding', '0.5rem 0.75rem 0.25rem'],
    ['font-size', '0.7rem'],
    ['font-weight', '600'],
    ['text-transform', 'uppercase'],
    ['letter-spacing', '0.08em'],
    ['color', 'var(--d-text-muted)'],
  ]);

  // Keyboard chip — mono-font key hint. Used in palette rows,
  // shortcut-help modals, and inline next to action buttons.
  emitRule('.d-kbd', [
    ['display', 'inline-flex'],
    ['align-items', 'center'],
    ['justify-content', 'center'],
    ['min-width', '1.5rem'],
    ['padding', '0 0.375rem'],
    ['height', '1.375rem'],
    ['border', '1px solid var(--d-border)'],
    ['border-radius', 'var(--d-radius-sm)'],
    ['background', 'var(--d-surface)'],
    ['color', 'var(--d-text-muted)'],
    ['font-family', 'var(--d-font-mono, ui-monospace, monospace)'],
    ['font-size', '0.75rem'],
    ['font-weight', '500'],
    ['line-height', '1'],
  ]);

  // ── Theme-scoped overrides (e.g. backdrop-filter) ──
  if (themeOverrideRules.length > 0) {
    lines.push('/* ── Theme-scoped Treatment Overrides ── */');
    lines.push('');
    for (const rule of themeOverrideRules) {
      lines.push(rule);
      lines.push('');
    }
  }

  // ── Keyframes (inside treatments layer) ──

  lines.push('/* ── Keyframes ── */');
  lines.push('');
  lines.push('@keyframes decantr-pulse {');
  lines.push('  0%, 100% { opacity: 1; }');
  lines.push('  50% { opacity: 0.5; }');
  lines.push('}');
  lines.push('');
  lines.push('} /* end @layer treatments */');

  const decoratorRules: string[] = [];
  if (themeDecoratorDefinitions) {
    // Emit a base rule plus optional state-variant pseudo-class rules.
    // Pseudo-class fields (:hover / :focus-visible / :active) are additive —
    // absent fields produce no rule, preserving prior behavior for themes
    // that haven't declared state variants yet.
    const emitProps = (selector: string, props: Record<string, string>) => {
      const entries = Object.entries(props);
      if (entries.length === 0) return;
      decoratorRules.push(`${selector} {`);
      for (const [prop, value] of entries) {
        decoratorRules.push(`  ${prop}: ${value};`);
        if (prop === 'animation') {
          const animationName = value.split(/\s+/)[0]?.trim();
          if (animationName) decoratorAnimationNames.add(animationName);
        }
      }
      decoratorRules.push('}');
      decoratorRules.push('');
    };
    for (const [className, definition] of Object.entries(themeDecoratorDefinitions)) {
      emitProps(`.${className}`, definition?.suggested_properties ?? {});
      emitProps(`.${className}:hover`, definition?.hover_properties ?? {});
      emitProps(`.${className}:focus-visible`, definition?.focus_properties ?? {});
      emitProps(`.${className}:active`, definition?.active_properties ?? {});
    }
  }

  const decoratorKeyframes: string[] = [];
  if (decoratorAnimationNames.has('carbon-fade-slide')) {
    decoratorKeyframes.push('@keyframes carbon-fade-slide {');
    decoratorKeyframes.push('  from { opacity: 0; transform: translateY(12px); }');
    decoratorKeyframes.push('  to { opacity: 1; transform: translateY(0); }');
    decoratorKeyframes.push('}');
    decoratorKeyframes.push('');
  }
  if (decoratorAnimationNames.has('pulse')) {
    decoratorKeyframes.push('@keyframes pulse {');
    decoratorKeyframes.push('  0%, 100% { opacity: 1; }');
    decoratorKeyframes.push('  50% { opacity: 0.5; }');
    decoratorKeyframes.push('}');
    decoratorKeyframes.push('');
  }

  const decoratorComments = themeDecorators
    ? Object.entries(themeDecorators)
        .map(([name, description]) => `  /* .${name}: ${description} */`)
        .join('\n')
    : '  /* No theme decorators available. */';
  const decoratorBody =
    decoratorRules.length > 0
      ? `${decoratorRules.join('\n')}${decoratorKeyframes.length > 0 ? `\n${decoratorKeyframes.join('\n')}` : ''}${decoratorComments ? `\n${decoratorComments}` : ''}`
      : `${decoratorComments}\n  /* Canonical decorator CSS should be derived from theme decorator definitions when available. */`;
  const decoratorBlock = `\n@layer decorators {\n${decoratorBody}\n}\n`;
  lines.push(decoratorBlock);

  return lines.join('\n');
}

/**
 * Generate personality-derived CSS utility classes based on keyword analysis.
 * Scans personality array for known keywords and emits matching utility rules.
 */
export function generatePersonalityCSS(
  personality: string[],
  themeData: { motion?: { entrance?: string }; palette?: Record<string, Record<string, string>> },
): string {
  const text = personality.join(' ').toLowerCase();
  const rules: string[] = [];

  // Neon glow utilities
  if (text.includes('neon') || text.includes('glow')) {
    const glowColor = 'var(--d-accent-glow, rgba(0, 212, 255, 0.3))';
    rules.push(`.neon-glow { box-shadow: 0 0 20px ${glowColor}; }`);
    rules.push(
      `.neon-glow-hover:hover { box-shadow: 0 0 24px ${glowColor}; transition: box-shadow var(--d-duration-hover, 0.15s) var(--d-easing, ease); }`,
    );
    rules.push(`.neon-text-glow { text-shadow: 0 0 12px ${glowColor}; }`);
    rules.push(
      `.neon-border-glow { border-color: var(--d-accent); box-shadow: 0 0 8px ${glowColor}; }`,
    );
  }

  // Monospace data utility
  if (text.includes('monospace') || text.includes('mono')) {
    rules.push(
      `.mono-data { font-family: var(--d-font-mono, ui-monospace, monospace); font-variant-numeric: tabular-nums; }`,
    );
  }

  // Status ring utilities
  if (text.includes('pulse') || text.includes('ring') || text.includes('status')) {
    rules.push(
      `.status-ring { width: 48px; height: 48px; border-radius: 50%; border: 2px solid var(--d-border); display: flex; align-items: center; justify-content: center; position: relative; transition: border-color 0.2s ease, box-shadow 0.2s ease; }`,
    );
    rules.push(`.status-ring[data-status="active"] { border-color: var(--d-success); }`);
    rules.push(
      `.status-ring[data-status="error"] { border-color: var(--d-error); box-shadow: 0 0 12px color-mix(in srgb, var(--d-error) 25%, transparent); }`,
    );
    rules.push(`.status-ring[data-status="warning"] { border-color: var(--d-warning); }`);
    rules.push(`.status-ring[data-status="idle"] { border-color: var(--d-text-muted); }`);
    rules.push(
      `.status-ring[data-status="processing"] { border-color: var(--d-primary); animation: pulse-ring 2s ease-in-out infinite; }`,
    );
    rules.push(
      `@keyframes pulse-ring { 0% { opacity: 0.6; transform: scale(1); } 100% { opacity: 0; transform: scale(1.3); } }`,
    );
    rules.push(
      `.status-ring[data-status="active"]::after { content: ''; position: absolute; inset: -4px; border-radius: 50%; border: 2px solid var(--d-success); opacity: 0; animation: pulse-ring 2s ease-out infinite; }`,
    );
  }

  // Entrance animation
  if (themeData.motion?.entrance) {
    rules.push(
      `.entrance-fade { animation: decantr-entrance var(--d-duration-entrance, 0.2s) var(--d-easing, ease-out); }`,
    );
    rules.push(
      `@keyframes decantr-entrance { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }`,
    );
  }

  if (rules.length === 0) return '';
  return (
    '\n@layer utilities {\n\n/* ── Personality-Derived Utilities ── */\n\n' +
    rules.join('\n\n') +
    '\n\n} /* end @layer utilities */\n'
  );
}
