/**
 * Extended Palette — 8 seed → unlimited series + continuous color scales.
 * @module _palette
 */

/**
 * Get chart color CSS variable for an index.
 * 0-7: base palette, 8-31: extended, 32+: cycles.
 * @param {number} index
 * @returns {string}
 */
export function chartColor(index) {
  return `var(--d-chart-${index % 8})`;
}

/**
 * Extended chart color with more variety beyond 8 series.
 * Uses extended palette tokens generated by derive.js.
 * @param {number} index
 * @returns {string}
 */
export function chartColorExtended(index) {
  if (index < 8) return `var(--d-chart-${index})`;
  if (index < 32) return `var(--d-chart-${index % 8}-ext-${Math.floor((index - 8) / 8) + 1})`;
  return `var(--d-chart-${index % 8})`;
}

/** Base palette size */
export const PALETTE_SIZE = 8;

/** Extended palette size (with 3 extensions per base) */
export const PALETTE_SIZE_EXTENDED = 32;

/**
 * Resolve palette to hex values for Canvas/WebGPU rendering.
 * @param {number} count
 * @param {HTMLElement} [el]
 * @returns {string[]}
 */
export function resolvePalette(count, el) {
  const colors = [];
  const target = el || (typeof document !== 'undefined' ? document.documentElement : null);
  const style = target && typeof getComputedStyle === 'function' ? getComputedStyle(target) : null;

  for (let i = 0; i < count; i++) {
    const prop = i < 8 ? `--d-chart-${i}` : `--d-chart-${i % 8}-ext-${Math.floor((i - 8) / 8) + 1}`;
    let color = style ? style.getPropertyValue(prop).trim() : '';
    if (!color) color = FALLBACK[i % FALLBACK.length];
    colors.push(color);
  }

  return colors;
}

/**
 * Create a continuous color scale.
 * @param {number[]} domain — [min, max] or [min, mid, max]
 * @param {string[]} stops — hex color stops
 * @returns {(value: number) => string}
 */
export function colorScale(domain, stops) {
  if (!stops || stops.length < 2) return () => stops?.[0] || '#000';
  const segments = stops.length - 1;
  const dMin = domain[0], dMax = domain[domain.length - 1];
  const dRange = dMax - dMin || 1;

  return function(value) {
    const t = Math.max(0, Math.min(1, (value - dMin) / dRange));
    const seg = Math.min(Math.floor(t * segments), segments - 1);
    const localT = t * segments - seg;
    return lerpColor(stops[seg], stops[seg + 1], localT);
  };
}

// --- Built-in color scales ---

export const scales = {
  /** Blue sequential */
  blues: ['#f0f9ff', '#bae6fd', '#38bdf8', '#0284c7', '#075985'],
  /** Red sequential */
  reds: ['#fef2f2', '#fca5a5', '#ef4444', '#b91c1c', '#7f1d1d'],
  /** Green sequential */
  greens: ['#f0fdf4', '#86efac', '#22c55e', '#15803d', '#14532d'],
  /** Red → White → Blue diverging */
  divergingRdBu: ['#ef4444', '#fca5a5', '#fafafa', '#93c5fd', '#3b82f6'],
  /** Purple → Orange diverging */
  divergingPrOr: ['#7c3aed', '#c4b5fd', '#fafafa', '#fed7aa', '#f97316'],
  /** Viridis-inspired */
  viridis: ['#440154', '#3b528b', '#21918c', '#5ec962', '#fde725'],
  /** Warm (yellow → red) */
  warm: ['#fef3c7', '#fbbf24', '#f59e0b', '#ea580c', '#dc2626'],
  /** Cool (cyan → purple) */
  cool: ['#ecfeff', '#67e8f9', '#06b6d4', '#7c3aed', '#4c1d95'],
};

// --- Internals ---

const FALLBACK = ['#1366D9', '#7c3aed', '#0891b2', '#22c55e', '#f59e0b', '#ef4444', '#3b82f6', '#71717a'];

function lerpColor(hex1, hex2, t) {
  const r1 = parseInt(hex1.slice(1, 3), 16), g1 = parseInt(hex1.slice(3, 5), 16), b1 = parseInt(hex1.slice(5, 7), 16);
  const r2 = parseInt(hex2.slice(1, 3), 16), g2 = parseInt(hex2.slice(3, 5), 16), b2 = parseInt(hex2.slice(5, 7), 16);
  const r = Math.round(r1 + (r2 - r1) * t), g = Math.round(g1 + (g2 - g1) * t), b = Math.round(b1 + (b2 - b1) * t);
  return '#' + [r, g, b].map(c => Math.max(0, Math.min(255, c)).toString(16).padStart(2, '0')).join('');
}
