import { execSync } from 'node:child_process';
import { cpSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const dist = join(root, 'dist');

// Check if essence.json exists with a blueprint — if so, use build-time resolver
const essencePath = join(root, 'decantr.essence.json');
let useBuildResolver = false;

if (existsSync(essencePath)) {
  try {
    const essence = JSON.parse(readFileSync(essencePath, 'utf-8'));
    if (essence.blueprint?.pages?.length > 0) {
      useBuildResolver = true;
    }
  } catch {
    // Invalid JSON or missing blueprint — fall through to Vite build
  }
}

if (useBuildResolver) {
  // Step 1: Build-time resolver generates static HTML from essence
  console.log('Essence blueprint detected — using build-time resolver...');

  // Still run Vite build first for JS/CSS bundling
  console.log('Building with Vite...');
  execSync('npx vite build', { cwd: root, stdio: 'inherit' });

  // Then run the build-time resolver to generate pre-rendered page HTML
  // This overlays static HTML on top of the Vite output
  try {
    const { buildFromEssence } = await import('@decantr/ui/build');
    const result = await buildFromEssence({
      essencePath,
      outDir: dist,
    });
    console.log(`Build-time resolver generated ${result.pages.length} page(s):`);
    for (const page of result.pages) {
      console.log(`  ${page.route} → ${page.pageId}`);
    }
  } catch (err) {
    console.warn('Build-time resolver failed, falling back to SPA mode:', err.message);
  }
} else {
  // No essence blueprint — standard Vite SPA build
  console.log('Building with Vite...');
  execSync('npx vite build', { cwd: root, stdio: 'inherit' });
}

// Step 2: Copy index.html to all route paths for GitHub Pages
// GitHub Pages serves index.html for / but 404s on /components without a file
const routes = [
  '/components',
  '/charts',
  '/icons',
  '/css',
  '/getting-started',
  '/why',
];

for (const route of routes) {
  const routeDir = join(dist, route);
  if (!existsSync(routeDir)) mkdirSync(routeDir, { recursive: true });
  // Only copy if not already generated by build-time resolver
  const routeIndex = join(routeDir, 'index.html');
  if (!existsSync(routeIndex)) {
    cpSync(join(dist, 'index.html'), routeIndex);
  }
}

// Dynamic routes (/components/:slug, /charts/:slug) are handled client-side
// GitHub Pages 404 fallback will serve the root index.html via 404.html
cpSync(join(dist, 'index.html'), join(dist, '404.html'));

console.log('Build complete! Output in dist/');
