/**
 * Decantr Migration Profile Compiler
 *
 * Scans project source files for usage of APIs listed in migration `changes`
 * manifests, then compiles a targeted `llm/task-age.md` profile containing
 * only the breaking/deprecated changes relevant to the specific project.
 *
 * Called by `cli/commands/age.js` step 5.
 *
 * @module tools/compile-age
 */

import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Recursively collect all .js files under a directory.
 */
async function collectJSFiles(dir) {
  const files = [];
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isDirectory() && entry.name !== 'node_modules') {
        files.push(...await collectJSFiles(full));
      } else if (entry.name.endsWith('.js')) {
        files.push(full);
      }
    }
  } catch { /* skip inaccessible dirs */ }
  return files;
}

/**
 * Scan a source file for usage of a symbol (import or bare reference).
 * Returns an array of { line, lineNumber } matches.
 */
function scanFileForSymbol(source, symbol, module) {
  const hits = [];
  const lines = source.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Check for import of the symbol from the module
    if (module && line.includes(module) && line.includes(symbol)) {
      hits.push({ line: line.trim(), lineNumber: i + 1 });
      continue;
    }

    // Check for bare usage of the symbol (function call, reference)
    // Avoid matching inside comments
    if (line.trimStart().startsWith('//') || line.trimStart().startsWith('*')) continue;
    if (line.includes(symbol + '(') || line.includes(symbol + ',') ||
        line.includes(symbol + ' ') || line.includes(symbol + ';') ||
        line.includes(symbol + '}') || line.endsWith(symbol)) {
      // Avoid double-counting the import line
      if (module && line.includes('import') && line.includes(module)) continue;
      hits.push({ line: line.trim(), lineNumber: i + 1 });
    }
  }

  return hits;
}

/**
 * Collect all changes from applicable migration modules in a version range.
 */
export function collectChanges(migrations) {
  const breaking = [];
  const deprecated = [];

  for (const m of migrations) {
    if (!m.changes) continue;
    if (Array.isArray(m.changes.breaking)) {
      for (const change of m.changes.breaking) {
        breaking.push({ ...change, since: m.version });
      }
    }
    if (Array.isArray(m.changes.deprecated)) {
      for (const change of m.changes.deprecated) {
        deprecated.push({ ...change, since: m.version });
      }
    }
  }

  return { breaking, deprecated };
}

/**
 * Scan source files and filter changes to only those used in the project.
 * Returns { relevant: [...], scannedFiles: number }.
 */
export async function scanForRelevantChanges(srcDir, changes) {
  const files = await collectJSFiles(srcDir);
  const allChanges = [...changes.breaking.map(c => ({ ...c, severity: 'breaking' })),
                      ...changes.deprecated.map(c => ({ ...c, severity: 'deprecated' }))];

  const relevant = [];

  for (const change of allChanges) {
    const fileHits = [];

    for (const filePath of files) {
      const source = await readFile(filePath, 'utf-8');
      const hits = scanFileForSymbol(source, change.symbol, change.module);
      if (hits.length > 0) {
        fileHits.push({ file: filePath, hits });
      }
    }

    if (fileHits.length > 0) {
      relevant.push({ ...change, fileHits });
    }
  }

  return { relevant, scannedFiles: files.length };
}

/**
 * Compile the migration profile markdown.
 */
export function compileProfile(fromVersion, toVersion, relevant, scannedFiles) {
  const lines = [];

  lines.push(`# Aging Profile: ${fromVersion} → ${toVersion}`);
  lines.push('');
  lines.push(`> Auto-generated by \`decantr age\`. ${relevant.length} change(s) affect this project (${scannedFiles} files scanned).`);
  lines.push('');

  if (relevant.length === 0) {
    lines.push('No source-level changes required. All transforms were handled automatically (essence + config).');
    return lines.join('\n');
  }

  // Group by severity
  const breaking = relevant.filter(c => c.severity === 'breaking');
  const deprecated = relevant.filter(c => c.severity === 'deprecated');

  if (breaking.length > 0) {
    lines.push('## Breaking Changes');
    lines.push('');
    for (const change of breaking) {
      lines.push(`### \`${change.symbol}\` (${change.type}, since ${change.since})`);
      lines.push('');
      if (change.module) lines.push(`**Module:** \`${change.module}\``);
      if (change.replacement) lines.push(`**Replacement:** \`${change.replacement}\``);
      lines.push('');
      if (change.guide) {
        lines.push(change.guide);
        lines.push('');
      }
      lines.push('**Affected files:**');
      for (const fh of change.fileHits) {
        for (const hit of fh.hits) {
          lines.push(`- \`${fh.file}\` line ~${hit.lineNumber}`);
        }
      }
      lines.push('');
    }
  }

  if (deprecated.length > 0) {
    lines.push('## Deprecated (update recommended)');
    lines.push('');
    for (const change of deprecated) {
      lines.push(`### \`${change.symbol}\` (since ${change.since}${change.until ? `, removal in ${change.until}` : ''})`);
      lines.push('');
      if (change.module) lines.push(`**Module:** \`${change.module}\``);
      if (change.replacement) lines.push(`**Replacement:** \`${change.replacement}\``);
      lines.push('');
      if (change.guide) {
        lines.push(change.guide);
        lines.push('');
      }
      lines.push('**Affected files:**');
      for (const fh of change.fileHits) {
        for (const hit of fh.hits) {
          lines.push(`- \`${fh.file}\` line ~${hit.lineNumber}`);
        }
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Full compile pipeline: collect changes, scan, compile, write.
 * Returns { written: boolean, relevant: number, scannedFiles: number, profile: string }.
 */
export async function compileAgeProfile(cwd, migrations, fromVersion, toVersion, { dryRun = false } = {}) {
  const changes = collectChanges(migrations);

  if (changes.breaking.length === 0 && changes.deprecated.length === 0) {
    return { written: false, relevant: 0, scannedFiles: 0, profile: null };
  }

  const srcDir = join(cwd, 'src');
  const { relevant, scannedFiles } = await scanForRelevantChanges(srcDir, changes);
  const profile = compileProfile(fromVersion, toVersion, relevant, scannedFiles);

  if (!dryRun) {
    const outDir = join(cwd, 'llm');
    try { await mkdir(outDir, { recursive: true }); } catch { /* exists */ }
    await writeFile(join(outDir, 'task-age.md'), profile, 'utf-8');
  }

  return { written: !dryRun, relevant: relevant.length, scannedFiles, profile };
}
