#!/usr/bin/env node

/**
 * TypeScript Declaration Generator for Decantr
 *
 * Reads module source files, parses JSDoc annotations and export signatures,
 * and generates `.d.ts` declaration files for every public module.
 *
 * Usage: node tools/dts-gen.js
 *
 * Zero dependencies — uses only Node.js built-ins + regex parsing.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');
const TYPES_DIR = join(ROOT, 'types');

// ─── Helpers ─────────────────────────────────────────────────────

function readSource(relPath) {
  const full = join(ROOT, relPath);
  if (!existsSync(full)) return null;
  return readFileSync(full, 'utf8');
}

/**
 * Extract named exports from an index.js barrel file.
 * Returns array of { names: string[], from: string|null }
 * Handles:
 *   export { Foo, Bar } from './foo.js';
 *   export function Foo(...)
 *   export const Foo = ...
 *   export { Foo }
 */
function parseExports(source) {
  const results = [];
  const reExportFrom = /export\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]/g;
  const reExportDecl = /export\s+(function|const|let|var|class)\s+(\w+)/g;

  let m;
  while ((m = reExportFrom.exec(source)) !== null) {
    const names = m[1].split(',').map(n => {
      const parts = n.trim().split(/\s+as\s+/);
      return parts.length > 1 ? parts[1].trim() : parts[0].trim();
    }).filter(Boolean);
    results.push({ names, from: m[2] });
  }

  while ((m = reExportDecl.exec(source)) !== null) {
    results.push({ names: [m[2]], from: null });
  }

  return results;
}

/**
 * Extract all exported names (flat list) from source.
 */
function getExportedNames(source) {
  const exports = parseExports(source);
  const names = [];
  for (const e of exports) {
    names.push(...e.names);
  }
  return [...new Set(names)];
}

/**
 * Parse function parameters from a function signature string.
 * Very basic: extracts param names from `function name(a, b, c)` or `(a, b, c) =>`.
 */
function parseFunctionParams(source, funcName) {
  // Match: export function funcName(...) or function funcName(...)
  const re = new RegExp(`(?:export\\s+)?function\\s+${funcName}\\s*\\(([^)]*)\\)`, 'm');
  const m = source.match(re);
  if (m) {
    return m[1].split(',').map(p => p.trim().replace(/\s*=\s*.+$/, '')).filter(Boolean);
  }
  return null;
}

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function writeDeclaration(filename, content) {
  const fullPath = join(TYPES_DIR, filename);
  writeFileSync(fullPath, content, 'utf8');
  return fullPath;
}

// ─── Module-Specific Declaration Generators ──────────────────────

function genCore() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/core' {
  /**
   * Create a DOM element via hyperscript.
   */
  export function h(tag: string, props?: Record<string, any> | null, ...children: any[]): HTMLElement;

  /**
   * Create a reactive text node from a getter function.
   */
  export function text(getter: () => string | number): Text;

  /**
   * Conditional rendering — renders trueBranch or falseBranch based on predicate.
   */
  export function cond(
    condition: () => boolean,
    thenFn: () => Node,
    elseFn?: () => Node
  ): HTMLElement;

  /**
   * Keyed list rendering with efficient reconciliation.
   */
  export function list(
    itemsGetter: () => any[],
    keyFn: (item: any, index: number) => string | number,
    renderFn: (item: any, index: number) => Node
  ): HTMLElement;

  /**
   * Mount a component to a DOM element.
   */
  export function mount(root: HTMLElement, component: () => Node): void;

  /**
   * Unmount a previously mounted component tree.
   */
  export function unmount(root: HTMLElement): void;

  /**
   * Register a callback to run after mount.
   */
  export function onMount(fn: () => void | (() => void)): void;

  /**
   * Register a callback to run on teardown.
   */
  export function onDestroy(fn: () => void): void;

  /**
   * Error catching component. Wraps children and catches render/effect errors.
   */
  export function ErrorBoundary(
    props: { fallback: (error: Error, retry: () => void) => Node },
    ...children: Node[]
  ): HTMLElement;

  /**
   * Render children into a different DOM target (e.g., document.body).
   */
  export function Portal(
    props?: { target?: string | HTMLElement },
    ...children: Node[]
  ): Comment;

  /**
   * Async boundary. Shows fallback while createQuery() calls in children are loading.
   */
  export function Suspense(
    props: { fallback: () => Node },
    ...children: Node[]
  ): HTMLElement;

  /**
   * Enter/exit animation wrapper for conditional content.
   */
  export function Transition(
    props: { enter?: string; exit?: string; duration?: number },
    child: () => Node | null
  ): HTMLElement;

  /**
   * Extract ref from props and pass it as second argument to a component.
   */
  export function forwardRef<P extends Record<string, any>>(
    component: (props: P, ref: ((el: HTMLElement) => void) | undefined, ...children: Node[]) => Node
  ): (props: P & { ref?: (el: HTMLElement) => void }, ...children: Node[]) => Node;
}
`;
}

function genState() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/state' {
  /**
   * Create a reactive signal primitive.
   * Returns a [getter, setter] tuple.
   */
  export function createSignal<T>(initialValue: T): [() => T, (value: T | ((prev: T) => T)) => void];

  /**
   * Create a reactive effect that auto-tracks signal dependencies.
   * Returns a dispose function.
   */
  export function createEffect(fn: () => void | (() => void)): () => void;

  /**
   * Create a cached derived computation.
   */
  export function createMemo<T>(fn: () => T): () => T;

  /**
   * Create a reactive proxy store with per-property tracking.
   */
  export function createStore<T extends object>(initialValue: T): T;

  /**
   * Batch multiple signal updates into one effect flush.
   */
  export function batch(fn: () => void): void;

  /**
   * Execute a function without subscribing to signal reads.
   */
  export function untrack<T>(fn: () => T): T;

  /**
   * Read a signal getter without subscribing. Alias for untrack().
   */
  export function peek<T>(getter: () => T): T;

  /**
   * Persistent signal backed by localStorage.
   */
  export function useLocalStorage<T>(key: string, initialValue: T): [() => T, (value: T | ((prev: T) => T)) => void];

  interface Context<T> {
    /** Provide a value. Returns a cleanup function to restore previous value. */
    Provider: (value: T) => () => void;
    /** Consume the current context value. */
    consume: () => T;
  }

  /**
   * Create a context for dependency injection.
   */
  export function createContext<T>(defaultValue?: T): Context<T>;

  /**
   * Create a selector — returns a function that produces a boolean signal
   * for whether a given key matches the source signal's value.
   */
  export function createSelector<T>(source: () => T): (key: T) => boolean;

  /**
   * Create a deferred/lazy memo that only computes on first read.
   */
  export function createDeferred<T>(fn: () => T): () => T;

  interface History<T> {
    canUndo: () => boolean;
    canRedo: () => boolean;
    undo: () => void;
    redo: () => void;
    clear: () => void;
  }

  /**
   * Create an undo/redo history tracker for a signal.
   */
  export function createHistory<T>(
    signal: [() => T, (value: T) => void],
    options?: { maxLength?: number }
  ): History<T>;
}
`;
}

function genRouter() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/router' {
  interface RouteConfig {
    /** Route path pattern (e.g., '/users/:id'). */
    path: string;
    /** Component function to render. */
    component?: (params?: Record<string, string>) => Node;
    /** Nested child routes. */
    children?: RouteConfig[];
    /** Optional named route. */
    name?: string;
    /** Arbitrary metadata merged parent→child, readable in guards via to.meta. */
    meta?: Record<string, any>;
  }

  interface RouterConfig {
    /** Routing strategy. Default: 'hash'. */
    mode?: 'hash' | 'history';
    /** Base path prefix for subdirectory deployments (e.g., '/app'). */
    base?: string;
    /** Route definitions. */
    routes: RouteConfig[];
    /** Enable View Transitions API for route changes. */
    transitions?: boolean;
    /** Scroll behavior on navigation. Default: 'top'. */
    scrollBehavior?: 'top' | 'restore' | false;
    /** Navigation guard — return false to cancel, string to redirect. */
    beforeEach?: (to: RouteMatch, from: RouteMatch) => void | false | string;
    /** Post-navigation hook. */
    afterEach?: (to: RouteMatch, from: RouteMatch) => void;
  }

  interface RouteMatch {
    path: string;
    params: Record<string, string>;
    query: Record<string, string>;
    component: Function | null;
    components: Function[];
    matched: boolean;
    name?: string;
    /** Merged route metadata (parent→child). */
    meta: Record<string, any>;
  }

  interface Router {
    /** Programmatic navigation. */
    navigate: (to: string | { name: string; params?: Record<string, string> }, opts?: { replace?: boolean }) => void;
    /** Create a route outlet element that renders the matched component. */
    outlet: (depth?: number) => HTMLElement;
    /** Signal getter for the current route match. */
    current: () => RouteMatch;
    /** Signal getter for the current path string. */
    path: () => string;
    /** Destroy the router and remove event listeners. */
    destroy: () => void;
    /** Subscribe to navigation events. Returns an unsubscribe function. */
    onNavigate: (callback: (to: RouteMatch, from: RouteMatch) => void) => () => void;
    /** Navigate back in history. */
    back: () => void;
    /** Navigate forward in history. */
    forward: () => void;
    /** Signal getter — true while lazy routes are resolving. */
    isNavigating: () => boolean;
  }

  /**
   * Create a router instance.
   */
  export function createRouter(config: RouterConfig): Router;

  /**
   * Navigate programmatically. Delegates to the active router.
   */
  export function navigate(
    to: string | { name: string; params?: Record<string, string> },
    opts?: { replace?: boolean }
  ): void;

  /**
   * Create a router-aware anchor element with active link detection.
   */
  export function link(
    props: { href: string; activeClass?: string; exact?: boolean; class?: string; [key: string]: any },
    ...children: any[]
  ): HTMLAnchorElement;

  /**
   * Get the current route signal from the active router.
   */
  export function useRoute(): () => RouteMatch;

  /**
   * Reactive search params. Returns [getter, setter] tuple.
   */
  export function useSearchParams(): [() => URLSearchParams, (params: Record<string, string> | URLSearchParams) => void];

  /**
   * Subscribe to navigation events on the active router. Returns an unsubscribe function.
   */
  export function onNavigate(callback: (to: RouteMatch, from: RouteMatch) => void): () => void;

  /**
   * Navigate back in history. Delegates to the active router.
   */
  export function back(): void;

  /**
   * Navigate forward in history. Delegates to the active router.
   */
  export function forward(): void;

  /**
   * Reactive boolean — true while lazy routes are resolving. Use for loading indicators.
   */
  export function isNavigating(): boolean;
}
`;
}

function genCSS() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/css' {
  /**
   * Compose atomic CSS class names. Injects styles on first use.
   */
  export function css(...classes: string[]): string;

  /**
   * Define a custom atomic CSS class.
   */
  export function define(name: string, declaration: string): void;

  /**
   * Get all generated CSS as a string.
   */
  export function extractCSS(): string;

  /**
   * Clear all injected styles.
   */
  export function reset(): void;

  /**
   * Sanitize a string for safe use in HTML attributes.
   */
  export function sanitize(str: string): string;

  // ── Style API (visual personality) ──

  /**
   * Set the active visual style.
   */
  export function setStyle(id: string): void;

  /**
   * Get the active style ID.
   */
  export function getStyle(): string;

  /**
   * Get list of registered styles.
   */
  export function getStyleList(): Array<{ id: string; name: string }>;

  interface StyleDefinition {
    id: string;
    name: string;
    seed: Record<string, string>;
    personality: Record<string, string>;
    typography?: Record<string, string>;
    overrides?: { light?: Record<string, string>; dark?: Record<string, string> };
    components?: string;
  }

  /**
   * Register a custom style.
   */
  export function registerStyle(style: StyleDefinition): void;

  // ── Mode API (light/dark) ──

  /**
   * Set the color mode.
   */
  export function setMode(mode: 'light' | 'dark' | 'auto'): void;

  /**
   * Get the current mode setting.
   */
  export function getMode(): 'light' | 'dark' | 'auto';

  /**
   * Get the resolved mode (always 'light' or 'dark', never 'auto').
   */
  export function getResolvedMode(): 'light' | 'dark';

  /**
   * Register callback for resolved mode changes. Returns unsubscribe function.
   */
  export function onModeChange(fn: (mode: 'light' | 'dark') => void): () => void;

  // ── Legacy / backward compat ──

  /**
   * Combines setStyle + setMode. Accepts legacy theme IDs.
   */
  export function setTheme(id: string, mode?: string): void;

  /**
   * Get the current theme object (backward compat).
   */
  export function getTheme(): Record<string, any>;

  /**
   * Get theme metadata.
   */
  export function getThemeMeta(): Record<string, any>;

  /**
   * Get list of available themes.
   */
  export function getThemeList(): Array<Record<string, any>>;

  /**
   * Register a theme (backward compat wrapper for registerStyle).
   */
  export function registerTheme(theme: Record<string, any>): void;

  /**
   * Get complete CSS for the active style's theme layer.
   */
  export function getActiveCSS(): string;

  /**
   * Reset to defaults (clean + light).
   */
  export function resetStyles(): void;

  /**
   * Enable/disable JS animations globally.
   */
  export function setAnimations(enabled: boolean): void;

  /**
   * Get a signal getter for the current animations-enabled state.
   */
  export function getAnimations(): () => boolean;

  /** Responsive breakpoint widths. */
  export const BREAKPOINTS: Record<string, number>;

  /** Container query widths. */
  export const CQ_WIDTHS: number[];
}
`;
}

function genTags() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/tags' {
  type TagFunction = (propsOrChild?: Record<string, any> | string | number | Node | (() => any), ...children: any[]) => HTMLElement;

  interface TagMap {
    [tag: string]: TagFunction;
    div: TagFunction;
    span: TagFunction;
    p: TagFunction;
    a: TagFunction;
    button: TagFunction;
    input: TagFunction;
    textarea: TagFunction;
    select: TagFunction;
    option: TagFunction;
    form: TagFunction;
    label: TagFunction;
    img: TagFunction;
    h1: TagFunction;
    h2: TagFunction;
    h3: TagFunction;
    h4: TagFunction;
    h5: TagFunction;
    h6: TagFunction;
    ul: TagFunction;
    ol: TagFunction;
    li: TagFunction;
    table: TagFunction;
    thead: TagFunction;
    tbody: TagFunction;
    tr: TagFunction;
    th: TagFunction;
    td: TagFunction;
    nav: TagFunction;
    header: TagFunction;
    footer: TagFunction;
    main: TagFunction;
    section: TagFunction;
    article: TagFunction;
    aside: TagFunction;
    details: TagFunction;
    summary: TagFunction;
    dialog: TagFunction;
    pre: TagFunction;
    code: TagFunction;
    em: TagFunction;
    strong: TagFunction;
    small: TagFunction;
    sub: TagFunction;
    sup: TagFunction;
    br: TagFunction;
    hr: TagFunction;
    svg: TagFunction;
    path: TagFunction;
  }

  /**
   * Proxy-based tag functions. Destructure what you need:
   * \`const { div, p, h2, button } = tags;\`
   */
  export const tags: TagMap;
}
`;
}

function genComponents() {
  // Read the actual index.js to get all exported names
  const source = readSource('src/components/index.js');
  const names = getExportedNames(source);

  // Classify exports: functions vs values
  // Known non-component exports
  const functionExports = new Set([
    'toast', 'resetToasts', 'icon', 'registerIcon', 'registerIcons',
    'notification', 'resetNotifications', 'message', 'resetMessages',
    'buttonVariants', 'createFormField'
  ]);

  let decls = `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/components' {
  // ── Component Props Base ──
  interface BaseProps {
    class?: string;
    style?: string | Record<string, string>;
    id?: string;
    'aria-label'?: string;
    'aria-labelledby'?: string;
    'aria-describedby'?: string;
    [key: string]: any;
  }

`;

  // Component functions (accept props, return HTMLElement)
  for (const name of names) {
    if (functionExports.has(name)) continue;
    decls += `  /**
   * ${name} component.
   */
  export function ${name}(props?: BaseProps & Record<string, any>, ...children: any[]): HTMLElement;

`;
  }

  // Special exports
  decls += `  /**
   * Button variant class generator.
   */
  export function buttonVariants(props?: Record<string, any>): string;

  /**
   * Create an icon element by name.
   */
  export function icon(name: string, props?: { size?: number | string; class?: string; [key: string]: any }): SVGElement;

  /**
   * Register a custom icon.
   */
  export function registerIcon(name: string, pathData: string): void;

  /**
   * Register multiple icons at once.
   */
  export function registerIcons(iconMap: Record<string, string>): void;

  /**
   * Show a toast notification. Returns a dismiss function.
   */
  export function toast(props: {
    title?: string;
    description?: string;
    variant?: 'default' | 'success' | 'error' | 'warning' | 'info';
    duration?: number;
    action?: { label: string; onClick: () => void };
    [key: string]: any;
  }): () => void;

  /**
   * Clear all active toasts.
   */
  export function resetToasts(): void;

  /**
   * Show a notification. Returns a dismiss function.
   */
  export function notification(props: {
    title?: string;
    description?: string;
    variant?: string;
    duration?: number;
    placement?: string;
    [key: string]: any;
  }): () => void;

  /**
   * Clear all active notifications.
   */
  export function resetNotifications(): void;

  /**
   * Show a message. Returns a dismiss function.
   */
  export function message(props: {
    content?: string;
    type?: 'info' | 'success' | 'warning' | 'error' | 'loading';
    duration?: number;
    [key: string]: any;
  }): () => void;

  /**
   * Clear all active messages.
   */
  export function resetMessages(): void;

  /**
   * Create a reactive form field binding helper.
   */
  export function createFormField(form: any, fieldName: string): Record<string, any>;
}
`;

  return decls;
}

function genForm() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/form' {
  // ── Validator Types ──

  type SyncValidator = (value: any, allValues?: Record<string, any>) => string | null;
  type AsyncValidator = (value: any, allValues?: Record<string, any>) => Promise<string | null>;

  interface Validators {
    /** Value must be truthy (non-empty). */
    required(msg?: string): SyncValidator;
    /** String length must be >= n. */
    minLength(n: number, msg?: string): SyncValidator;
    /** String length must be <= n. */
    maxLength(n: number, msg?: string): SyncValidator;
    /** Numeric value must be >= n. */
    min(n: number, msg?: string): SyncValidator;
    /** Numeric value must be <= n. */
    max(n: number, msg?: string): SyncValidator;
    /** Value must match regex pattern. */
    pattern(regex: RegExp, msg?: string): SyncValidator;
    /** Must be a valid email address. */
    email(msg?: string): SyncValidator;
    /** Value must equal another field's current value. */
    match(fieldName: string, msg?: string): SyncValidator;
    /** Custom synchronous validator. */
    custom(fn: (value: any, allValues: Record<string, any>) => true | string, msg?: string): SyncValidator;
    /** Async validator (auto-debounced 300ms). */
    async(fn: (value: any, allValues: Record<string, any>) => Promise<true | string>, msg?: string): AsyncValidator;
  }

  export const validators: Validators;

  // ── Field Instance ──

  interface FieldInstance {
    readonly name: string;
    /** Signal getter for current value. */
    value: () => any;
    /** First error message or null. */
    error: () => string | null;
    /** All error messages. */
    errors: () => string[];
    /** Whether field has been blurred. */
    touched: () => boolean;
    /** Whether value differs from initial. */
    dirty: () => boolean;
    /** Whether field has no errors. */
    valid: () => boolean;
    /** Set a new value. */
    setValue: (value: any) => void;
    /** Mark as touched. */
    setTouched: () => void;
    /** Set an error manually. */
    setError: (msg: string) => void;
    /** Reset to initial value. */
    reset: (value?: any) => void;
    /** Run all validators. Returns true if valid. */
    validate: () => Promise<boolean>;
    /** Get binding props for Decantr form components. */
    bind: () => { value: () => any; onchange: (v: any) => void; onblur: () => void; error: () => string | null };
  }

  // ── Field Array Instance ──

  interface FieldArrayInstance {
    /** Signal getter for array of items. */
    items: () => any[];
    /** Reactive item count. */
    length: () => number;
    /** Append a value to the end. */
    append: (value: any) => void;
    /** Prepend a value to the beginning. */
    prepend: (value: any) => void;
    /** Remove item at index. */
    remove: (index: number) => void;
    /** Move item from one index to another. */
    move: (from: number, to: number) => void;
    /** Swap two items by index. */
    swap: (a: number, b: number) => void;
    /** Replace item at index. */
    replace: (index: number, value: any) => void;
  }

  // ── Form Instance ──

  interface FieldConfig {
    /** Initial value. */
    value?: any;
    /** Array of validator functions. */
    validators?: Array<SyncValidator | AsyncValidator>;
    /** Transform function applied on setValue. */
    transform?: (raw: any) => any;
  }

  interface FormConfig {
    /** Field definitions. */
    fields: Record<string, FieldConfig>;
    /** Submit handler. */
    onSubmit?: (values: Record<string, any>, form: FormInstance) => void | Promise<void>;
    /** Cross-field validation returning \`{ fieldName: string[] }\`. */
    validate?: (values: Record<string, any>) => Record<string, string[]> | void;
    /** When to trigger validation. Default: 'onBlur'. */
    validateOn?: 'onChange' | 'onBlur' | 'onSubmit';
  }

  interface FormInstance {
    /** Get or create a field by name. */
    field: (name: string) => FieldInstance;
    /** Proxy for field access via dot notation (form.fields.email). */
    fields: Record<string, FieldInstance>;
    /** Signal getter for all current values. */
    values: () => Record<string, any>;
    /** Signal getter for all errors \`{ fieldName: string[] }\`. */
    errors: () => Record<string, string[]>;
    /** Signal getter for overall form validity. */
    isValid: () => boolean;
    /** Signal getter for whether any field is dirty. */
    isDirty: () => boolean;
    /** Signal getter for submitting state. */
    isSubmitting: () => boolean;
    /** Signal getter for submitted state. */
    isSubmitted: () => boolean;
    /** Signal getter for submit count. */
    submitCount: () => number;
    /** Submit the form. */
    submit: () => Promise<void>;
    /** Reset all fields. */
    reset: (values?: Record<string, any>) => void;
    /** Set multiple field values at once. */
    setValues: (partial: Record<string, any>) => void;
    /** Set errors on multiple fields. */
    setErrors: (errors: Record<string, string | string[]>) => void;
    /** Run all validators. Returns true if valid. */
    validate: () => Promise<boolean>;
    /** Get or create a field array. */
    fieldArray: (name: string) => FieldArrayInstance;
    /** Watch a specific field for value changes. Returns unsubscribe. */
    watch: (fieldName: string, callback: (value: any, prevValue: any) => void) => () => void;
    /** Watch all fields for any change. Returns unsubscribe. */
    watchAll: (callback: (values: Record<string, any>) => void) => () => void;
  }

  /**
   * Create a reactive form instance.
   */
  export function createForm(config: FormConfig): FormInstance;

  interface UseFormFieldResult {
    value: () => any;
    setValue: (value: any) => void;
    error: () => string | null;
    errors: () => string[];
    touched: () => boolean;
    dirty: () => boolean;
    valid: () => boolean;
    onBlur: () => void;
    bind: () => { value: () => any; onchange: (v: any) => void; onblur: () => void; error: () => string | null };
  }

  /**
   * Hook for binding a form field to a custom component.
   */
  export function useFormField(form: FormInstance, fieldName: string): UseFormFieldResult;
}
`;
}

function genIcons() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/icons' {
  /**
   * Get SVG inner content for an icon by name.
   */
  export function getIconPath(name: string): string | null;

  /**
   * Register a custom icon (or override an existing one).
   */
  export function registerIcon(name: string, pathData: string): void;

  /**
   * Register multiple icons at once.
   */
  export function registerIcons(iconMap: Record<string, string>): void;

  /**
   * Check if an icon is available.
   */
  export function hasIcon(name: string): boolean;

  /**
   * Get all currently available icon names.
   */
  export function getIconNames(): string[];
}
`;
}

function genChart() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/chart' {
  interface ChartSpec {
    /** Chart type. Default: 'line'. */
    type?: 'line' | 'bar' | 'area' | 'pie';
    /** Data array or reactive signal getter. */
    data?: any[] | (() => any[]);
    /** X-axis field name. Default: 'x'. */
    x?: string;
    /** Y-axis field name(s). Default: 'y'. */
    y?: string | string[];
    /** Chart title. */
    title?: string;
    /** Show tooltip. Default: true. */
    tooltip?: boolean | ((info: { label: string; value: string; element: Element }) => Node);
    /** Show legend. Default: true. */
    legend?: boolean;
    /** Show grid lines. Default: true. */
    grid?: boolean;
    /** Stack series. Default: false. */
    stacked?: boolean;
    /** Animate transitions. Default: true. */
    animate?: boolean;
    /** Render mode. Default: 'auto'. */
    renderer?: 'auto' | 'svg' | 'canvas';
    /** Chart height CSS value. Default: '300px'. */
    height?: string;
    /** Donut mode for pie charts. Default: true. */
    donut?: boolean;
    /** Show accessible data table fallback. Default: true. */
    tableAlt?: boolean;
    /** CSS class for the container. */
    class?: string;
    /** Accessible label. */
    'aria-label'?: string;
    [key: string]: any;
  }

  /**
   * Validate and fill defaults for a chart spec.
   */
  export function chartSpec(overrides?: Partial<ChartSpec>): ChartSpec;

  /**
   * Create a chart DOM element from a declarative spec.
   */
  export function Chart(spec: ChartSpec): HTMLElement;

  interface SparklineSpec {
    /** Data array or reactive signal getter. */
    data: number[] | (() => number[]);
    /** Height in pixels. Default: '32'. */
    height?: string;
    /** Width in pixels. Default: '120'. */
    width?: string;
    /** CSS class. */
    class?: string;
    /** Accessible label. */
    'aria-label'?: string;
    [key: string]: any;
  }

  /**
   * Create an inline sparkline element.
   */
  export function Sparkline(spec: SparklineSpec): HTMLElement;

  /**
   * Get the CSS color for a chart series index.
   */
  export function chartColor(index: number): string;

  /**
   * Number of colors in the chart palette.
   */
  export const PALETTE_SIZE: number;
}
`;
}

function genTest() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/test' {
  import type { TestContext } from 'node:test';

  export function describe(name: string, fn: () => void): void;
  export function it(name: string, fn: (t?: TestContext) => void | Promise<void>): void;
  export function test(name: string, fn: (t?: TestContext) => void | Promise<void>): void;
  export function before(fn: () => void | Promise<void>): void;
  export function after(fn: () => void | Promise<void>): void;
  export function beforeEach(fn: () => void | Promise<void>): void;
  export function afterEach(fn: () => void | Promise<void>): void;
  export function mock(target: any): any;

  export const assert: typeof import('node:assert/strict');

  interface DOMEnvironment {
    document: Document;
    cleanup: () => void;
  }

  /**
   * Create an isolated DOM environment for testing.
   */
  export function createDOM(): DOMEnvironment;

  interface RenderResult {
    container: Element;
    getByText: (text: string) => Element | null;
    getByClass: (cls: string) => Element | null;
    getById: (id: string) => Element | null;
    cleanup: () => void;
  }

  /**
   * Render a component for testing.
   */
  export function render(component: () => Node): RenderResult;

  /**
   * Dispatch a DOM event on an element.
   */
  export function fire(el: Element, event: string, detail?: Record<string, any>): void;

  /**
   * Flush pending reactive effects.
   */
  export function flush(): Promise<void>;
}
`;
}

function genI18n() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/i18n' {
  /**
   * Configuration for creating an i18n instance.
   */
  export interface I18nConfig {
    /** Initial active locale (e.g. 'en', 'fr', 'ar'). */
    locale: string;
    /** Messages keyed by locale. Each locale maps keys to strings or nested objects. */
    messages: Record<string, Record<string, any>>;
    /** Fallback locale used when a key is missing in the active locale. */
    fallbackLocale?: string;
  }

  /**
   * An i18n instance returned by createI18n().
   */
  export interface I18nInstance {
    /**
     * Translate a key with optional interpolation and pluralization.
     *
     * - Dot notation: \`t('nav.home')\` resolves nested objects.
     * - Interpolation: \`t('hello', { name: 'World' })\` replaces \`{name}\`.
     * - Pluralization: \`t('items', { count: 3 })\` appends \`_one\`/\`_other\` suffix
     *   via \`Intl.PluralRules\`.
     * - Fallback chain: current locale -> fallback locale -> raw key.
     */
    t: (key: string, params?: Record<string, any>) => string;

    /** Signal getter for the current locale. */
    locale: () => string;

    /** Set the active locale. Reactively updates all \`t()\` consumers. */
    setLocale: (locale: string) => void;

    /** Set the document direction attribute ('ltr' or 'rtl'). */
    setDirection: (dir: 'ltr' | 'rtl') => void;

    /** Merge additional messages into a locale at runtime. */
    addMessages: (locale: string, messages: Record<string, any>) => void;
  }

  /**
   * Create a reactive i18n instance.
   *
   * The returned \`t()\` function is reactive — it reads the internal locale
   * signal, so any \`createEffect\` or \`createMemo\` that calls \`t()\` will
   * re-run when the locale changes via \`setLocale()\`.
   */
  export function createI18n(config: I18nConfig): I18nInstance;
}
`;
}

function genTannins() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
declare module 'decantr/tannins/auth' {
  export interface AuthConfig {
    /** POST endpoint for login. Default: '/api/auth/login'. */
    loginEndpoint?: string;
    /** POST endpoint for token refresh. Default: '/api/auth/refresh'. */
    refreshEndpoint?: string;
    /** POST endpoint for logout. Default: '/api/auth/logout'. */
    logoutEndpoint?: string;
    /** Storage key for the persisted token. Default: 'decantr_auth_token'. */
    tokenKey?: string;
    /** Which storage to use for token persistence. Default: 'localStorage'. */
    storage?: 'localStorage' | 'sessionStorage';
    /** Called whenever the isAuthenticated state changes. */
    onAuthChange?: (isAuthenticated: boolean) => void;
  }

  export interface AuthInstance {
    /** Signal getter for the current user object (null when not logged in). */
    user: () => any;
    /** Signal getter for the current auth token (null when not authenticated). */
    token: () => string | null;
    /** Derived signal — true when token is non-null. */
    isAuthenticated: () => boolean;
    /** Signal getter — true during login/logout/refresh operations. */
    isLoading: () => boolean;
    /** Signal getter for the last auth error (null when no error). */
    error: () => any;
    /** POST credentials to loginEndpoint. Sets token + user on success. */
    login: (credentials: Record<string, any>) => Promise<any>;
    /** Clear local auth state. Optionally POSTs to logoutEndpoint. */
    logout: () => Promise<void>;
    /** POST to refreshEndpoint to obtain a new token. */
    refresh: () => Promise<void>;
    /** Manually set the user object. */
    setUser: (user: any) => void;
    /** Manually set the auth token (or null to clear). */
    setToken: (token: string | null) => void;
    /** Remove fetch middleware and clean up reactive effects. */
    destroy: () => void;
  }

  /**
   * Create an auth instance with reactive signals, token persistence,
   * login/logout/refresh flows, and automatic fetch middleware.
   */
  export function createAuth(config?: AuthConfig): AuthInstance;

  export interface RequireAuthOptions {
    /** Path to redirect unauthenticated users to. Default: '/login'. */
    loginPath?: string;
    /** Query parameter name for the redirect URL. Default: 'redirect'. */
    redirectParam?: string;
    /** Custom authentication check function. */
    isAuthenticated?: () => boolean;
  }

  /**
   * Install a route guard that redirects unauthenticated users to a login page.
   * Returns a cleanup function to remove the guard.
   */
  export function requireAuth(router: any, options?: RequireAuthOptions): () => void;
}
`;
}

function genIndex() {
  return `// Auto-generated by tools/dts-gen.js — do not edit manually
// Master declaration file — re-exports all Decantr modules.

/// <reference path="./core.d.ts" />
/// <reference path="./state.d.ts" />
/// <reference path="./router.d.ts" />
/// <reference path="./css.d.ts" />
/// <reference path="./tags.d.ts" />
/// <reference path="./components.d.ts" />
/// <reference path="./form.d.ts" />
/// <reference path="./icons.d.ts" />
/// <reference path="./chart.d.ts" />
/// <reference path="./i18n.d.ts" />
/// <reference path="./tannins.d.ts" />
/// <reference path="./test.d.ts" />
`;
}

// ─── Main ────────────────────────────────────────────────────────

function main() {
  console.log('Decantr .d.ts Declaration Generator');
  console.log('===================================\n');

  ensureDir(TYPES_DIR);

  const generators = [
    ['core.d.ts', genCore],
    ['state.d.ts', genState],
    ['router.d.ts', genRouter],
    ['css.d.ts', genCSS],
    ['tags.d.ts', genTags],
    ['components.d.ts', genComponents],
    ['form.d.ts', genForm],
    ['icons.d.ts', genIcons],
    ['chart.d.ts', genChart],
    ['test.d.ts', genTest],
    ['i18n.d.ts', genI18n],
    ['tannins.d.ts', genTannins],
    ['index.d.ts', genIndex],
  ];

  const generated = [];

  for (const [filename, genFn] of generators) {
    try {
      const content = genFn();
      const fullPath = writeDeclaration(filename, content);
      const lines = content.split('\n').length;
      generated.push({ filename, lines, fullPath });
      console.log(`  ✓ ${filename} (${lines} lines)`);
    } catch (err) {
      console.error(`  ✗ ${filename}: ${err.message}`);
    }
  }

  console.log(`\n${generated.length} declaration files generated in types/`);

  // Summary table
  const totalLines = generated.reduce((sum, g) => sum + g.lines, 0);
  console.log(`Total: ${totalLines} lines of TypeScript declarations\n`);

  // Module mapping summary
  console.log('Module mapping:');
  const mapping = {
    'decantr/core': 'types/core.d.ts',
    'decantr/state': 'types/state.d.ts',
    'decantr/router': 'types/router.d.ts',
    'decantr/css': 'types/css.d.ts',
    'decantr/tags': 'types/tags.d.ts',
    'decantr/components': 'types/components.d.ts',
    'decantr/form': 'types/form.d.ts',
    'decantr/icons': 'types/icons.d.ts',
    'decantr/chart': 'types/chart.d.ts',
    'decantr/test': 'types/test.d.ts',
    'decantr/i18n': 'types/i18n.d.ts',
    'decantr/tannins/auth': 'types/tannins.d.ts',
  };
  for (const [mod, file] of Object.entries(mapping)) {
    console.log(`  ${mod} → ${file}`);
  }
}

main();
