#!/usr/bin/env node
/**
 * Generic SVG icon importer — reads a directory of SVG files, extracts inner
 * content, and writes a JS module that can be loaded via registerIcons().
 *
 * Usage:
 *   node tools/icons.js <svg-dir> [output.js]
 *
 * Examples:
 *   node tools/icons.js ./my-icons                    → src/icons/custom.js
 *   node tools/icons.js ./brand-icons brand.js         → src/icons/brand.js
 *   node tools/icons.js node_modules/some-icons/svgs   → src/icons/custom.js
 *
 * The generated file exports an ICONS object. Import and register in your app:
 *   import { ICONS } from './icons/custom.js';
 *   import { registerIcons } from 'decantr/icons';
 *   registerIcons(ICONS);
 *
 * Also regenerates src/registry/icons.json with the current essential icon list.
 *
 * Run with no arguments to just regenerate the registry from essential.js:
 *   node tools/icons.js
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const iconsOutDir = join(root, 'src', 'icons');
const registryDir = join(root, 'src', 'registry');

/**
 * Extract the inner content of an SVG, stripping the outer <svg> wrapper.
 */
function extractInner(svgContent) {
  let s = svgContent.replace(/<!--[\s\S]*?-->/g, '');
  s = s.replace(/<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  s = s.replace(/\s+/g, ' ').trim();
  return s;
}

/**
 * Read a directory of SVG files and return { name: innerContent } map.
 */
function importSVGs(dir) {
  const absDir = resolve(dir);
  if (!existsSync(absDir)) {
    console.error(`Directory not found: ${absDir}`);
    process.exit(1);
  }
  const files = readdirSync(absDir).filter(f => f.endsWith('.svg')).sort();
  if (files.length === 0) {
    console.error(`No .svg files found in: ${absDir}`);
    process.exit(1);
  }
  const icons = {};
  for (const file of files) {
    const name = basename(file, '.svg');
    const svg = readFileSync(join(absDir, file), 'utf-8');
    icons[name] = extractInner(svg);
  }
  return icons;
}

/**
 * Write icon data as a JS module.
 */
function writeIconModule(icons, outPath) {
  const entries = Object.entries(icons)
    .map(([k, v]) => `  '${k}': '${v.replace(/'/g, "\\'")}'`)
    .join(',\n');
  writeFileSync(outPath,
    `// Generated by tools/icons.js — do not edit\nexport const ICONS = {\n${entries}\n};\n`
  );
}

/**
 * Regenerate src/registry/icons.json from essential.js.
 */
function updateRegistry() {
  const essentialPath = join(iconsOutDir, 'essential.js');
  if (!existsSync(essentialPath)) return;

  const source = readFileSync(essentialPath, 'utf-8');
  const names = [];
  const re = /'([a-z][a-z0-9-]*)'\s*:/g;
  let m;
  while ((m = re.exec(source)) !== null) names.push(m[1]);

  mkdirSync(registryDir, { recursive: true });
  writeFileSync(join(registryDir, 'icons.json'), JSON.stringify({
    generated: new Date().toISOString().split('T')[0],
    source: 'decantr original icons',
    essential: names.sort(),
    essentialCount: names.length,
    api: {
      'icon(name, opts?)': 'Render icon as <span> with CSS mask-image',
      'registerIcon(name, svgInner)': 'Add a single custom icon',
      'registerIcons(map)': 'Bulk-register icons from { name: svgInner }',
      'hasIcon(name)': 'Check if icon is available',
      'getIconNames()': 'List all available icon names'
    },
    importGuide: 'node tools/icons.js <svg-dir> [output.js] — import SVG directory as JS module'
  }, null, 2) + '\n');

  console.log(`Registry: src/registry/icons.json (${names.length} essential icons)`);
}

// --- Main ---

const args = process.argv.slice(2);

if (args.length >= 1) {
  // Import mode: read SVG directory, write JS module
  const svgDir = args[0];
  const outName = args[1] || 'custom.js';
  const outPath = outName.includes('/') ? resolve(outName) : join(iconsOutDir, outName);

  mkdirSync(dirname(outPath), { recursive: true });
  const icons = importSVGs(svgDir);
  writeIconModule(icons, outPath);

  console.log(`Imported ${Object.keys(icons).length} icons from ${svgDir}`);
  console.log(`  → ${outPath}`);
  console.log(`\nUsage in your app:`);
  console.log(`  import { ICONS } from './icons/${basename(outPath)}';`);
  console.log(`  import { registerIcons } from 'decantr/icons';`);
  console.log(`  registerIcons(ICONS);`);
}

// Always update registry
updateRegistry();
