export type {
  FetchTelemetrySinkOptions,
  TelemetryClient,
  TelemetryClientOptions,
  TelemetrySink,
} from './client.js';
export {
  createFetchTelemetrySink,
  createNoopTelemetrySink,
  createTelemetryClient,
} from './client.js';
export type {
  AdoptionMode,
  AuditCompletedProperties,
  CampaignAttributionProperties,
  BillingCheckoutBlockedProperties,
  BillingPlanClickedProperties,
  CliCommandCompletedProperties,
  ContentPublishCompletedProperties,
  ContentValidationCompletedProperties,
  CritiqueCompletedProperties,
  DecantrAnalyzeCompletedProperties,
  DecantrTelemetryEvent,
  DecantrTelemetryEventName,
  DecantrLifecycleCompletedProperties,
  ExecutionPackCompiledProperties,
  ExecutionPackSelectedProperties,
  HealthCiFailedProperties,
  HealthFindingPromptRequestedProperties,
  MarketingWebCommandClickedProperties,
  MarketingWebCtaClickedProperties,
  MarketingWebOutboundClickedProperties,
  MarketingWebPageViewedProperties,
  PrivateRegistryContentListedProperties,
  PrivateRegistryGateViewedProperties,
  PrivateRegistryIntentClickedProperties,
  ProductEventProperties,
  ProjectHealthFailOn,
  ProjectHealthFindingSeverity,
  ProjectHealthFindingSource,
  ProjectHealthOutputFormat,
  ProjectHealthTelemetryProperties,
  ProjectHealthTelemetryStatus,
  ProjectScope,
  RegistryItemResolvedProperties,
  RegistrySource,
  RegistrySyncCompletedProperties,
  RegistryWebCommercialPageViewedProperties,
  RegistryWebContentOpenedProperties,
  RegistryWebPageViewedProperties,
  RegistryWebSearchPerformedProperties,
  TelemetryEventCatalogEntry,
  TelemetryActorResolutionOptions,
  TelemetryActorType,
  TelemetryAnalysisScope,
  TelemetryContentType,
  TelemetryContext,
  TelemetryEnvironment,
  TelemetryProperties,
  TelemetryPropertyValue,
  TelemetryPrivacyClass,
  TelemetrySignalBucket,
  TelemetrySource,
  TelemetryVisibility,
  TelemetryIdentityLinkedProperties,
  StudioHealthRefreshedProperties,
  StudioStartedProperties,
  WorkflowMode,
} from './events.js';
export {
  DECANTR_TELEMETRY_ACCEPTED_SCHEMA_VERSIONS,
  DECANTR_TELEMETRY_ACTOR_TYPES,
  DECANTR_TELEMETRY_EVENT_CATALOG,
  DECANTR_TELEMETRY_EVENT_NAMES,
  DECANTR_TELEMETRY_SCHEMA_VERSION,
  isDecantrTelemetryEventName,
  getTelemetryEventCatalogEntry,
  isDecantrTelemetrySchemaVersion,
  isTelemetryActorType,
  isTelemetryEventAllowedForSource,
  resolveTelemetryActorType,
} from './events.js';
export type { PostHogTelemetrySinkOptions } from './posthog.js';
export { createPostHogTelemetrySink } from './posthog.js';
export type { TelemetryRedactionOptions } from './privacy.js';
export {
  isSensitiveTelemetryKey,
  REDACTED_VALUE,
  sanitizeTelemetryEvent,
  sanitizeTelemetryValue,
} from './privacy.js';
